from pathlib import Path
import json,hashlib,statistics,math
w=Path('/private/tmp/amu-private-length-clones-20261006');remote=w/'remote-evidence';p=remote/'timing-package';load=lambda f:json.loads(f.read_text());sha=lambda f:hashlib.sha256(f.read_bytes()).hexdigest();pre=load(p/'preflight.json');batch=load(remote/'batch-status.json');spec=load(p/'paired-timing-spec.json');assert batch['status']=='terminal-all-changed-guests-attempted';assert batch['changedGuests']==pre['changedGuests'];rows=[];total=0
for name,digest in pre['proofPins'].items():assert sha(p/name)==digest
pc=load(p/'candidate-proof.json');pb=load(p/'product-proof.json');matrix=load(p/'comparison-matrix.json')
for name in pre['changedGuests']:
 d=p/name;x=load(d/'timing/results.json');assert x['status']=='complete-provisional-candidate-timing';manifest=load(d/'candidate/manifest.json');assert x['manifest']==manifest;assert x['runnerSha256']=='a1b8778cf9af255f66bba3e3cad20e3baadd9653e18defe429bfa179840665ac';assert sha(p/'paired-timing-spec.json')==x['specSha256'];assert sha(d/'baseline-native.bin')==manifest['baselineNativeSha256'];assert sha(d/'candidate/native.bin')==manifest['nativeSha256'];baseline=load(d/'baseline/results.json');e=baseline['entries'][0];assert sha(d/'baseline/results.json')==x['baselineResultsSha256'];assert sha(p/'comparison-matrix.json')==baseline['matrixSpecSha256'];control=next(v for v in matrix['entries'] if v['workload']==name);cp=next(v for v in pc['entries'] if v['workload']==name);bp=next(v for v in pb['entries'] if v['workload']==name);assert manifest['sourceSha256']==manifest['baselineSourceSha256']==control['expectedSourceSha256']==cp['sourceSha256']==bp['sourceSha256'];assert manifest['nativeSha256']==cp['nativeSha256'] and manifest['baselineNativeSha256']==bp['nativeSha256'];assert manifest['offset']==cp['offset'] and manifest['baselineOffset']==bp['offset'];assert cp['runs']==bp['runs'];assert sha(d/'baseline'/name/'c.dylib')==e['cDylibSha256'];assert e['offset']==manifest['baselineOffset'];assert len(set(manifest['compilerGenerationSha256'].values()))==1;groups={}
 for z in x['rows']:groups.setdefault(z['attempt'],[]).append(z)
 assert len(groups)==x['attemptedTriples'] and all(len(g)==3 and {z['arm'] for z in g}=={'baseline','candidate','C'} and len({z['accepted'] for z in g})==1 for g in groups.values());assert sum(g[0]['accepted'] for g in groups.values())==30==x['acceptedTriples'];n=e['iterationsPerCall'];summaries={}
 for arm in ['baseline','candidate','C']:
  zs=[z for z in x['rows'] if z['arm']==arm and z['accepted']];assert len(zs)==30
  for z in zs:
   assert not z['rejectionReasons'] and z['result']==1 and z['warmupCalls']==spec['warmupCalls'];assert max(z['loadBefore'],z['loadAfter'])<=spec['maximumLoad'];assert z['elapsedNanoseconds']>=spec['minimumIntervalNs'];assert z['cpuActivityEnvelope']['estimatedBackgroundIdlePercent']>=spec['minimumBackgroundIdlePercent']
   if arm!='C':assert z['contextFuelConsumed']==manifest['expectedFuelPerCall']
  vals=[z['elapsedNanoseconds']/(z['calls']*n) for z in zs];mu=statistics.mean(vals);sd=statistics.stdev(vals);old=x['summary'][arm];assert mu==old['meanNsPerBody'] and math.isclose(sd,old['sdNs'],rel_tol=1e-13) and math.isclose(sd/mu,old['relativeSd'],rel_tol=1e-13);summaries[arm]=old
 b=summaries['baseline'];c=summaries['candidate'];ref=summaries['C'];stable=max(z['relativeSd'] for z in summaries.values())<=spec['maximumRelativeSd'];improves=stable and b['meanNsPerBody']/c['meanNsPerBody']>=spec['minimumSpeedup'] and b['meanNsPerBody']-c['meanNsPerBody']>b['sdNs']+c['sdNs'];regresses=stable and c['meanNsPerBody']/b['meanNsPerBody']>=spec['minimumSpeedup'] and c['meanNsPerBody']-b['meanNsPerBody']>b['sdNs']+c['sdNs'];cbetter=stable and ref['meanNsPerBody']/c['meanNsPerBody']>=spec['minimumSpeedup'] and ref['meanNsPerBody']-c['meanNsPerBody']>ref['sdNs']+c['sdNs'];assert stable==x['summary']['stable'] and improves==x['summary']['candidateImprovesBaseline'];assert b['meanNsPerBody']/c['meanNsPerBody']==x['summary']['baselineOverCandidate'];assert c['meanNsPerBody']/ref['meanNsPerBody']==x['summary']['candidateOverC'];total+=30;rows.append({'workload':name,**summaries,'stable':stable,'qualifiedImprovement':improves,'qualifiedRegression':regresses,'qualifiedCOrBetter':cbetter,'timeReductionPercent':100*(1-c['meanNsPerBody']/b['meanNsPerBody']),'candidateOverC':c['meanNsPerBody']/ref['meanNsPerBody'],'attemptedTriples':x['attemptedTriples']})
possible=all(z['stable'] and not z['qualifiedRegression'] for z in rows) and any(z['qualifiedImprovement'] for z in rows);out={'status':'complete-independent-all5-changed-native-product-candidate-C-timing-audit','acceptedTriples':total,'unstable':[z['workload'] for z in rows if not z['stable']],'qualifiedImprovements':[z['workload'] for z in rows if z['qualifiedImprovement']],'qualifiedRegressions':[z['workload'] for z in rows if z['qualifiedRegression']],'qualifiedCOrBetter':[z['workload'] for z in rows if z['qualifiedCOrBetter']],'performanceAllowsFurtherAdoptionGates':possible,'productPromoted':False,'all19GoalAchieved':False,'officialEmbenchScore':False,'rows':rows};(w/'timing-audit.json').write_text(json.dumps(out,indent=2)+'\n');print('PASS independent raw triples/stats/source/native/C/fuel controls', {k:v for k,v in out.items() if k!='rows'},flush=True)
