from pathlib import Path
import json,hashlib,re,stat
W=Path('/Users/junkawasaki/github/workspaces/codex');D=W/'crc-table-decision-collapse-tc-remaining-extract1-source-v2-20261009';O=D/'run-outputs';R=W/'crc-table-decision-collapse-tc-remaining-extract1-v2-actual-review-independent-20261009';G=W/'crc-table-decision-collapse-tc-remaining-extract1-v2-go-root-20261009/root-go.json';H=lambda b:hashlib.sha256(b).hexdigest();L=lambda p:json.loads(Path(p).read_bytes())
def pin(p,v):
 p=Path(p);st=p.lstat();assert stat.S_ISREG(st.st_mode)and not p.is_symlink();b=p.read_bytes();assert len(b)==v['bytes']and H(b)==v['sha256'];return b
def receipt(p):p=Path(p);b=p.read_bytes();return {'path':str(p),'bytes':len(b),'sha256':H(b)}
counts=[]
for n,rel in [('source-pins.json',True),('input-pins.json',False)]:
 reg=L(D/n);total=0
 for p,v in reg.items():pin(D/p if rel else p,v);total+=v['bytes']
 counts.append([len(reg),total])
assert counts==[[10,65394],[2004,392322812]];pr=L(D/'preregistration.json');g=L(G);c=L(O/'completion.json')
assert g['status']=='ROOT_GO_TC_SAVED_OBSERVER_EXTRACT1_ONLY'and g['maximumLoaderCalls']==1 and g['noRetry']is True and g['TCEmitterExecutionAuthorized']is False and g['generatedWorkloadExecutionAuthorized']is False and g['timingAuthorized']is False
for n,h in g['sha256'].items():assert H((D/n).read_bytes())==h
assert len(g['sourceReviews'])==2
for r in g['sourceReviews']:
 v=json.loads(pin(r['path'],r));assert v['status']=='PASS_SOURCE_ONLY_TC_SAVED_OBSERVER_EXTRACT1'and v['sourcePinsSHA256']==g['sha256']['source-pins.json']and v['driverSHA256']==g['sha256']['run.py']
assert c['status']=='COMPLETE_TC_SAVED_OBSERVER_EXTRACT1_IDENTITY_ONLY'and c['sourcePinsSHA256']==g['sha256']['source-pins.json']and c['rootGOSHA256']==H(G.read_bytes())
for name in ['terminal','attempts','generatedPins','native']:pin(c[name]['path'],c[name])
for p,v in L(O/'generated-pins.json').items():pin(p,v)
a=L(O/'attempts.json');assert len(a)==1;r=a[0];assert L(O/'terminal.json')=={'attemptedCalls':1,'allChildrenClosed':True,'failure':False,'noRetry':True}
assert r['index']==1 and r['label']=='saved-observed-input-extract'and r['nativeArgv']==pr['orderedChildren'][0]['nativeArgv']and r['argv'][5:]==r['nativeArgv']and r['argv'][0]==pr['interpreter']['path']and r['argv'][1]==str(D/'launch-wrapper.py');assert r['environment']==pr['environment']==L(O/'effective-environment.json')
assert r['state']=='terminal'and r['spawned']and r['reaped']and r['returncode']==0 and r['waitEntered']and not r['waitUncertain']and r['signalingAuthorityRetired']and r['reason']is None and r['exception']is None and r['cleanup']==[]
label=r['label']
for field,suffix,cap in [('stdout','stdout',8388608),('stderr','stderr',1048576),('limitJournal','limit-journal.jsonl',65536),('memoryJournal','memory-journal.jsonl',16777216)]:pin(O/(label+'.'+suffix),r[field]);assert r[field]['bytes']<=cap
jr=[json.loads(x)for x in (O/(label+'.limit-journal.jsonl')).read_bytes().splitlines()];assert len(jr)==6;keys=sorted(pr['environment']);e=jr[0];assert e=={'stage':'environment-admission','suppliedKeyNames':keys,'runtimeExtraKeyNames':e['runtimeExtraKeyNames'],'missingKeyNames':[],'changedExpectedKeyNames':[],'nativeExecKeyNames':keys,'nativeExecEnvironmentExact':True}and e['runtimeExtraKeyNames']in [[],['__CF_USER_TEXT_ENCODING']]
for i,(name,soft,hard)in enumerate([('RLIMIT_FSIZE',67108864,67108864),('RLIMIT_CPU',1800,1801)]):
 before,after=jr[1+2*i:3+2*i];assert before['index']==i+1 and before['limit']==name and before['desired']==[soft,hard]and before['stage']=='before';assert all(x==9223372036854775807 or x>=y for x,y in zip(before['before'],[soft,hard]));assert after=={'index':i+1,'limit':name,'stage':'outcome','outcome':'installed','readback':[soft,hard]}
assert jr[-1]=={'stage':'exec-ready','argv':r['nativeArgv'],'ASSetterRequested':False,'CPUGraceHardSeconds':1801}
mem=[json.loads(x)for x in (O/(label+'.memory-journal.jsonl')).read_bytes().splitlines()];assert len(mem)==r['memorySamples']==2;seen={};aggregates=[];last=0
for i,m in enumerate(mem,1):
 assert m[0]==i and m[1]>last and m[2]==r['pid']and 1<=len(m[3])<=2;last=m[1];ids=[]
 for pid,birth,foot in m[3]:assert birth>0 and 0<=foot<2**64 and seen.get(pid,birth)==birth;seen[pid]=birth;ids.append(pid)
 assert r['pid']in ids and len(set(ids))==len(ids);aggregates.append(sum(z[2]for z in m[3]));assert aggregates[-1]<=4294967296
assert len(seen)<=2 and max(aggregates)==r['peakObservedAggregateFootprintBytes']
stderr=(O/(label+'.stderr')).read_bytes();fields=['pairs','string-pool-bytes','vectors','vector-items','heap-bytes','conj','conj-tail','conj-region','conj-copy','copied-words','reserved-words','regions','scope-releases','string-regions','string-region-appends','string-copied-bytes','string-reserved-bytes'];pattern=('KEXE_ARENA_USE {'+' '.join(':'+k+' ([0-9]+)'for k in fields)+'}\n').encode();match=re.fullmatch(pattern,stderr);assert match;vals=dict(zip(fields,map(int,match.groups())));assert vals==r['counterObservation']['values']and r['counterObservation']['status']=='valid';assert vals['heap-bytes']==16*vals['pairs']+vals['string-pool-bytes']+16*vals['vectors']+8*vals['vector-items'];assert vals['pairs']<=16777216 and vals['string-pool-bytes']<=268435456 and vals['vectors']<=4194304 and vals['vector-items']<=134217728
blob=pin(pr['savedContainer']['path'],pr['savedContainer']);copy=Path(pr['savedInputCopyPath']);assert copy.read_bytes()==blob and stat.S_IMODE(copy.stat().st_mode)==0o444;end=blob.index(b'\n\n');head=blob[:end].splitlines();assert head[0]==b'KSEED1 3680 4';payload=blob[end+2:];exports=[(z[0].decode(),int(z[1]),int(z[2]))for row in head[1:]for z in [row.split()]];assert exports==[tuple(x)for x in pr['expectedExports']]==[tuple(x)for x in c['exports']];native=pin(c['native']['path'],c['native']);assert native==payload==pin(pr['expectedNative']['path'],pr['expectedNative']);assert native==Path(pr['savedOutputRoot']+'/on-input.kseed').read_bytes().split(b'\n\n',1)[1]
assert (O/(label+'.stdout')).read_bytes()==('{:ok true, :output "'+c['native']['path']+'", :offset 1264, :length 3680, :arity 1}\n').encode();assert c['benchOffset']==1264
for k,n in [('savedContainer','savedContainer'),('savedObserver','extractProducer'),('expectedCandidateNative','expectedNative'),('acceptedEmissionProof','actualEmissionProof')]:assert c[k]==pr[n];pin(pr[n]['path'],pr[n])
old=Path(pr['savedOutputRoot']);assert not(old/'observed-on-input.bin').exists()and not(old/'completion.json').exists()and len(L(old/'attempts.json'))==7 and L(old/'terminal.json')['failure']is True
assert not(O/'failure.json').exists()and c['oldBuild8StillFailed']is True and c['oldCallsRepeated']==0 and c['freshExtractionCalls']==1
for k in ['TCEmitterExecuted','generatedWorkloadExecuted','guestRuntimeQualified','performanceQualified','selfhostFixedPointQualified','OSStackLimitProof','hardMemoryCapEstablished']:assert c[k]is False
q={'status':'PASS_INDEPENDENT_ACTUAL_TC_SAVED_OBSERVER_EXTRACT1_IDENTITY_ONLY','independent':True,'priorImplementationAuthorship':False,'sourcePinsSHA256':g['sha256']['source-pins.json'],'driverSHA256':g['sha256']['run.py'],'inputPinsSHA256':g['sha256']['input-pins.json'],'preregistrationSHA256':g['sha256']['preregistration.json'],'rootGOSHA256':H(G.read_bytes()),'completion':receipt(O/'completion.json'),'sourceReviews':g['sourceReviews'],'freshClosure':counts,'extractedNative':c['native'],'acceptedEmissionProof':c['acceptedEmissionProof'],'savedObserver':c['savedObserver'],'savedContainer':c['savedContainer'],'expectedCandidateNative':c['expectedCandidateNative'],'exports':c['exports'],'benchOffset':1264,'wholeBothContainerPayloadsAndNativeIdentity':True,'freshExtractionCalls':1,'parentReapedReturncode':0,'exactArgvAnd17EnvironmentVerified':True,'namedJournalRecords':6,'arenaCounterFields':17,'memorySamples':2,'memberCounts':[len(m[3])for m in mem],'observedLifetimeMembers':len(seen),'aggregateFootprintBytes':aggregates,'peakObservedAggregateFootprintBytes':max(aggregates),'authorityRetired':True,'waitUncertain':False,'oldCallsRepeated':0,'oldBuild8StillFailed':True,'oldObservedNativeAndCompletionAbsent':True,'operationalCallsByReviewer':0,'rerunsByReviewer':0,'guestRuntimeQualified':False,'performanceQualified':False,'selfhostFixedPointQualified':False,'hardMemoryCapEstablished':False,'limits':['Saved one-call extraction artifact identity only. Original build8 failure remains preserved; this is a separate namespace, not a retroactive eighth receipt.','Normal loader return/counters provide pinned native-child wait protocol; no independent descendant wait receipt or syscall trace.','EOF and no-signal lifecycle follow accepted reviewed driver path and saved reaping/retirement fields; no fresh process query.','Exactly-once outer tool exit0 is root observation. No guest behavior/full19/cache reuse/fixedpoint/performance, OS-stack/arena or hardpeak equivalence.'],'blockers':[]};p=R/'report.json';p.write_text(json.dumps(q,indent=2)+'\n');p.chmod(0o444);print(str(p),p.stat().st_size,H(p.read_bytes()))
