from pathlib import Path
import json,hashlib,tarfile,subprocess,shutil
r=Path('/Users/junkawasaki/github/wt/amu-seed17');w=Path('/private/tmp/amu-affine-reader-20261005');i=Path('/private/tmp/amu-affine-reader-integrated-20261005');p=Path('/private/tmp/amu-affine-reader-integrated-20261005-parity');d=r/'docs/evidence/coscientist-affine-reader-20261006';d.mkdir(parents=True,exist_ok=True);load=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();t=load(w/'timing-audit-wikisort.json');integ=load(w/'integrated-summary.json');assert t['qualifies'] and integ['status']=='complete-3-generations-19-ports-and-per-case-corpus-parity';assert (r/'seed/41-a64gen.kotoba').read_bytes()==(w/'41-a64gen-prototype.kotoba').read_bytes();assert '4196/4196 runs pass' in (w/'permanent-unit-final.log').read_text();assert (w/'bootstrap-before.log').read_bytes()==(w/'bootstrap-after.log').read_bytes();state=load(w/'reader-state-proof.json');imports=load(w/'reader-import-proof.json');invalid=load(w/'invalid-handles-proof.json')
s={'status':'qualified-native-closed-affine-index-reader-composition','sourceCommit':'271a8bdc1','permanentFixtureMetadataCommit':'c5526f060','baselineSourceCommit':'a27dc9074','experimentStarted':'2026-10-05','qualificationCompleted':'2026-10-06','decision':'Promote generic closed exact frameless vector reader composition; only WikiSort machine bytes change. Fresh30 quiet rotating triples pass unchanged1.05+summedSD rule. Full native semantic proofs, gates and integrated3gen/per-case corpus parity pass.','hypothesis':load(w/'hypothesis.json'),'generations':load(w/'generations.json'),'nativeAdmission':load(w/'meta-admission.json'),'codeChanges':load(w/'code-change.json'),'nativeHandProof':{k:v for k,v in state.items() if k!='runs'},'independentStateAudit':load(w/'state-audit.json'),'allocatingImportProof':{k:v for k,v in imports.items() if k!='runs'},'invalidHandleExtremes':{k:v for k,v in invalid.items() if k!='runs'},'baseFixtureComposition':load(w/'base-layout-proof.json'),'newFixtureLayout':load(w/'reader-layout-proof.json'),'observerByteProof':load(w/'observer-byte-audit.json'),'replayInputProof':load(w/'replay-input-proof.json'),'permanentRegression':{'fixtures':342,'runs':4196,'original319FixtureAndRunPrefixPreserved':True,'finalCallerMetadataScalar':True,'finalRunWithoutGoldenUpdatePassed':True,'generator':'scripts/seed/a64gen-fixtures.py'},'timing':t,'timingPins':load(w/'timing-artifact-audit.json'),'gates':load(w/'gate-summary.json'),'integration':integ,'repairs':[load(w/'repair-note.json'),'Initial fixture authoring placed cases before later original fixtures; moved allnew cases after the complete original319 prefix. Initial broader synthetic argument metadata was then restricted to vector-reader leaves; final4196 pass without updating machine golden. Earlier runs are retained, not added to final counts.','Proof replay inputs were frozen after product fixture additions, reproducing exact executed587fixture IDs and244caller configurations. Repository-root resolution is the only adaptation. Prior qualified golden pin checked.'],'bootstrapProductInventoryUnchanged':True,'productChanged':True,'launcherSwitched':False,'rungRecordChanged':False,'wire20Granted':False,'officialEmbenchScore':False,'COrBetter':False};(d/'summary.json').write_text(json.dumps(s,indent=2)+'\n');(d/'archive.py').write_bytes(Path(__file__).read_bytes());(d/'timing-audit.json').write_bytes((w/'timing-audit-wikisort.json').read_bytes());q=subprocess.run(['git','diff','--no-index',str(w/'baseline-41-a64gen.kotoba'),str(w/'41-a64gen-prototype.kotoba')],capture_output=True,text=True);assert q.returncode==1;(d/'prototype.diff').write_text(q.stdout)
with tarfile.open(d/'native-proof.tgz','w:gz') as a:
 for x in sorted(w.iterdir()):
  if x.name in ['__pycache__','gate-build','permanent-unit','permanent-unit-final','timing-package','timing-upload.tgz']:continue
  a.add(x,arcname=x.name)
 for n in ['seed/MANIFEST','seed/SIR','seed/HEADS','seed/MEMORY-MAP','AGENTS.md','scripts/seed/a64gen-fixtures.py','seed/tests/unit/41-a64gen.expected','seed/tests/unit/41-a64gen.fixtures.json','seed/tests/unit/41-a64gen_t.kotoba']:a.add(r/n,arcname='committed-source/'+n)
 for n in ['clobber-state-loader.c','clobber-state-loader']:a.add(Path('/private/tmp/amu-context-call-20261005')/n,arcname='diagnostic/'+n)
with tarfile.open(d/'timing.tgz','w:gz') as a:
 for n in ['remote-timing.py','timing-package','audit-workload.py','timing-audit-wikisort.json','timing-artifact-audit.py','timing-artifact-audit.json','timing.log']:a.add(w/n,arcname=n)
with tarfile.open(d/'integrated-proof.tgz','w:gz') as a:
 for n in ['gate-summary.json','gates.log','gate-build/gates/r6m','integrated-ports.py','integrated-proof.py','integrated-summary.json','integrated-parity.log','integrated-ports.log','integrated-build.log']:a.add(w/n,arcname=n)
 for n in ['check.tsv','compile.tsv','exports.tsv']:a.add(p/n,arcname='parity/'+n)
 for n in ['inputs.sha256','input-check.log','objects1.sha','objects2.sha','objects3.sha','ports.json','front1.out','front2.out','front3.out','g1.out','g2.out','g3.out','g3/amu','g3/amu.bin','g3/amu.kseed']:a.add(i/n,arcname='integrated/'+n)
next={'status':'registered-not-implemented-or-measured','hypothesis':'Reuse a previously validated vector descriptor in a bounded region only when dominance and exact same handle are proved, with mutation/effect/call invalidation. Keep each original index check and fuel/trap publication unless a separate sound range proof applies. No result memoization.','evidence':'Original WikiSort native census has59084 value entries and93139 ordinary vector-at lowerings per body; removing calls qualifies8.29% but candidate remains11.72x C. Repeated handle/descriptor checks remain real generated cost, counts are not time shares.','invalidation':'The actual runtime checked_vector_conj can mutate descriptor length on in-place append. Content identity does not make runtime state immutable. Unknown calls/capabilities/imports/mutation or changed handles must invalidate; no descriptor immutability assumption.','qualification':'All19 original canonical sources unchanged; native signed/invalid handle/index/fuel/partial-write/mutation/alias/open imports, fixedpoint; freshquiet30rotatingtriples for everychangedguest same1.05+sumSD rule; fullgates/integrated3gen/corpus beforepromotion.','scope':'C-level-or-better on all19 original aligned workloads, not just WikiSort; no100percent completion or official score claim.'};(d/'next-hypothesis.json').write_text(json.dumps(next,indent=2)+'\n');(d/'checksums.sha256').write_text(''.join(sha(x)+'  '+x.name+'\n' for x in sorted(d.iterdir()) if x.is_file() and x.name!='checksums.sha256'));print('PASS qualified native reader proof, raw fresh timing and integrated lineage archived')
