#!/bin/zsh
# seed/tests/r5b/gate-r5b.sh [--extra] -- the extra gate of rung R5 part B (effects; owner R5B). BOOTSTRAP-TOOL (zsh).
# gates.sh --rung r5b runs it as its XTRA row (--extra); BUILD ERR G1 G2 G3 G4 G5 GR (r1 r3 r4 r4b and the full R5 test format:
# all 77 cases of seed/tests/r5 incl. the 38 part-B ones, 16/16 neg texts) are gates.sh's own rows. Rows here:
#   EXT    seed/tests/r5b/run-r5b.sh with seed-1: the extra R5B cases of expect.tsv (specializations, string state, cells, ceilings,
#          the --policy file shapes, the R5B refusals)
#   R5A-X  seed/tests/r5a/gate-r5a.sh --extra: the namespace-split rung proof of R5A (SPLIT fixed point, SPLIT-G1/G2/G4, SEP) kept
#          passing with the R5B sources (seed/split regenerated by seed/split/gen-split.py)
# Exit 0 iff every row passes.
emulate -L zsh
setopt pipefail
source "$(dirname "$0")/../../../scripts/seed/lib.sh"
R=$SEED_REPO; B=${SEED_BUILD:A}; D=$R/seed/tests/r5b
fails=0
row() { printf "%-5s %s\n" $1 "$2"; [ $1 = FAIL ] && fails=$((fails+1)); return 0; }
SEED_BUILD=$B zsh $D/run-r5b.sh $B/seed-1.bin > $B/gate-r5b-ext.log 2>&1 && row PASS "EXT $(tail -1 $B/gate-r5b-ext.log)" \
  || row FAIL "EXT $(grep -E '^FAIL|run-r5b' $B/gate-r5b-ext.log | head -4 | tr '\n' ' ')"
SEED_BUILD=$B zsh $R/seed/tests/r5a/gate-r5a.sh --extra > $B/gate-r5b-r5a.log 2>&1 && row PASS "R5A-X $(tail -1 $B/gate-r5b-r5a.log)" \
  || row FAIL "R5A-X $(grep -E '^FAIL' $B/gate-r5b-r5a.log | head -3 | tr '\n' ' ')"
echo "gate-r5b: $([ $fails -eq 0 ] && echo READY || echo "NOT READY ($fails failed)") (load $(uptime | sed 's/.*averages: //'))"
[ $fails -eq 0 ]
