"""Prospective V2 static authoring only; never imports or calls operational V1/V2 driver."""
from pathlib import Path
import json,hashlib,stat,ast,sys
D=Path(__file__).resolve().parent;W=D.parent;V=W/'vector-fuel-scalar-dag-original19-functional285-plan-v1';G=W/'vector-fuel-scalar-dag-original19-functional285-go-v1-root'
J=lambda p:json.loads(Path(p).read_bytes());H=lambda b:hashlib.sha256(b).hexdigest()
def pin(p):
 p=Path(p);st=p.lstat();assert stat.S_ISREG(st.st_mode)and not p.is_symlink();h=hashlib.sha256()
 with p.open('rb')as f:
  for b in iter(lambda:f.read(1048576),b''):h.update(b)
 return {'path':str(p),'bytes':st.st_size,'sha256':h.hexdigest()}
def save(n,v):(D/n).write_text(json.dumps(v,indent=2)+'\n')
assert len(sys.argv)==2,'saved independent FAIL1 review path required';review=pin(sys.argv[1]);q=J(review['path']);assert q['status']=='CLOSED_FAIL1_FUEL_DAG_ORIGINAL19_FUNCTIONAL285_SANDBOX_INIT_ONLY'
assert not(D/'run.py').exists()and not(D/'preregistration.json').exists(),'fresh V2 namespace registration'
cl=J(V/'input-closure.json')
def add(v):
 row={k:v[k]for k in ['bytes','sha256']};assert v['path']not in cl or cl[v['path']]==row;cl[v['path']]=row
for folder in [V,G,W/'vector-fuel-scalar-dag-original19-functional285-source-review-v1-root',W/'vector-fuel-scalar-dag-original19-functional285-source-review-v1-fuel44-review',Path(review['path']).parent]:
 for p in folder.rglob('*'):
  if p.is_file():add(pin(p))
if 'auditInputPinsSHA256'in q:
 rp=Path(review['path']).parent/'input-pins.json';assert pin(rp)['sha256']==q['auditInputPinsSHA256']
 for path,v in J(rp).items():add({'path':path,**v})
pr=J(V/'preregistration.json');prior={'independentReview':review,'independentReviewInputPins':pin(Path(review['path']).parent/'input-pins.json'),'sourcePins':pin(V/'source-pins.json'),'driver':pin(V/'run.py'),'preregistration':pin(V/'preregistration.json'),'inputClosure':pin(V/'input-closure.json'),'GO':pin(G/'root-go.json'),'attempts':pin(V/'run-outputs/attempts.json'),'stdout':pin(V/'run-outputs/aha-mont64-OFF-n0.stdout'),'stderr':pin(V/'run-outputs/aha-mont64-OFF-n0.stderr'),'failure':pin(V/'run-outputs/failure.json'),'report':pin(V/'run-outputs/report.json'),'terminal':pin(V/'run-outputs/terminal.json')}
for z in prior.values():add(z)
pr.update(status='PROSPECTIVE_SOURCE_ONLY_FUEL_DAG_ORIGINAL19_FUNCTIONAL285_V2_REGISTERED_BEFORE_DRIVER_AUTHORING',sourceReviewStatus='PASS_SOURCE_ONLY_FUEL_DAG_ORIGINAL19_FUNCTIONAL285_V2_LAUNCHER',rootGOStatus='ROOT_AUTHORIZED_FUEL_DAG_ORIGINAL19_FUNCTIONAL285_V2_LAUNCHER_ONLY',outputRoot=str(D/'run-outputs'),priorFailedNamespace=prior,priorFailedAttempts=1,maximumCumulativeAttempts=286,launcherConstraint={'tool':'functions.exec_command','sandbox_permissions':'require_escalated','rootNativeLauncherAuthorizationRequired':True,'scope':'Outer macOS launcher must allow the already source-bound kexe-loader sandbox_init. Loader sandbox and fixed child environments remain unchanged. Driver can validate root attestation but cannot introspect actual tool permission.'},noRetryScope='Per namespace. V1 CLOSED_FAIL1 preserved, no rerun there. V2 is separately reviewed prospectively authorized full19 fresh285; no failed baseline return retained. Maximum cumulative attempts=1+285=286.',v1FailureScope='First OFF aha-mont64 n0 exited125 at sandbox_init Operation not permitted. Initial=remaining16777216 and all terminal arenasused0; no successful native result, complete triples0; independently reviewed saved raw only.')
save('input-closure.json',dict(sorted(cl.items())));save('preregistration.json',pr)
s=(V/'run.py').read_text();s=s.replace("'specific finite285 root GO')","'specific finite285 root GO')\n need(g['launcherTool']=='functions.exec_command'and g['launcherSandboxPermissions']=='require_escalated'and g['nativeLauncherAuthorized']is True and g['priorFailedAttempts']==1 and g['maximumCumulativeAttempts']==286,'root outer-launcher authorization and cumulative286 boundary')")
s=s.replace(" guard()\n for v in g['sourceReviews']:"," guard()\n prior=pr['priorFailedNamespace'];v1=load(prior['report']['path']);terminal=load(prior['terminal']['path']);rows=load(prior['attempts']['path']);failed=load(prior['failure']['path']);v1review=load(prior['independentReview']['path'])\n need(v1review['status']=='CLOSED_FAIL1_FUEL_DAG_ORIGINAL19_FUNCTIONAL285_SANDBOX_INIT_ONLY'and v1['status']=='FAIL_FINITE_FUEL_DAG_ORIGINAL19_FUNCTIONAL285_FIRST_FAILURE'and v1['calls']==1 and v1['completedTriples']==0 and v1['comparisons']==[] and terminal=={'calls':1,'allCallsClosed':True,'failure':True,'noRetry':True}and failed['calls']==1 and failed['completedTriples']==0 and failed['policy']=='STOP_FIRST_FAILURE_NO_RETRY','preserved V1 CLOSED_FAIL1 only')\n need(v1review['independent']is True and v1review['rootGO']==prior['GO']and v1review['auditInputPinsSHA256']==prior['independentReviewInputPins']['sha256']and v1review['sourcePinsSHA256']==prior['sourcePins']['sha256']and v1review['driverSHA256']==prior['driver']['sha256']and v1review['preregistrationSHA256']==prior['preregistration']['sha256']and v1review['inputClosureSHA256']==prior['inputClosure']['sha256']and v1review['rawStdout']==prior['stdout']and v1review['rawStderr']==prior['stderr']and v1review['bodyResultEvidence']is False and v1review['candidateONCalls']==v1review['CCalls']==v1review['completedTriples']==0,'saved independent FAIL1 exact source GO raw closure correspondence')\n for path,v in load(prior['independentReviewInputPins']['path']).items():need(cl[path]==v,'full prior FAIL1 review closure retained')\n need(len(rows)==1 and rows[0]['state']=='terminal'and rows[0]['returncode']==125 and rows[0]['label']=='aha-mont64-OFF-n0'and rows[0]['stdoutSHA256']==prior['stdout']['sha256']and rows[0]['stderrSHA256']==prior['stderr']['sha256'],'exact prior failed raw ledger')\n need(pin(prior['stderr']).read_bytes()==b'sandbox initialization failed: Operation not permitted\\nkexe-loader: sandbox_init: Operation not permitted\\n'and pin(prior['stdout']).read_bytes()==b'{:status :trap :exit 125 :fuel {:initial 16777216 :remaining 16777216} :heap {:capacity 2097152 :used 0} :string-pool {:capacity 65536 :used 0} :vectors {:capacity 4096 :used 0} :vector-items {:capacity 65536 :used 0}}\\n','prior sandbox initialization failure exact, never accepted as guest result')\n for v in g['sourceReviews']:")
s=s.replace('PASS_FINITE_FUEL_DAG_ORIGINAL19_FUNCTIONAL285_ONLY','PASS_FINITE_FUEL_DAG_ORIGINAL19_FUNCTIONAL285_V2_ONLY').replace('FAIL_FINITE_FUEL_DAG_ORIGINAL19_FUNCTIONAL285_FIRST_FAILURE\'if ok','FAIL_FINITE_FUEL_DAG_ORIGINAL19_FUNCTIONAL285_V2_FIRST_FAILURE\'if ok')
# Replace only the future terminal FAIL status, never the retained V1 guard.
s=s.replace("else'FAIL_FINITE_FUEL_DAG_ORIGINAL19_FUNCTIONAL285_FIRST_FAILURE'","else'FAIL_FINITE_FUEL_DAG_ORIGINAL19_FUNCTIONAL285_V2_FIRST_FAILURE'")
s=s.replace("'freshOriginal19Calls':len(led.rows)","'freshOriginal19Calls':len(led.rows),'priorFailedAttempts':1,'cumulativeAttempts':1+len(led.rows),'maximumCumulativeAttempts':286")
ast.parse(s);(D/'run.py').write_text(s)
(D/'pure-controls.py').write_text((V/'pure-controls.py').read_text().replace('PASS_PURE_STATIC_SOURCE_CONTROLS_FUEL_DAG_ORIGINAL19_FUNCTIONAL285','PASS_PURE_STATIC_SOURCE_CONTROLS_FUEL_DAG_ORIGINAL19_FUNCTIONAL285_V2'))
print('Preregistration written before driver. Static authoring only, inherited',len(cl),'files',sum(v['bytes']for v in cl.values()),'bytes.')
