from pathlib import Path
import tarfile,json,hashlib,subprocess
r=Path('/Users/junkawasaki/github/wt/amu-seed17');w=Path('/private/tmp/amu-static-arg-20261005');d=r/'docs/evidence/coscientist-static-arg-20261005';d.mkdir(parents=True,exist_ok=True);sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda n:json.loads((w/n).read_text());t=load('timing-audit.json');assert not t['allQualify'] and all(not x['qualifies'] for x in t['entries']);assert (w/'baseline-41-a64gen.kotoba').read_bytes()==(r/'seed/41-a64gen.kotoba').read_bytes()
s={'status':'complete-rejected-native-static-argument-specialization','sourceHeadBefore':'4f92e52f28ae424d62f13a62ff6a8bf5a52033a9','decision':'All five changed workloads fail the prospective1.05 speedup criterion and meanGap>summedSD rule; no product promotion or same-byte timing retry.','productChanged':False,'fullReleaseGateClaim':False,'officialEmbenchScore':False,'COrBetter':False,'hypothesis':load('hypothesis.json'),'generations':load('generations.json'),'admission':load('descriptor-admission.json'),'observerByteAudit':load('observer-byte-audit.json'),'frameByteAudit':load('frame-byte-audit.json'),'frameAudit':load('frame-audit.json'),'nativeOracles':load('expanded-proof.json'),'importProof':{k:v for k,v in load('import-proof.json').items() if k!='cases'},'workspace':load('bulk-state.json'),'codeChanges':load('code-change.json'),'timing':t,'remainingQualification':['Clone and optional-code/frame capacity fallback probes not completed','Full expanded fixture supervisor/partial-state proof not completed','No committed-source ERR/G1-G5, integrated rebuilding or corpus qualification for this rejected candidate'],'repairs':['Initial prototype reused private clones across regeneration; repaired owned-G metadata and restored original CALL/FN/SIR/LABEL before installing new imports. Native closed->open emission equals fresh-open, with180 actual allocating-import comparisons.','First expanded diagnostic had a missing output-expression parenthesis; compiler artifact unaffected; failure log retained.','Canonical output directories existed from initial prototype; harness corrected to reuse directories before fresh current runs.','Fixture test layout adds2 zero padding bytes; common code/literals/function table independently match real layout. Complete blob byte equality is not claimed.'],'ownershipBoundary':'Header101 is private prototype-owned extended G metadata; normal project reset zeroes0..255 and used heap. Arbitrary appending of source after native generation is not qualified.'}
(d/'summary.json').write_text(json.dumps(s,indent=2)+'\n');q=subprocess.run(['git','diff','--no-index',str(w/'baseline-41-a64gen.kotoba'),str(w/'41-a64gen-prototype.kotoba')],capture_output=True,text=True);assert q.returncode==1;(d/'prototype.diff').write_text(q.stdout)
for n in ['archive.py','audit-workload.py','timing-audit.json']:(d/n).write_bytes((w/n).read_bytes())
with tarfile.open(d/'native-proof.tgz','w:gz') as a:
 for p in sorted(w.iterdir()):
  if p.name in ['timing-package','__pycache__','archive.py'] or p.name.startswith('timing-audit-'):continue
  a.add(p,arcname=p.name)
 for x in [x.strip() for x in (r/'seed/MANIFEST').read_text().splitlines() if x.strip() and not x.lstrip().startswith('#')]:a.add(r/x,arcname='baseline-source/'+x)
 for x in ['seed/SIR','seed/HEADS','seed/MEMORY-MAP','seed/MANIFEST','AGENTS.md','bench/embench/comparison-matrix.json','bench/embench/paired-timing-spec.json']:a.add(r/x,arcname='baseline-source/'+x)
 for x in ['clobber-state-loader.c','clobber-state-loader']:a.add(Path('/private/tmp/amu-context-call-20261005')/x,arcname='diagnostic/'+x)
with tarfile.open(d/'timing.tgz','w:gz') as a:
 for n in ['remote-all.py','timing-package','audit-workload.py','timing-audit.json']:a.add(w/n,arcname=n)
 a.add(Path('/private/tmp/amu-context-call-20261005/measure-native-candidate-v2.py'),arcname='measure-native-candidate-v2.py')
next={'status':'registered-not-implemented-or-measured','hypothesis':'Before another static specialization, obtain native dynamic cost census of scalar mode tests, direct helper calls, checked vector operations and repeated runtime dispatch on every original workload. Select the measured hottest removable cost and propose a generic bounded transformation with exact fuel/trap/allocation/partial-write/import proofs. Separately evaluate content-addressed cold/warm compilation; no result-cache hit may count as fresh Embench execution.','reason':'Static bits are native-admissible and branch folding occurs, but five workloads produce only noise-level changes while code grows. Source occurrence/admission is not dynamic cost evidence.','promotion':'Unchanged original workloads;30 fresh rotating triples per changed guest; ratio>=1.05, meanGap>summedSD, quiet host and native fixedpoint/full gates/integrated/corpus.'};(d/'next-hypothesis.json').write_text(json.dumps(next,indent=2)+'\n')
(d/'checksums.sha256').write_text(''.join(sha(x)+'  '+x.name+'\n' for x in sorted(d.iterdir()) if x.is_file() and x.name!='checksums.sha256'));print('PASS rejected experiment archived; native product source unchanged')
