from pathlib import Path
import json,hashlib,tarfile,subprocess
r=Path('/Users/junkawasaki/github/wt/amu-seed17');w=Path('/private/tmp/amu-loop-high-temp-20261006');i=Path('/private/tmp/amu-loop-high-temp-integrated-20261006');p=Path('/private/tmp/amu-loop-high-temp-integrated-20261006-parity');q=Path('/private/tmp/amu-high-temp-no-spill-20261006');d=r/'docs/evidence/coscientist-loop-high-temp-20261006';d.mkdir(parents=True,exist_ok=True);load=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();integ=load(w/'integrated-summary.json');tim=load(w/'timing-lineage.json');assert tim['qualifies'] and integ['status']=='complete-3-generations-19-ports-and-per-case-corpus-parity';assert (r/'seed/41-a64gen.kotoba').read_bytes()==(w/'41-a64gen-prototype.kotoba').read_bytes();assert (w/'bootstrap-before.log').read_bytes()==(w/'bootstrap-after-final.log').read_bytes();gates=[]
for line in (w/'gate-build/gates/r6m/summary.tsv').read_text().splitlines():
 name,status,seconds,detail=line.split('\t',3);gates.append({'gate':name,'status':status,'seconds':float(seconds),'detail':detail})
assert len([x for x in gates if x['status']=='PASS'])==6 and not any(x['status']=='FAIL' for x in gates);assert all(next(x for x in gates if x['gate']==n)['status']=='PASS' for n in ['ERR','G1','G2','G3','G4','G5']);(w/'gate-summary.json').write_text(json.dumps(gates,indent=2)+'\n')
s={'status':'qualified-native-loop-contained-high-temp-vector-read-without-call-spills','sourceCommit':integ['sourceCommit'],'baselineSourceCommit':load(w/'hypothesis.json')['sourceCommit'],'decision':'Promote general bounded same-function loop-contained reads. Matmult exactly matches already-qualified pinned30-triple machine with15.32percent shorter fresh time; other18 originals equal previous product bytes. No identical-machine retiming. Full native proofs/permanent7989/gates/committed-source integrated3gen/per-case actual-output parity pass.','hypothesis':load(w/'hypothesis.json'),'generations':load(w/'generations.json'),'nativeAdmission':load(w/'meta-admission.json'),'codeChanges':load(w/'code-change.json'),'promotionPreflight':load(w/'promotion-preflight.json'),'nativeInstructionAudit':load(w/'instruction-audit.json'),'observerByteProof':load(w/'observer-byte-audit.json'),'permanent':load(w/'permanent-summary.json'),'timingLineage':tim,'gates':gates,'gateCompilerLineage':load(w/'gate-build-lineage.json'),'integration':integ,'fullCheckAndActualExportOutputAudit':{k:v for k,v in load(w/'per-case-output-audit.json').items() if k!='rows'},'authoringCorrections':load(w/'authoring-corrections.json'),'additionalAuthoringCorrections':'Baseline permanent-table audit used frozen original repository root after temp-copy path resolution failed. Baseline bytes and expected results unchanged. New task Python cache removed before final bootstrap audit; final inventory byte-identical.','bootstrapProductInventoryUnchanged':True,'productChanged':True,'launcherSwitched':False,'rungRecordChanged':False,'wire20Granted':False,'officialEmbenchScore':False,'COrBetter':False}
for name,key in [('hand-proof.json','loopHandStateProof'),('ownership-proof.json','rawNonleafAliasJoinOwnershipProof'),('import-proof.json','actualOpenImportProof'),('resource-proof.json','resourcePartialWrites'),('ports-state.json','original19StateProof'),('regression-proof.json','freshOriginalRegression')]:v=load(w/name);s[key]={k:x for k,x in v.items() if k not in ['runs','observations']}
(d/'summary.json').write_text(json.dumps(s,indent=2)+'\n');(d/'archive.py').write_bytes(Path(__file__).read_bytes());(d/'timing-lineage.json').write_bytes((w/'timing-lineage.json').read_bytes());z=subprocess.run(['git','diff','--no-index',str(w/'baseline-41-a64gen.kotoba'),str(w/'41-a64gen-prototype.kotoba')],capture_output=True,text=True);assert z.returncode==1;(d/'prototype.diff').write_text(z.stdout)
with tarfile.open(d/'native-proof.tgz','w:gz') as a:
 for x in sorted(w.iterdir()):
  if x.name in ['__pycache__','gate-build','permanent-unit','permanent-unit-final','regression-run','permanent-regression-run']:continue
  a.add(x,arcname=x.name)
 for n in ['seed/MANIFEST','seed/SIR','seed/HEADS','seed/MEMORY-MAP','AGENTS.md','scripts/seed/a64gen-fixtures.py','seed/tests/unit/41-a64gen.expected','seed/tests/unit/41-a64gen.fixtures.json','seed/tests/unit/41-a64gen_t.kotoba']:a.add(r/n,arcname='committed-source/'+n)
 for n in ['clobber-state-loader.c','clobber-state-loader']:a.add(Path('/private/tmp/amu-context-call-20261005')/n,arcname='diagnostic/'+n)
with tarfile.open(d/'timing-lineage-proof.tgz','w:gz') as a:
 for n in ['timing-audit-matmult-int.json','timing-artifact-audit-matmult-int.json','timing-package/matmult-int','timing-package/preflight.json','timing-package/product-proof.json','timing-package/candidate-proof.json','timing-package/paired-timing-spec.json','timing-package/comparison-matrix.json','timing-package/measure-native-candidate-v2.py','generations.json','hypothesis.json','audit-workload.py','timing-artifact-audit.py']:a.add(q/n,arcname='timed-predecessor/'+n)
 for n in ['timing-lineage.py','timing-lineage.json','ports-correctness.json','code-change.json','generations.json']:a.add(w/n,arcname='loop-candidate/'+n)
with tarfile.open(d/'integrated-proof.tgz','w:gz') as a:
 for n in ['gate-summary.json','gates.log','gate-build/gates/r6m','integrated-ports.py','integrated-proof.py','integrated-summary.json','per-case-output-audit.py','per-case-output-audit.json','integrated-parity.log','integrated-ports.log','integrated-build.log']:a.add(w/n,arcname=n)
 for n in ['check.tsv','compile.tsv','exports.tsv']:a.add(p/n,arcname='parity/'+n)
 for x in sorted((p/'run').rglob('*')):
  if x.is_file() and x.suffix in ['.out','.err','.st','.raw']:a.add(x,arcname='parity/'+str(x.relative_to(p)))
 for n in ['inputs','inputs.sha256','input-check.log','objects1.sha','objects2.sha','objects3.sha','ports.json','front1.out','front2.out','front3.out','g1.out','g2.out','g3.out','g3/amu','g3/amu.bin','g3/amu.kseed','g3/tree']:a.add(i/n,arcname='integrated/'+n)
next={'status':'registered-not-implemented-or-measured','hypothesis':'Use callee registers left unused by current local allocation for temps7+ in deep expressions. Keep original frame size and local registers. Save/restore added callee registers in those mapped temps original home slots, which then stop storing expression values. Bounds/alias/call/fuel/resource/effect behavior remains original.','actualNativeCensus':load(q/'high-temp-register-census.json'),'evidence':'Actual native census finds high temps and unused callee slots in huffbench/matmult/md5/SHA/slre/UD. Counts are not time shares. New loop optimization keeps original allocation, so census allocation remains applicable; independently observe new admission before measuring.','proofRequirements':'Disjoint registers/backups/locals/low homes/outgoing area; prologue/epilogue/tailcall/RET2 preservation; deep aliases/joins/calls/indirect/allocatingimports/resources/fuel/fullstate. Refuse unknown invariants; nativefixedpoint/all19 originalsource/result/fuel/bytes; fresh30rotatingtriples everychangedguest1.05+sumSD, thenpermanentgates/integrated3gen/corpus.','identity':'No connected native DefCID/result cache. Future artifact proof keys require definition/dependency identity, semantics/compiler/optimization/target/runtime ABI; input/state/effect/resource identity additionally needed for execution-result reuse.','scope':'C-or-better remains all19 original aligned workloads; no result-cache benchmarks or official score claim.'};(d/'next-hypothesis.json').write_text(json.dumps(next,indent=2)+'\n');(d/'checksums.sha256').write_text(''.join(sha(x)+'  '+x.name+'\n' for x in sorted(d.iterdir()) if x.is_file() and x.name!='checksums.sha256'));print('PASS qualified loop-contained native optimization, exact timing lineage and committed-source full integration archived')
