from pathlib import Path
import json,hashlib,tarfile,subprocess
r=Path('/Users/junkawasaki/github/wt/amu-seed17');w=Path('/private/tmp/amu-high-temp-no-spill-20261006');d=r/'docs/evidence/coscientist-high-temp-no-spill-20261006';d.mkdir(parents=True,exist_ok=True);load=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();t=load(w/'timing-summary.json');assert not t['fullCandidateQualifies'];assert (r/'seed/41-a64gen.kotoba').read_bytes()==(w/'baseline-41-a64gen.kotoba').read_bytes()
s={'status':'rejected-unrestricted-native-high-temp-vector-read-without-call-spills','baselineSourceCommit':load(w/'hypothesis.json')['sourceCommit'],'decision':'Both changed original guests freshly measured with30 accepted rotating triples each. Matmult qualifies but SHA256 does not qualify unchanged1.05+gap>sumSD rule. Reject unrestricted prototype; no product change or identical-code retiming.','hypothesis':load(w/'hypothesis.json'),'generations':load(w/'generations.json'),'nativeAdmission':load(w/'meta-admission.json'),'instructionAudit':load(w/'instruction-audit.json'),'codeChanges':load(w/'code-change.json'),'nativePreflightSealedBeforeTiming':load(w/'preflight-audit.json'),'timing':t,'productChanged':False,'officialEmbenchScore':False,'COrBetter':False,'productGatesAndIntegration':'Not rerun after performance rejection. Previous qualified affine-reader product remains current.','authoringCorrections':'Independent instruction audit fixed a transcription typo in a comparison word and used actual blob length for the final function end. Compiler and test expectations unchanged. Exact instruction audit completed after timing.','contextNote':'Actual gn-ctx loads context and marks gn-f-ctx=1. Inline sequence preserves x7; no assumption that gn-ctx leaves metadata unknown.'}
for name,key in [('hand-proof.json','highTempHandProof'),('ownership-proof.json','registerOwnershipProof'),('import-proof.json','actualOpenImportProof'),('resource-proof.json','resourcePartialWrites'),('regression-proof.json','freshOriginalRegression'),('ports-state.json','original19StateProof')]:
 v=load(w/name);s[key]={k:x for k,x in v.items() if k not in ['runs','observations']}
s['newFixtureLayout']=load(w/'hand-layout.json');s['authoringCorrections']=load(w/'authoring-corrections.json');s['loopContainmentCensus']=load(w/'loop-containment-census.json');s['unusedHighTempRegisterCensus']=load(w/'high-temp-register-census.json');(d/'summary.json').write_text(json.dumps(s,indent=2)+'\n');(d/'archive.py').write_bytes(Path(__file__).read_bytes());(d/'timing-summary.json').write_bytes((w/'timing-summary.json').read_bytes());q=subprocess.run(['git','diff','--no-index',str(w/'baseline-41-a64gen.kotoba'),str(w/'41-a64gen-prototype.kotoba')],capture_output=True,text=True);assert q.returncode==1;(d/'prototype.diff').write_text(q.stdout)
with tarfile.open(d/'native-proof.tgz','w:gz') as a:
 for x in sorted(w.iterdir()):
  if x.name in ['__pycache__','timing-package','regression-run','batch-status.json','remote-timing.log']:continue
  if x.name.startswith('timing-artifact-audit-') or x.name.startswith('timing-audit-'):continue
  a.add(x,arcname=x.name)
 for n in ['seed/MANIFEST','seed/SIR','seed/HEADS','seed/MEMORY-MAP','AGENTS.md','seed/41-a64gen.kotoba','tools/kexe_loader.c','scripts/seed/a64gen-fixtures.py','seed/tests/unit/41-a64gen.expected']:a.add(r/n,arcname='baseline-source/'+n)
 for n in ['clobber-state-loader.c','clobber-state-loader']:a.add(Path('/private/tmp/amu-context-call-20261005')/n,arcname='diagnostic/'+n)
with tarfile.open(d/'timing.tgz','w:gz') as a:
 for n in ['remote-timing.py','timing-package','audit-workload.py','timing-artifact-audit.py','timing-summary.json','batch-status.json','remote-timing.log','remote-timing-initial.log']:a.add(w/n,arcname=n)
 for x in sorted(w.iterdir()):
  if x.name.startswith('timing-audit-') or x.name.startswith('timing-artifact-audit-'):a.add(x,arcname=x.name)
next={'status':'registered-not-implemented-or-measured','hypothesis':'Restrict no-spill inline high-temp reads to exact access contained in a backward branch region in the same function. Use bounded scans and validated label ownership. Exclude setup reads outside loops. Keep ordered checks, original nonleaf frame, alias protection and fuel. No workload names.','actualCensus':load(w/'loop-containment-census.json'),'timingLineage':'If restricted matmult emitted bytes exactly equal the already qualified no-spill machine, reuse its pinned30-triple qualified receipt with explicit lineage; do not retime identical bytes. All18 other guests must equal current product bytes.','proofRequirements':'Fresh nativefixedpoint; all19originalsource/result/fuel/guest byte identity; native loop containment and refusals, live register/home prefixes, coalesced aliases, skippedaccesses/joins, effects/import/resource/fuel/traps; permanentauthoritativefixtures/gates/committed-input integrated3gen/percase corpus beforepromotion.','scope':'C-or-better remains all19originalaligned workloads; no result cache/officialscore/100percent claim.'};(d/'next-hypothesis.json').write_text(json.dumps(next,indent=2)+'\n');(d/'checksums.sha256').write_text(''.join(sha(x)+'  '+x.name+'\n' for x in sorted(d.iterdir()) if x.is_file() and x.name!='checksums.sha256'));print('PASS rejected experiment, raw timing and native proofs archived')
