from pathlib import Path
import json,hashlib,tarfile,shutil
r=Path('/Users/junkawasaki/github/wt/amu-seed17');w=Path('/private/tmp/amu-multi-cold-20261005');d=r/'docs/evidence/coscientist-multi-cold-20261005';d.mkdir()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
reports=[]
for row in json.loads((w/'all-summary.json').read_text()):
 name=row['workload'];base=w/'remote-timing'/name;b=json.loads((base/'baseline/results.json').read_text());t=json.loads((base/'timing/results.json').read_text());mf=json.loads((base/'candidate/manifest.json').read_text());e=b['entries'][0]
 assert t['status']=='complete-provisional-candidate-timing' and t['acceptedTriples']==30 and t['summary']['stable'] ;assert sha(base/'baseline/results.json')==t['baselineResultsSha256'];assert sha(base/'baseline'/name/'native.bin')==e['nativeSha256']==mf['baselineNativeSha256'];assert sha(base/'baseline'/name/'c.dylib')==e['cDylibSha256'];assert sha(base/'candidate/native.bin')==mf['nativeSha256'];assert mf==t['manifest'];assert sha(r/'bench/embench/paired-timing-spec.json')==t['specSha256'];assert sha(r/'bench/embench/comparison-matrix.json')==b['matrixSpecSha256']
 s=t['summary'];gap=s['candidate']['meanNsPerBody']-s['baseline']['meanNsPerBody'];sd=s['candidate']['sdNs']+s['baseline']['sdNs'];reports.append({'workload':name,'acceptedTriples':t['acceptedTriples'],'attemptedTriples':t['attemptedTriples'],'summary':s,'regressionGapNs':gap,'summedSdNs':sd,'regressionSeparated':gap>sd,'baselineResultsSha256':sha(base/'baseline/results.json'),'timingResultsSha256':sha(base/'timing/results.json')})
assert len(reports)==19
assert any(x['regressionSeparated'] for x in reports)
proof=json.loads((w/'fixture-proof.json').read_text());gen=json.loads((w/'generations.json').read_text());assert len({x['sha256'] for x in gen[1:]})==1
summary={'status':'complete-mixed-multiple-site-cold-fuel-experiment','decision':'Reject global promotion: separated regression violates prospective all19 acceptance. Product remains qualified scalar-tree version.','sourceHead':'ca907def12d5c55a826745f8b1a18812829331bf','generations':gen,'prototypeSourceSha256':sha(w/'41-a64gen-prototype.kotoba'),'unitySourceSha256':sha(w/'seed-unity.kotoba'),'canonicalWorkloads':19,'canonicalResultFuelExhaustionStatus':json.loads((w/'ports-correctness.json').read_text())['status'],'nativeFixtureProof':{k:proof[k] for k in ['status','canonicalRuns','fixtures','realTestLayoutIdentical','supervisorComparisons','instructionAudit']},'spanProof':json.loads((w/'span-proof.json').read_text()),'compilerGenerationEntryOffsets':{str(n):int((w/f'seed-{n}.offset').read_text()) for n in [2,3,4]},'supplementaryZeroEntry':json.loads((w/'zero-entry-proof.json').read_text()),'workspace':json.loads((w/'bulk-state.json').read_text()),'codeChanges':json.loads((w/'code-change.json').read_text()),'timingReports':reports,'measurementScriptSha256':sha(w/'measure-native-candidate-v2.py'),'productChanged':False,'promotionEligible':False,'officialEmbenchScore':False,'formalPerfgateQualified':False,'COrBetterEvidence':False}
(d/'summary.json').write_text(json.dumps(summary,indent=2)+'\n');shutil.copyfile(w/'prototype.diff',d/'prototype.diff')
with tarfile.open(d/'native-proof.tgz','w:gz') as a:
 names=['create.py','build.py','41-a64gen-prototype.kotoba','hypothesis.json','generations.json','check-ports.py','ports-correctness.json','code-change.json','bulk-state.py','bulk-state.json','picojpeg-state-observer.kotoba','bulk-baseline','bulk-candidate','fixture-proof.py','fixture-proof.json','fixture-baseline-code.bin','fixture-candidate-code.bin','zero-entry-proof.py','zero-entry-proof.json','zero-entry-baseline','zero-entry-candidate','span-proof.py','span-proof.kotoba','span-proof.bin','span-proof.stdout','span-proof.json','span-compile.log','span-extract.log','failed-audit-name.txt','resume-fixture.py']
 for name in names:a.add(w/name,arcname=name)
 for glob in ['seed-*.bin','seed-*.offset','seed-*.log','candidate-*.kotoba','candidate-*.bin','candidate-*.stdout','candidate-*.log','baseline-real.kotoba','baseline-real.bin','baseline-real.stdout','baseline-real-*.log']:
  for p in sorted(w.glob(glob)):a.add(p,arcname=p.name)
with tarfile.open(d/'timing.tgz','w:gz') as a:
 for name in ['remote-timing','all-summary.json','remote-all.py','prepare-timing.py','measure-native-candidate-v2.py']:a.add(w/name,arcname=name)
 for name in ['paired-timing-spec.json','comparison-matrix.json']:a.add(r/'bench/embench'/name,arcname=name)
next={'status':'registered-unimplemented-transaction-preserving-masked-writer-hypothesis','hypothesis':'Recognize exact typed SIR for a one-element vector writer composed of entry fuel, an integer AND255, and the already admitted charged vector-write wrapper. Inline the exact structure without benchmark/source/function names. Preserve bounds trap ordering, callee leaf fuel transaction and publication, unknown call fallback and original partial writes. Do not merely substitute caller fuel instructions: nonleaf caller context commits differ from the callee leaf transaction.','rationale':'Native charge profiling points to repeated bounded writer calls. Eliminating real call/return and stack overhead could help freshly executed work without result memoization. Counts are charge observations, not exclusive time. Cold layout experiments have separated EDN regressions; do not stack unqualified cold layouts.','baseline':'Qualified scalar-tree product only; unchanged canonical19 sources and original C/runner.','proof':'Exact SIR dependencies and ABI; native fixedpoint; all19 result/exactfuel/exhaustion; 8192cell Pico state; lowfuel/bounds/partial-write/context and caller/callee trap-state proofs. Abort admission for any unknown shape or effect.','timing':'Fresh30 rotating quiet product/candidate/C triples for every changed workload; >=1.05 and gain>summed SD; no separated regression; retain fixed cap/negative results. No unchanged-code retiming.'}
(d/'next-hypothesis.json').write_text(json.dumps(next,indent=2)+'\n')
files=sorted(x for x in d.iterdir() if x.is_file());(d/'checksums.sha256').write_text(''.join(sha(x)+'  '+x.name+'\n' for x in files));print('PASS all19 evidence pins; wins',sum(x['summary']['candidateImprovesBaseline'] for x in reports),'regressions',[x['workload'] for x in reports if x['regressionSeparated']],flush=True)
