from pathlib import Path
import json,hashlib,stat,sys,importlib.util,re
D=Path('/Users/junkawasaki/github/workspaces/codex/tc-homogeneous-tail-frame-native4-source-v1-20261009');S=D/'run-outputs';O=Path(__file__).resolve().parent;sys.dont_write_bytecode=True;sys.path.insert(0,str(D))
def rec(p):
 p=Path(p);a=p.lstat();assert stat.S_ISREG(a.st_mode)and not p.is_symlink();b=p.read_bytes();return dict(path=str(p),bytes=len(b),sha256=hashlib.sha256(b).hexdigest())
def ck(p,r):a=rec(p);assert all(a[k]==r[k]for k in ['bytes','sha256']);return Path(p).read_bytes()
sp=json.loads((D/'source-pins.json').read_bytes());ip=json.loads((D/'input-pins.json').read_bytes());pr=json.loads((D/'preregistration.json').read_bytes())
for p,r in sp.items():ck(D/p,r)
for p,r in ip.items():ck(p,r)
G=Path('/Users/junkawasaki/github/workspaces/codex/tc-homogeneous-tail-frame-native4-go-root-v1-20261009/root-go.json');g=json.loads(G.read_bytes())
assert set(g)=={'status','maximumLoaderCalls','outputRoot','noRetry','timingAuthorized','runtimeGuestAuthorized','C2','sourcePinsSHA256','inputPinsSHA256','preregistrationSHA256','driverSHA256','sourceReviews','integrationFixtureProof','hostAuthorizedOuterEscalation'}and g['hostAuthorizedOuterEscalation']is True and g['maximumLoaderCalls']==4 and g['noRetry']is True
for n,k in [('source-pins.json','sourcePinsSHA256'),('input-pins.json','inputPinsSHA256'),('run.py','driverSHA256'),('preregistration.json','preregistrationSHA256')]:assert rec(D/n)['sha256']==g[k]
assert len(g['sourceReviews'])==2 and len({r['path']for r in g['sourceReviews']})==2
for rp in g['sourceReviews']:
 q=json.loads(ck(rp['path'],rp));assert q['status']==pr['sourceReviewStatus']and all(q[k]==g[k]for k in ['sourcePinsSHA256','driverSHA256','preregistrationSHA256'])
assert g['integrationFixtureProof']==pr['qualifiedIntegrationFixtureProof'];fp=json.loads(ck(g['integrationFixtureProof']['path'],g['integrationFixtureProof']))
for n,k in [('capture.py','captureSHA256'),('integration.py','integrationSHA256'),('controller.py','controllerSHA256')]:assert fp[k]==sp[n]['sha256']
rows=json.loads((S/'attempts.json').read_bytes());assert len(rows)==1;r=rows[0];c=pr['cases'][0];assert r['nativeArgv']==c['nativeArgv']and r['environment']==pr['environment']and r['state']=='terminal'and r['returncode']==1 and r['waitEntered']and not r['waitUncertain']and r['signalingAuthorityRetired']and r['captureStopAcknowledged']and not r['watchdogErrors']
sealPath=S/'G1-compile.admission.json';seal=json.loads(sealPath.read_bytes());assert seal['rootGO']==rec(G)and seal['nativeArgv']==c['nativeArgv']and seal['sourcePinsSHA256']==g['sourcePinsSHA256']and seal['preregistrationSHA256']==g['preregistrationSHA256']and seal['input']['sha256']==pr['sourceSHA256']
for k in ['producer','producerContainer','input']:ck(seal[k]['path'],seal[k])
assert r['argv'][:6]==[pr['interpreter']['path'],str(D/'launch-wrapper.py'),'--journal-fd','3','--admission-sha',rec(sealPath)['sha256']]and r['argv'][6:]==['--',*c['nativeArgv']]
raw={k:ck(S/('G1-compile'+ext),r[k])for k,ext in [('stdout','.stdout'),('stderr','.stderr'),('limitJournal','.limit-journal.jsonl'),('memoryJournal','.memory-journal.jsonl')]}
spec=importlib.util.spec_from_file_location('pure_resource_journal',D/'native-call.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);assert m.resource_journal(S/'G1-compile.limit-journal.jsonl',pr,c['nativeArgv'])
obs=r['controllerObservation'];cap=obs['capture'];mr=obs['memoryAdmissionRecord'];assert cap['completeRaw']and cap['stoppedWriter']and cap['EOF']==dict(stdout=True,stderr=True)and not any(cap['dropped'].values())and not cap['errors']and cap['hashes']=={k:r[k]for k in ['stdout','stderr']}
assert obs['status']=='REFUSE'and not obs['semanticQualification']and mr['failure']is None and mr['otherRefusals']==['validation:AssertionError','resource-journal-unqualified']and mr['groupOperationsAfterWait']==mr['groupOperationsAfterUncertainty']==0
samples=[json.loads(x)for x in raw['memoryJournal'].splitlines()];assert len(samples)==r['memorySamples']==obs['sampleCount']==mr['acceptedSamples']==56;prev=0;births={};sums=[]
for i,q in enumerate(samples,1):
 assert q[0]==i and q[1]>prev and q[2]==r['pid']and 1<=len(q[3])<=2 and len({z[0]for z in q[3]})==len(q[3])and any(z[0]==r['pid']for z in q[3]);prev=q[1]
 for pid,bt,foot in q[3]:assert bt>0 and foot>=0 and (pid not in births or births[pid]==bt);births[pid]=bt
 total=sum(z[2]for z in q[3]);assert total<=4294967296;sums.append(total)
assert not raw['stdout']and raw['stderr'].startswith(b"seed: E2101 unknown or unsupported form 'enc-mov' (byte 884739)\n")
from runtime import counters
assert counters(raw['stderr'])['status']=='unavailable-or-invalid';tail=raw['stderr'][raw['stderr'].index(b'KEXE_ARENA_USE'):];arenas=counters(tail);assert arenas['status']=='valid'
assert json.loads((S/'terminal.json').read_bytes())==dict(calls=1,closed=True,failure=True)and json.loads((S/'failure.json').read_bytes())['noRetry']is True
assert not any(Path(x['outputPath']).exists()for x in pr['cases'])and not any((S/x).exists()for x in ['report.json','results.json'])
for p,rp in json.loads((S/'generated-pins.json').read_bytes()).items():ck(p,rp)
source=(D/'candidate-current16.kotoba').read_bytes();assert source==(S/'candidate-current16.kotoba').read_bytes();calls=set(re.findall(rb'\((enc-[A-Za-z0-9!?_-]+)\s',source));defs=set(re.findall(rb'\(defn-?\s+(enc-[A-Za-z0-9!?_-]+)\s',source));missing=sorted(x.decode()for x in calls-defs);assert missing==['enc-mov'];spots=[x.start()for x in re.finditer(rb'\(enc-mov ',source)];assert spots==[884738,885508]and source[884739:884746]==b'enc-mov';assert b'(defn- enc-mov-r 'in source and b'(defn- enc-mov 'not in source
report={'status':'PASS_INDEPENDENT_SAVED_FAILURE_HFT_NATIVE4_V1_UNKNOWN_ENCODER_ONLY','independent':True,'priorSOURCEReviewer':True,'priorImplementationAuthorship':False,'sourcePinsSHA256':g['sourcePinsSHA256'],'inputPinsSHA256':g['inputPinsSHA256'],'driverSHA256':g['driverSHA256'],'preregistrationSHA256':g['preregistrationSHA256'],'rootGO':rec(G),'sourceReviews':g['sourceReviews'],'verifiedClosure':dict(sourceFiles=len(sp),inputFiles=len(ip),inputLogicalBytes=sum(x['bytes']for x in ip.values())),'calls':1,'directWaitReturncode':1,'remainingUnexecuted':[x['label']for x in pr['cases'][1:]],'capture':cap,'resourceJournalIndependentlyInstalled':True,'retainedControllerObservation':obs,'finiteSamples':dict(count=56,sums=sums,maximumSampledSum=max(sums),leaderBirthBound=mr['acceptedLeaderBirthBound']),'raw':{k:r[k]for k in ['stdout','stderr','limitJournal','memoryJournal']},'diagnosticArenaTail':arenas,'sourceNameEvidence':{'missingEncoderCallDefinitions':missing,'callOpenParenByteOffsets':spots,'rawDiagnosticNameByteOffset':884739,'primaryEncoderDefinedName':'enc-mov-r','scope':'Direct frozen source encoder-call vs definition spelling check; not a full Kotoba name/type analysis.'},'conclusion':'Original once native4 campaign FAIL: current7618 compiler executed and rejected HFTV2 source E2101 enc-mov before generating G1.kseed. No artifacts or remaining3calls. Resource setters installed and no sampling failure context; retained resource-journal-unqualified is downstream validation short-circuit, not failed setter evidence.','reviewerMiss':'Both root and this independent SOURCE review missed concrete helper definition closure. The architecture model used instruction words and did not validate enc-mov versus primary enc-mov-r name. Prior SOURCE PASS is not syntax qualification; actual rejection is preserved, and missing reference must be corrected only in a fresh source version.','limits':['No optimizer candidate compiler created/guest executed; no code-emission/runtime/performance qualification.','56 finite footprint samples do not certify hardpeak; directchild wait1/source-bound receipts are not external syscall chronology or separately observed descendant wait.','Root reports once host require_escalated and session9903 CLOSED1; outer result attribution separate from durable directchild rc1.'],'noRetry':True,'operationalCalls':0,'subjectEdits':False,'evidence':{p.name:rec(p)for p in S.iterdir()if p.is_file()}}
p=O/'report.json';p.write_text(json.dumps(report,indent=2)+'\n');print(rec(p))
