"""Saved first-failure audit only. No campaign execution or runtime APIs."""
from pathlib import Path,PurePosixPath
import json,hashlib,base64,sys,importlib.util
W=Path('/Users/junkawasaki/github/workspaces/codex');S=W/'current17-consumer-qualify342-source-v1-20261009-dense';K=W/'current17-consumer-qualify342-v1-failure-collection-root-20261009';D=K/'collected';O=D/'consumer-qualification-outputs';A=Path(__file__).resolve().parent
checked={}
def h(b):return hashlib.sha256(b).hexdigest()
def rec(p):b=p.read_bytes();q=dict(path=str(p),bytes=len(b),sha256=h(b));checked[str(p)]=q;return q
def load(p):return json.loads(p.read_bytes())
def check(p,r):assert p.is_file()and not p.is_symlink();q=rec(p);assert(q['bytes'],q['sha256'])==(r['bytes'],r['sha256']);return p.read_bytes()
summary=load(K/'collection-summary.json');raw=(K/'actual.stdout').read_bytes();assert h(raw)==summary['payloadSHA256'];collection=json.loads(raw);names=set();total=0
for r in collection['files']:
 p=PurePosixPath(r['path']);assert not p.is_absolute()and'..'not in p.parts and str(p)not in names;names.add(str(p));b=base64.b64decode(r['base64'],validate=True);assert len(b)==r['bytes']and h(b)==r['sha256']and check(D/str(p),r)==b;total+=len(b)
assert len(names)==34==summary['files']and total==508190==summary['logicalBytes']==collection['logicalBytes']and names=={str(p.relative_to(D))for p in D.rglob('*')if p.is_file()}
g=load(D/'root-current17-qualification-GO/root-go.json');root=g['taskRoot'];pr=load(S/'preregistration.json');sp=load(S/'source-pins.json');ip=load(S/'input-pins.json');assert len(sp)==25 and len(ip)==108
for n,r in sp.items():check(S/n,r)
for n,k in [('source-pins.json','sourcePinsSHA256'),('input-pins.json','inputPinsSHA256'),('run.py','driverSHA256'),('preregistration.json','preregistrationSHA256')]:assert h((S/n).read_bytes())==g[k]
m={r['relativePath']:r for r in load(W/'tc-hft-current19-packet-install-source-v3-20261009-crc/manifest.json')['files']}
for n,r in ip.items():assert (m[n]['bytes'],m[n]['sha256'])==(r['bytes'],r['sha256']);check(Path(m[n]['source']),r)
def local(p):return D/str(PurePosixPath(p).relative_to(root))
for r in g['sourceReviews']:
 q=json.loads(check(local(r['path']),r));assert q['status']==pr['sourceReviewStatus']and all(q[k]==g[k]for k in ['sourcePinsSHA256','driverSHA256','preregistrationSHA256'])
assert len(g['sourceReviews'])==2 and len(g['consumerProofs'])==len(g['C19Proofs'])==19
sys.dont_write_bytecode=True;sys.path.insert(0,str(S));import run,prepare,header,qualification,ownership
assert set(g)==run.GO_KEYS and g['status']==pr['qualifyGOStatus']and g['maximumLoaderCalls']==342 and g['runtimeGuestAuthorized']is True and g['timingAuthorized']is False and g['noRetry']is True and g['C2']is False and run.validate_scope(pr,ip)
rows=load(S/'packet.json')['entries'];arts={};cp={}
for r in g['C19Proofs']:
 w=Path(r['path']).name.removeprefix('C19-').removesuffix('.json');q=json.loads(check(W/f'current19-C-build38-v3-actual-review-independent-20261009/per-work/{w}.json',r));assert q['status']=='PASS_INDEPENDENT_FRESH_CURRENT19_C_BUILD_SOURCE_IDENTITY_ONLY'and q['workload']==w;check(Path(q['savedCopy']['path']),q['savedCopy']);cp[w]=(r,q)
for r in g['consumerProofs']:
 q=json.loads(check(local(r['path']),r));w=q['workload'];assert q==load(W/f'current17-consumer-build38-v2-actual-review-independent-20261009-dense/per-work/{w}.json');assert q['status']=='PASS_INDEPENDENT_FRESH_CURRENT17_CONSUMER_BUILD_SOURCE_IDENTITY_ONLY'and q['consumerBuildSourcePinsSHA256']=='514bbfffffb4718e3a175989001ece4e9da39ad3770c6424347ebe252f71a6ba'and q['consumerSourcePinsSHA256']==pr['consumerSourcePinsSHA256']and q['CProof']==cp[w][0];check(Path(q['savedCopy']['path']),q['artifact']);row=next(z for z in rows if z['workload']==w);b=header.header(row,check(Path(row['OFF']['native']['path']),row['OFF']['native']),check(Path(row['ON']['native']['path']),row['ON']['native']),check(Path(cp[w][1]['savedCopy']['path']),cp[w][1]['artifact']),cp[w][1]);assert len(b)==q['generatedHeader']['bytes']and h(b)==q['generatedHeader']['sha256'];arts[w]=q['artifact']
assert len(arts)==len(cp)==19
rr=load(O/'runtime-preregistration.json');cases=prepare.qualification_cases(Path(root),rows,arts);expected=dict(pr);expected.update(qualificationSourcePinsSHA256=g['sourcePinsSHA256'],taskRoot=root,freshOutputRoot=root+'/consumer-qualification-outputs',interpreter=g['hostBinding']['interpreter'],cases=cases,environment=pr['environmentBase']|{'TMPDIR':root+'/consumer-qualification-outputs'},maximumLoaderCalls=342,rootGOStatus=pr['qualifyGOStatus'],invocationSealVersion='current17-consumer342-held-v6-invocation/v1');assert rr==expected
at=load(O/'attempts.json');assert len(at)==1;attempt=at[0];case=cases[0];base=O/case['label'];assert case['nativeArgv']==[root+'/consumer-build-outputs/aha-mont64/consumer','OFF','0','1','1']and attempt['index']==1 and attempt['label']==case['label']and attempt['nativeArgv']==case['nativeArgv']and attempt['environment']==rr['environment'];gen=load(O/'generated-pins.json');assert len(gen)==2
for p,r in gen.items():check(local(p),r)
seal=load(base.with_suffix('.admission.json'));gr=seal['rootGO'];check(local(gr['path']),gr);assert seal==dict(format=rr['invocationSealVersion'],index=1,case=case,runtimeRegistration=dict(path=root+'/consumer-qualification-outputs/runtime-preregistration.json',bytes=(O/'runtime-preregistration.json').stat().st_size,sha256=h((O/'runtime-preregistration.json').read_bytes())),rootGO=gr,sourcePinsSHA256=g['sourcePinsSHA256'],preregistrationSHA256=g['preregistrationSHA256']);assert attempt['invocation']==h(base.with_suffix('.admission.json').read_bytes())
for key,suf in [('stdout','stdout'),('stderr','stderr'),('limitJournal','limit-journal.jsonl'),('memoryJournal','memory-journal.jsonl'),('ownershipJournal','ownership-journal.jsonl')]:check(base.with_suffix('.'+suf),attempt[key])
out=base.with_suffix('.stdout').read_bytes();err=base.with_suffix('.stderr').read_bytes();first,timer=out.splitlines(keepends=True);decoded=qualification.native_raw(first,err);assert decoded==case['expected'];t=json.loads(timer);assert t==dict(schema='CURRENT17_TIMING_V1',arm=0,calls=1,warmup=1,elapsedNs=0,nativeObservablesAvailable=True,resetIncluded=False)
try:qualification.parse(out,err,case,case['expected'],0)
except AssertionError:pass
else:raise AssertionError('original parser unexpectedly accepted elapsed0')
changed=dict(t,elapsedNs=1);assert qualification.parse(first+(json.dumps(changed)+'\n').encode(),err,case,case['expected'],0)['observables']==decoded
# Source-derived resource check pure; import does not call operational call().
spec=importlib.util.spec_from_file_location('saved_resource',S/'native-call.py');nc=importlib.util.module_from_spec(spec);spec.loader.exec_module(nc);assert nc.resource_journal(base.with_suffix('.limit-journal.jsonl'),rr,case['nativeArgv'])
assert attempt['state']=='terminal'and attempt['returncode']==0 and attempt['waitEntered']is True and attempt['waitUncertain']is False and attempt['signalingAuthorityRetired']is True and attempt['captureStopAcknowledged']is True and attempt['ownershipWriterStopAcknowledged']is True and attempt['watchdogErrors']==[]and attempt['failure']=='AssertionError()'
bindings={int(k):v for k,v in attempt['ownershipBindings'].items()};leader=attempt['pid'];child=next(p for p in bindings if p!=leader);assert len(bindings)==2;nonce=h((attempt['invocation']+gr['sha256']).encode());own=[json.loads(x)for x in base.with_suffix('.ownership-journal.jsonl').read_bytes().splitlines()];assert len(own)==4
for j,(stage,seq,wirechild,pid)in enumerate([(2,1,0,leader),(4,2,child,child),(6,3,child,child),(8,4,child,child)]):
 wire=ownership.encode(stage,seq,leader,wirechild,bindings[pid],leader,0,bytes.fromhex(gr['sha256']),bytes.fromhex(nonce));common=dict(pid=pid,birth=bindings[pid],GO=gr['sha256'],nonce=nonce,wireSHA256=h(wire));wanted=dict(stage='held-birth-admitted',sequence=seq,leader=leader,**common,guestStillHeld=True)if j<2 else dict(stage='loader-child-exit-held',**common,exit=0,unreapedPIDAnchor=True)if j==2 else dict(stage='loader-child-wait',**common,waitStatus=0,noPostReapGroupQueries=True);assert own[j]==wanted
assert attempt['childWaitReceipt']==dict(pid=child,birth=bindings[child],exit=0,durable=True)
mem=[json.loads(x)for x in base.with_suffix('.memory-journal.jsonl').read_bytes().splitlines()];assert len(mem)==attempt['memorySamples']==3 and len(base.with_suffix('.memory-journal.jsonl').read_bytes())==attempt['memoryJournalBytes'];maximum=0;last=-1
for i,q in enumerate(mem,1):
 assert len(q)==4 and q[0]==i and last<q[1]and q[2]==leader;last=q[1];pids=set()
 for p,b,f in q[3]:assert p in bindings and b==bindings[p]and f>=0 and p not in pids;pids.add(p)
 assert leader in pids and(i!=1 or pids=={leader})and(i!=2 or pids=={leader,child});maximum=max(maximum,sum(x[2]for x in q[3]));assert maximum<=4294967296
obs=attempt['controllerObservation'];mrec=obs['memoryAdmissionRecord'];cap=obs['capture'];assert obs['status']=='REFUSE'and obs['semanticQualification']is False and obs['strictHeldSamplingPolicyPassed']is False and obs['memoryObservation']=={'status':'refused','hardPeakQualified':False};assert mrec['failure']is None and mrec['otherRefusals']==['validation:AssertionError','resource-journal-unqualified']and mrec['heldOwnershipQualified']is False and mrec['exactHeldChildWait0']is False
assert cap['EOF']=={'stdout':True,'stderr':True}and cap['completeRaw']and cap['stoppedWriter']and cap['errors']==[]and cap['dropped']=={'stdout':0,'stderr':0}and cap['hashes']=={'stdout':attempt['stdout'],'stderr':attempt['stderr']}and cap['retained']=={'stdout':len(out),'stderr':len(err)}and cap['observedBytes']==len(out)+len(err)
ev=obs['controllerEvents'];assert ev==['group-operation']*3+['retire:owned-child-exit-before-reap-ACK','retire:before-watchdog-stop-and-wait','wait-enter','retire:final-cleanup'];assert mrec['groupOperationsAfterWait']==mrec['groupOperationsAfterUncertainty']==0
assert load(O/'terminal.json')==dict(consumerCalls=1,allChildrenClosed=True,failure=True)and load(O/'failure.json')['noRetry']and not(O/'results.json').exists()and not(O/'report.json').exists()and len(list(O.glob('*.admission.json')))==1
extension=Path(m['source/consumer/timing-extension.h']['source']);text=extension.read_text();assert 'if(end<begin||UINT64_MAX-total<end-begin)'in text and 'total+=end-begin;'in text
q=dict(status='PASS_INDEPENDENT_SAVED_CURRENT17_CONSUMER342_V1_FIRST_FAILURE_AUDIT_ONLY',sourcePinsSHA256=g['sourcePinsSHA256'],inputPinsSHA256=g['inputPinsSHA256'],driverSHA256=g['driverSHA256'],preregistrationSHA256=g['preregistrationSHA256'],rootGO=gr,collection=rec(K/'actual.stdout'),collectionSummary=rec(K/'collection-summary.json'),sourceReviews=g['sourceReviews'],consumerBuildProof=rec(W/'current17-consumer-build38-v2-actual-review-independent-20261009-dense/report.json'),verified=dict(sourceFiles=25,inputFiles=108,collectedFiles=34,collectedBytes=508190,CProofs=19,consumerProofs=19,generatedHeaders=19,declaredCases=342,executedCases=1,remainingUnexecuted=341,directWait0=1,heldChildWait0=1,memorySamples=3,maximumObservedGroupFootprint=maximum,resourceJournalRows=6,ownershipJournalRows=4),rawObservation=dict(case=case,stdout=rec(base.with_suffix('.stdout')),stderr=rec(base.with_suffix('.stderr')),structured=decoded,timing=t),failure='Frozen parse requires elapsedNs>0; saved elapsedNs0 raises AssertionError before qualifiedResources callback. Controller records validation refusal and derived resource-journal-unqualified; independent six-row resource decode succeeds, so no named setter failure is observed.',sourceTrace=dict(decoder=rec(S/'qualification.py'),controller=rec(S/'controller.py'),nativeCall=rec(S/'native-call.py'),clockExtension=rec(extension),clockSemantics='Primary extension accepts end==begin and accumulates zero. Saved raw has no begin/end timestamps or kernel clock-resolution trace; exact zero cause remains unknown.'),reviewCorrection='My SOURCE review passed the >0 qualifier without challenging the primary timer legal-zero case; that mismatch was missed. This saved failure remains permanent and is not credited under future relaxed parser.',campaignQualified=False,semanticAdmissionQualified=False,strictHeldPolicyPassed=False,actual342Qualified=False,qualifiedConsumerCalls=0,conditionalStructuredRawMatchesCurrent190=True,performanceQualified=False,C2=False,newOperationalCalls=0,reviewerRole='HeldV6 mechanism author and prior qualifier SOURCE reviewer; independent of Dense qualifier implementation and root once execution.',limitations=['Saved correlated source/journals establish one direct wait0 and durable held childwait0 observations, not universal kernel/WNOWAIT/FD/scheduling proof.','Original controller REFUSE retained despite separately decoded resource and wait receipts. No accepted sampler policy or generic342 child proofs issued.','No OFF/ON/C pair, repeat/reset campaign, C comparison or full19 runtime/timing qualification from this one prefix.','Zero duration is an emitted raw field, not measured performance benefit or proof of exact clock quantization cause.'],checkedSavedPins=checked)
save=lambda p,v:p.write_text(json.dumps(v,indent=2)+'\n');save(A/'report.json',q);print(rec(A/'report.json'))
