from pathlib import Path
import tarfile,json,hashlib,subprocess
r=Path('/Users/junkawasaki/github/wt/amu-seed17');w=Path('/private/tmp/amu-affine-join-20261005');z=Path('/private/tmp/amu-affine-index-20261005');d=r/'docs/evidence/coscientist-affine-join-20261005';d.mkdir(exist_ok=True);sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();fp=json.loads((w/'fixture-proof.json').read_text());tp=json.loads((w/'timing-audit.json').read_text());obs=json.loads((w/'descriptor-admission.json').read_text());zero=json.loads((z/'descriptor-admission.json').read_text());assert not tp['qualifies'] and fp['supervisorComparisons']==22152 and obs['specializedIndexSites']==4 and zero['specializedIndexSites']==0;assert (w/'baseline-41-a64gen.kotoba').read_bytes()==(r/'seed/41-a64gen.kotoba').read_bytes()
summary={'status':'complete-rejected-native-join-constant-specialization','sourceHeadBefore':'83fa3b30ba1c70bf00fed01a0529e1c11e5b8dc2','decision':'No product promotion: ratio1.045654<1.05 and mean gap<summedSD. Zero-admission predecessor rejected before timing.','productChanged':False,'fullReleaseGateClaim':False,'officialEmbenchScore':False,'COrBetter':False,'hypothesis':json.loads((w/'hypothesis.json').read_text()),'generations':json.loads((w/'generations.json').read_text()),'zeroAdmissionPredecessor':{'specializedSites':0,'nativeGenerations':json.loads((z/'generations.json').read_text()),'decision':'Reject before measurement; no complete native state/gates claimed.'},'admission':obs,'observerByteAudit':json.loads((w/'observer-byte-audit.json').read_text()),'nativeProof':{k:fp[k] for k in ['status','dominanceCases','fixtures','canonicalRuns','realTestLayoutIdentical','supervisorComparisons']},'handOracleReceipt':json.loads((w/'hand-oracle-receipt.json').read_text()),'dominanceProof':json.loads((w/'dominance-proof.json').read_text()),'independentBoundProof':json.loads((w/'limit-proof.json').read_text()),'indexInstructionAudit':json.loads((w/'index-instruction-audit.json').read_text()),'fallbackAudit':json.loads((w/'fallback-audit.json').read_text()),'importSubstitutions':{'ordinary':len(json.loads((w/'import-proof.json').read_text())['runs']),'joined':len(json.loads((w/'join-import-proof.json').read_text())['runs'])},'workspace':json.loads((w/'bulk-state.json').read_text()),'codeChanges':json.loads((w/'code-change.json').read_text()),'timing':tp,'qualificationOrdering':'Actual hand-derived runs and native dominance reports precede measurement; full supervisor proof completed independently after measurement. Original measurement-only preflight retained; no integrated/release gate claim.'};(d/'summary.json').write_text(json.dumps(summary,indent=2)+'\n')
q=subprocess.run(['git','diff','--no-index',str(w/'baseline-41-a64gen.kotoba'),str(w/'41-a64gen-prototype.kotoba')],capture_output=True,text=True);assert q.returncode==1;(d/'prototype.diff').write_text(q.stdout)
(d/'archive.py').write_bytes(Path(__file__).read_bytes());(d/'timing-audit.json').write_bytes((w/'timing-audit.json').read_bytes());(d/'audit.py').write_bytes((w/'audit.py').read_bytes())
with tarfile.open(d/'native-proof.tgz','w:gz') as t:
 for name in ['create.py','build.py','seed-unity.kotoba','seed-0.bin','seed-0.offset','seed-4.bin','seed-4.offset','kexe-loader','41-a64gen-prototype.kotoba','baseline-41-a64gen.kotoba','baseline-a64gen-fixtures.py','generations.json','hypothesis.json','inspected-sir.json','observe.py','descriptor-observer.kotoba','descriptor-unity.kotoba','descriptor-seed.bin','descriptor-admission.json','observer-byte-audit.py','observer-byte-audit.json','check-ports.py','ports-correctness.json','code-change.json','bulk-state.py','bulk-state.json','picojpeg-state-observer.kotoba','bulk-baseline','bulk-candidate','prepare-proof.py','repair-proof.py','fixture-proof.py','fixture-proof.json','hand-oracle-receipt.json','native-preflight.json','dominance-proof.json','candidate-test.stdout','candidate-real.stdout','baseline-real.stdout','first-candidate-test.stdout','first-candidate-real.stdout','first-baseline-real.stdout','fixture-candidate-code.bin','fixture-baseline-code.bin','fixture-first-compile-failure.log','fixture-second-diagnostic-failure.txt','limit-proof.py','limit-proof.json','limit-proof.kotoba','limit-proof.bin','limit-proof.stdout','limit-proof-first-failure.log','index-instruction-audit.py','index-instruction-audit.json','fallback-audit.py','fallback-audit.json','import-proof.py','import-proof.json','join-import-proof.py','join-import-proof.json','baseline-open.stdout','candidate-open.stdout','candidate-closed.stdout','baseline-open-linked.bin','candidate-open-linked.bin','candidate-closed-linked.bin','join-baseline-open.stdout','join-candidate-open.stdout','join-candidate-closed.stdout','join-baseline-open-linked.bin','join-candidate-open-linked.bin','join-candidate-closed-linked.bin']:
  t.add(w/name,arcname=name)
 for name in ['seed/SIR','seed/HEADS','seed/MEMORY-MAP']:t.add(r/name,arcname=name)
 for name in ['clobber-state-loader.c','clobber-state-loader']:t.add(Path('/private/tmp/amu-context-call-20261005')/name,arcname='diagnostic/'+name)
 for e in obs['entries']:t.add(w/'descriptor-ports'/e['workload']/'compile.log',arcname='descriptor-ports/'+e['workload']+'/compile.log')
with tarfile.open(d/'zero-admission.tgz','w:gz') as t:
 for name in ['create.py','build.py','observe.py','41-a64gen-prototype.kotoba','descriptor-observer.kotoba','descriptor-unity.kotoba','descriptor-seed.bin','seed-4.bin','seed-4.offset','generations.json','hypothesis.json','descriptor-admission.json']:t.add(z/name,arcname=name)
 for e in zero['entries']:t.add(z/'descriptor-ports'/e['workload']/'compile.log',arcname='descriptor-ports/'+e['workload']+'/compile.log')
with tarfile.open(d/'timing.tgz','w:gz') as t:
 for name in ['prepare-timing.py','remote-all.py','timing-package','all-summary.json','audit.py','timing-audit.json']:t.add(w/name,arcname=name)
 t.add(Path('/private/tmp/amu-context-call-20261005/measure-native-candidate-v2.py'),arcname='measure-native-candidate-v2.py')
(d/'checksums.sha256').write_text(''.join(sha(x)+'  '+x.name+'\n' for x in sorted(d.iterdir()) if x.is_file() and x.name!='checksums.sha256'))
print('PASS full native evidence and raw negative timing archived; product source remains unchanged')
