#!/usr/bin/env python3
"""seed/tests/kir/doclib/gen-doclib.py [--check] -- embed doclib.kotoba into seed/12-kirread.kotoba (agent KIR4,
BOOTSTRAP-TOOL: generator only, never in a seed's process tree).

The block between the lines ';; BEGIN KIR4 doclib (generated by seed/tests/kir/doclib/gen-doclib.py)' and
';; END KIR4 doclib' of 12-kirread is rewritten from doclib.kotoba: the defns (one per line; comment and blank lines
dropped) become string chunks of kr-doc-text, (def kr-ndoc N) is their count, and (def kr-dj-<name> J) is the library
index of every defn (8 = the first doc defn, after the 8 KIR3 library functions). --check exits 1 when the file differs.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..', '..', '..'))
SRC = os.path.join(HERE, 'doclib.kotoba')
DST = os.path.join(REPO, 'seed', '12-kirread.kotoba')
BEGIN = ';; BEGIN KIR4 doclib (generated by seed/tests/kir/doclib/gen-doclib.py)'
END = ';; END KIR4 doclib'
FIRST = 8      # kr-nlib of the KIR3 library
CHUNK = 8      # defns per string function


def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


def block():
    defs = [l.rstrip('\n') for l in open(SRC, encoding='utf-8') if l.startswith('(defn ')]
    names = [re.match(r'\(defn (\S+)', d).group(1) for d in defs]
    out = [BEGIN, f';; {len(defs)} defns from seed/tests/kir/doclib/doclib.kotoba; edit that file, then run the generator']
    out.append(f'(def kr-ndoc {len(defs)})')
    for j, nm in enumerate(names):
        out.append(f'(def kr-dj-{nm[5:]} {FIRST + j})')
    chunks = [defs[i:i + CHUNK] for i in range(0, len(defs), CHUNK)]
    for k, ch in enumerate(chunks):
        out.append(f'(defn- kr-doc-text{k} [] :string')
        parts = ['"' + esc(d) + '\\n"' for d in ch]
        expr = parts[-1]
        for p in reversed(parts[:-1]):
            expr = f'(string-concat {p}\n  {expr})'
        out.append('  ' + expr + ')')
    expr = f'(kr-doc-text{len(chunks) - 1})'
    for k in range(len(chunks) - 2, -1, -1):
        expr = f'(string-concat (kr-doc-text{k}) {expr})'
    out.append(f'(defn- kr-doc-text [] :string {expr})')
    out.append(END)
    return '\n'.join(out) + '\n'


def main():
    text = open(DST, encoding='utf-8').read()
    i = text.find(BEGIN)
    j = text.find(END)
    if i < 0 or j < 0:
        sys.exit('gen-doclib: markers not found in ' + DST)
    j = text.find('\n', j) + 1
    new = text[:i] + block() + text[j:]
    if '--check' in sys.argv:
        if new != text:
            print('gen-doclib: 12-kirread.kotoba is out of date with doclib.kotoba')
            sys.exit(1)
        print('gen-doclib: up to date')
        return
    open(DST, 'w', encoding='utf-8').write(new)
    print('gen-doclib: wrote', DST)


if __name__ == '__main__':
    main()
