from pathlib import Path
import json,hashlib,tarfile,subprocess
r=Path('/Users/junkawasaki/github/wt/amu-seed17');w=Path('/private/tmp/amu-high-temp-read-20261006');d=r/'docs/evidence/coscientist-high-temp-read-20261006';d.mkdir(parents=True,exist_ok=True);load=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();t=load(w/'timing-summary.json');assert not t['fullCandidateQualifies'];assert (r/'seed/41-a64gen.kotoba').read_bytes()==(w/'baseline-41-a64gen.kotoba').read_bytes()
s={'status':'rejected-native-high-temp-vector-read-with-original-call-spills','baselineSourceCommit':load(w/'hypothesis.json')['sourceCommit'],'decision':'Both changed original guests freshly measured with30 accepted rotating triples each. Neither qualifies unchanged1.05+gap>sumSD rule. Reject complete prototype; no product change or identical-code retiming.','hypothesis':load(w/'hypothesis.json'),'generations':load(w/'generations.json'),'nativeAdmission':load(w/'meta-admission.json'),'instructionAudit':load(w/'instruction-audit.json'),'codeChanges':load(w/'code-change.json'),'nativePreflightSealedBeforeTiming':load(w/'preflight-audit.json'),'timing':t,'productChanged':False,'officialEmbenchScore':False,'COrBetter':False,'productGatesAndIntegration':'Not rerun after performance rejection. Previous qualified affine-reader product remains current.','authoringCorrections':'Independent instruction audit fixed a transcription typo in a comparison word and used actual blob length for the final function end. Compiler and test expectations unchanged. Exact instruction audit completed after timing.','contextNote':'Actual gn-ctx loads context and marks gn-f-ctx=1. Inline sequence preserves x7; no assumption that gn-ctx leaves metadata unknown.'}
for name,key in [('hand-proof.json','highTempHandProof'),('import-proof.json','actualOpenImportProof'),('resource-proof.json','resourcePartialWrites'),('regression-proof.json','freshOriginalRegression'),('ports-state.json','original19StateProof')]:
 v=load(w/name);s[key]={k:x for k,x in v.items() if k not in ['runs','observations']}
s['newFixtureLayout']=load(w/'hand-layout.json');(d/'summary.json').write_text(json.dumps(s,indent=2)+'\n');(d/'archive.py').write_bytes(Path(__file__).read_bytes());(d/'timing-summary.json').write_bytes((w/'timing-summary.json').read_bytes());q=subprocess.run(['git','diff','--no-index',str(w/'baseline-41-a64gen.kotoba'),str(w/'41-a64gen-prototype.kotoba')],capture_output=True,text=True);assert q.returncode==1;(d/'prototype.diff').write_text(q.stdout)
with tarfile.open(d/'native-proof.tgz','w:gz') as a:
 for x in sorted(w.iterdir()):
  if x.name in ['__pycache__','timing-package','regression-run','batch-status.json','remote-timing.log']:continue
  if x.name.startswith('timing-artifact-audit-') or x.name.startswith('timing-audit-'):continue
  a.add(x,arcname=x.name)
 for n in ['seed/MANIFEST','seed/SIR','seed/HEADS','seed/MEMORY-MAP','AGENTS.md','seed/41-a64gen.kotoba','tools/kexe_loader.c','scripts/seed/a64gen-fixtures.py','seed/tests/unit/41-a64gen.expected']:a.add(r/n,arcname='baseline-source/'+n)
 for n in ['clobber-state-loader.c','clobber-state-loader']:a.add(Path('/private/tmp/amu-context-call-20261005')/n,arcname='diagnostic/'+n)
with tarfile.open(d/'timing.tgz','w:gz') as a:
 for n in ['remote-timing.py','timing-package','audit-workload.py','timing-artifact-audit.py','timing-summary.json','batch-status.json','remote-timing.log']:a.add(w/n,arcname=n)
 for x in sorted(w.iterdir()):
  if x.name.startswith('timing-audit-') or x.name.startswith('timing-artifact-audit-'):a.add(x,arcname=x.name)
next={'status':'registered-not-implemented-or-measured','hypothesis':'Remove gn-save0t from high-temp inline vector reads only after proving scratch ownership. Retain original nonleaf prescan/frame, x0/x1 argument staging, x7 context restoration, x16/x17 ordered checks and payload load, and gn-take alias protection. Prefix temps x9..x15, callee-saved locals and high homes stay intact because the replacement has no BL/BLR. Calls elsewhere still retain original gn-save/fuel/context contract.','evidence':'The rejected version retains call-preparation stores and changes prefix descriptors to HOME although its inline access never calls. Local actual gn-save saves only REG/unknown prefix temps0..6. gn-sr assigns these x9..x15, distinct from x0,x1,x7,x16,x17. Static read count is not time share.','proofRequirements':'Fresh native fixedpoint; all19 result/fuel/source/guest byte classification; signed handles/indices, livecomputed register/home prefix through joins, aliases/coalescing, real allocating imports, exact full supervisor state and partial resource/fuel/traps. Prospective unchanged30-triplet timing on every changed guest, followed by permanent fixtures, gates, committed-input integrated3gen and full per-case corpus before promotion.','identityDesign':'Code identity remains normalized typed-KIR content identity. Proposed reusable specialization certificate/artifact key must seal DefCID/dependency closure, semantic profile, compiler/optimization version, target and runtime ABI. Current native SIR lacks that linked DefCID; do not call source/SIR hashes DefCIDs. Invocation-result caches separately require immutable inputs and explicit effects/state/resource contracts.','scope':'All19 original aligned Embench workloads freshly executed, no result cache. No official-score or100percent selfhost claim.'};(d/'next-hypothesis.json').write_text(json.dumps(next,indent=2)+'\n');(d/'checksums.sha256').write_text(''.join(sha(x)+'  '+x.name+'\n' for x in sorted(d.iterdir()) if x.is_file() and x.name!='checksums.sha256'));print('PASS rejected experiment, raw timing and native proofs archived')
