"""Local saved source/receipt reads only, no APIs/native/SSH/compiler/child calls."""
from pathlib import Path
import hashlib,json
D=Path(__file__).resolve().parent;W=D.parent;S=W/'vector-leaf-straight-read-cache-current19-timing-source-v1';F=W/'vector-leaf-straight-read-cache-fresh-consumer-functional285-source-v2-receipt-binding';C=W/'vector-param-runner-telemetry-plan-v1-native-controls/timing-host-telemetry.c'
def ref(p):
 p=Path(p);b=p.read_bytes();return dict(path=str(p),bytes=len(b),sha256=hashlib.sha256(b).hexdigest())
pr=json.loads((S/'preregistration.json').read_bytes());rows=[dict(workload=e['workload'],C=e['C'],exceedsTimingRegularFileCap=e['C']['bytes']>16384)for e in pr['entries']]
r=dict(status='SAVED_SOURCE_FAILURE_DIAGNOSIS_STRONG_CAUSAL_HYPOTHESIS_NOT_SYSCALL_TRACE',failure=dict(child=14,label='aha-mont64-cal-C-0',returncode=-25,signal='SIGXFSZ',stdoutBytes=0,stderrBytes=0),sourceEvidence=[ref(S/'ledger.py'),ref(F/'ledger.py'),ref(C),ref(S/'launch-outputs/children/00001/stderr')],sourcePath=dict(function='timing_known_c_library',lines=[689,706],writes='Embedded immutable C image written to /private/tmp/amu-timing-C-XXXXXX/known.dylib before dlopen',bytesAha=17432,acceptedFunctionalRegularFileLimit=16777216,timingRegularFileLimit=16384,limitScope='RLIMIT_FSIZE applies to every regular-file write, not only stdout/stderr'),CImages=rows,maximumCBytes=max(e['C']['bytes']for e in pr['entries']),causalAssessment='SIGXFSZ with empty telemetry and 1450000ns childCPU is explained by known.dylib materialization crossing16KiB before dlopen. No dyld-cache defect is needed. Exact offending syscall is not traced.',tempLifetime=dict(success='close fd then dlopen then unlink known.dylib and rmdir; source does not use TMPDIR for this directory',signalFailure='SIGXFSZ interrupts before unlink/rmdir; one orphan directory/partial dylib may remain in /private/tmp',maximumSuccessfulLiveFilesPerSequentialCChild=1,maximumNormalLiveBytes=83640,campaignMaximumCChildren=1805,campaignTotalMaterializationBytesUpper=1805*83640,firstFailureStop='At most one additional orphan per failed prospective campaign if previous successful unlink/rmdir operations worked; no cleanup proof without filesystem inspection',unlinkRmdirReturnIgnored=True),prospectiveV2=dict(regularFileLimit=16777216,runnerOutputStreamLimit=16384,loadOutputStreamLimit=1024,transportOutputStreamLimit=8388608,pipes='Separate bounded nonblocking stdout/stderr capture; cap+1 detection fails/kills/reaps, parent durable raw sinks never grow beyond perstream cap',nativeConsumerChanges=False,artifactsChanged=False,newRemoteNamespace=True,oldFailureRetained=True,freezeRequiresIndependentActualFailureAcceptance=True),operationalCalls=0)
(D/'report.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps(dict(status=r['status'],maximumCBytes=r['maximumCBytes'],materializationUpper=r['tempLifetime']['campaignTotalMaterializationBytesUpper'])))
