from pathlib import Path
import json,hashlib,stat,importlib.util,copy
W=Path('/Users/junkawasaki/github/workspaces/codex');D=W/'tc-homogeneous-tail-frame-candidate-source-v1-20261009';R=Path(__file__).parent
h=lambda b:hashlib.sha256(b).hexdigest()
def rec(p):b=p.read_bytes();return dict(path=str(p),bytes=len(b),sha256=h(b))
def ck(p,v):assert stat.S_ISREG(p.lstat().st_mode)and not p.is_symlink();b=p.read_bytes();assert len(b)==v['bytes']and h(b)==v['sha256'];return b
sp=json.loads((D/'source-pins.json').read_bytes());ip=json.loads((D/'input-pins.json').read_bytes());fr=json.loads((D/'freeze.json').read_bytes());pr=json.loads((D/'preregistration.json').read_bytes())
for k,v in sp.items():ck(D/k,v)
for k,v in ip.items():ck(Path(k),v)
assert rec(D/'source-pins.json')['sha256']=='7eaed679b0b661562b2b2ff88248af5a33fa9035831ee6652b6a8c590597ab90'and rec(D/'41-a64gen-candidate.kotoba')['sha256']=='b7c80e7ef0cfd56e642f9233acea09c6ca8e0c2b0471cde1de770416ecdd1456'
base=Path(next(k for k in ip if k.endswith('/crc-table-decision-collapse-v2-20261008/41-a64gen-candidate.kotoba'))).read_text();cand=(D/'41-a64gen-candidate.kotoba').read_text();rule=(D/'rule.kotoba').read_text();assert rule in cand
# The existing gn-run wrapper is sole original-source replacement; helper definitions inserted before it.
baseTail='(defn- gn-run [M :vector-i64] :vector-i64 (gn-run-open M 0 0))';newTail='(defn- gn-run [M :vector-i64] :vector-i64 (sf-collapse (gn-run-open M 0 0)))';assert cand.replace(rule+'\n','',1).replace(newTail,baseTail,1)==base
spec=importlib.util.spec_from_file_location('inert_symbolic_equalframe',D/'model.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)
for F in [80,96]:
 s=m.initial(F);assert m.original(s,F)==m.fused(s,F)and m.original(s,F)!=m.fused(s,F,True)
 for fuel in [0,1,2,2**64-1]:assert m.observe(m.original(s,F),fuel)==m.observe(m.fused(s,F),fuel)
# Import only the inert saved-control definitions before the top-level positive/write block.
ns={'__file__':str(D/'saved-controls.py')};src=(D/'saved-controls.py').read_text();exec(compile(src[:src.index('positive=admit(132)')],str(D/'saved-controls.py'),'exec'),ns);pos=ns['admit'](132);assert pos==json.loads((D/'saved-controls-result.json').read_bytes())['firstPositive']
# Concrete namespace reuse counterexample: add otherwise unrelated original label-kind relocation to unused labelindex.
x=copy.deepcopy(ns['fix']);newIndex=len(ns['labels']);pc=next(p for p in ns['code']if p>0 and p<ns['fn'][132][13]and not any(z[0]==p for z in x.values()));x[max(x)+1]=[pc,1,newIndex,0];admitted=ns['admit'](132,fix=x);assert admitted is not None and newIndex not in ns['labels']
ce={'status':'UNRESOLVED_LABEL_TARGET_REUSE_ADMITTED_BY_SOURCE_PREDICATES','existingFix':{'at':pc,'kind':1,'target':newIndex,'aux':0},'oldLabelN':newIndex,'oldLayoutTarget':0,'newLayoutTarget':pos['privateEntryWord'],'pairStillAdmitted':admitted,'scope':'Malformed-M closure counterexample. No claim current saved typedmodule contains this state; candidate predicates do not themselves exclude it.','minimumRepair':'Before mutation require all existing label-kind fixup targets in [1,oldLABEL-N), with original bound initialized target; alternatively provide complete primary typed-lowering invariant proving this for every accepted gn-run route.'};(R/'label-reuse-counterexample.json').write_text(json.dumps(ce,indent=2)+'\n')
# All saved actual labels and FIXs are withinoriginal namespace; counterexample is an addedmutant only.
actualBad=[{'index':k,'fix':z}for k,z in ns['fix'].items()if k>0 and z[1]in [1,2,3]and not(0<z[2]<newIndex and ns['labels'].get(z[2],0)>0)];assert actualBad==[]
r={'status':'HOLD_SOURCE_EQUAL_FRAME_TAIL_NAMESPACE_AND_ABI_CLOSURE_PREMISES','independent':True,'priorImplementationAuthorship':False,'sourcePinsSHA256':rec(D/'source-pins.json')['sha256'],'inputPinsSHA256':rec(D/'input-pins.json')['sha256'],'candidateSHA256':rec(D/'41-a64gen-candidate.kotoba')['sha256'],'freeze':rec(D/'freeze.json'),'sourceRegistry':{'files':len(sp),'logicalBytes':sum(v['bytes']for v in sp.values())},'inputRegistry':{'files':len(ip),'logicalBytes':sum(v['bytes']for v in ip.values())},'baseInverseExact':True,'verifiedConditionalArchitecture':['SameF80/96 exact6wordprologue/singlex19/contextF-8/parameterMOV and completefivewordtail; preservedargMOV0,9 and retainedtargetMOV19,0.','Original restore/repush reloads savedcallerLR. Correct fusion LDR30,[29,#8]+2NOP preservesx30 at targetentry; bare3NOP concretecounterexample remains.','Given valid private frame/contextnonalias and helpers obeycallee-save/frameownership, arbitrary31regs/SP/NZCV/header/framehomes/guestmemory match at retained targetparameter/bodyentry. Identical targetfuel/bodywords then preserve synchronous bodytrap state/PC.','Freshlabel uses existingFX-B26, unchangedCODE/FIX/publicFFCODE/exports/FADDR andoneLABELcell; no prescan/gn-ins rerun andfirstpaironly.','Recorded actualpair132→133/F80/at5567/privateentry5574 verifiedsavedwordsource predicates; currentactual labels/FIXs are valid.'],'savedFirstPair':pos,'namespaceCounterexample':rec(R/'label-reuse-counterexample.json'),'mustResolveBeforeRunnableCandidate':['Newprivate labeloldLABEL-N can resolve an old unresolved label-kindFIX outside protectedwords. Currentactualmodule hasnone; globalfallback contract needs predicate or proved accepted-lowering-route invariant.','Primarycompiled helper and loader ABI must establish private stack/header/homes cannot escape or alias context/vector and preserveactivecallee-save maps; sourcebody recognition alone is not that proof.','Native syntax/typebinding and actual emittedselection still unexecuted; exactincoming/privateentry/fuel/trap/vector/17arena runtime obligations remain separate.'],'trapDebugBoundary':['No narrowing x30, SP, x29, NZCV, synchronous trapPC/unwind/header/home observables is accepted. Exact boundary state checked under validprivateframe premises.','Model excludes asynchronous instruction-step observation of removed intermediate restore/prologue; this assumption is explicit and must align with existing language/debugcontract, not be silently adopted as equivalence.','Pure observe function abstracts identical targetinstruction execution; not independent fullA64 trapmodel.'],'qualification':'Conditional equal-frame transition identity only. No runnableGO/native/runtime/generaloptimizer/adoption/performance proof.','operations':{'nativeThreadFDPipeProcessGroupSetterNetworkCalls':0,'productOrFrozenSubjectWrites':0}}
(R/'report.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps(rec(R/'report.json')))
