#!/bin/zsh
# seed/tests/r6a/gate-r6a.sh [--extra] -- the extra gate of rung R6 entry (agent R6A: values across module boundaries, the string
# arena, the R6 scan). BOOTSTRAP-TOOL (zsh). gates.sh --rung r6a runs it as its XTRA row; BUILD ERR G1 G2 G3 G4 G5 GR (every
# earlier rung's tests incl. the full R5 format) are gates.sh's own rows. Rows here:
#   R6A    seed/tests/r6a/check-r6a.sh with seed-1: keyword, record (+ nested and recursive schemas, the Form shape), fn type,
#          variadic, :bytes and 7-parameter interfaces; in-process image == separate-mode image; the schema conflict refused
#   R5B-X  seed/tests/r5b/gate-r5b.sh --extra: R5B's extra cases and, through it, R5A's namespace-split rung proof (SPLIT fixed
#          point, SPLIT-G1/G2/G4, SEP) with the R6A sources (seed/split regenerated by seed/split/gen-split.py)
# Exit 0 iff every row passes.
emulate -L zsh
setopt pipefail
source "$(dirname "$0")/../../../scripts/seed/lib.sh"
R=$SEED_REPO; B=${SEED_BUILD:A}; D=$R/seed/tests/r6a
fails=0
row() { printf "%-5s %s\n" $1 "$2"; [ $1 = FAIL ] && fails=$((fails+1)); return 0; }
SEED_BUILD=$B zsh $D/check-r6a.sh $B/seed-1.bin > $B/gate-r6a-check.log 2>&1 && row PASS "R6A $(tail -1 $B/gate-r6a-check.log)" \
  || row FAIL "R6A $(grep -E '^FAIL' $B/gate-r6a-check.log | head -4 | tr '\n' ' ')"
SEED_BUILD=$B zsh $R/seed/tests/r5b/gate-r5b.sh --extra > $B/gate-r6a-r5b.log 2>&1 && row PASS "R5B-X $(tail -1 $B/gate-r6a-r5b.log)" \
  || row FAIL "R5B-X $(grep -E '^FAIL' $B/gate-r6a-r5b.log | head -3 | tr '\n' ' ')"
echo "gate-r6a: $([ $fails -eq 0 ] && echo READY || echo "NOT READY ($fails failed)") (load $(uptime | sed 's/.*averages: //'))"
[ $fails -eq 0 ]
