(ns kotoba.compiler.test-runner
  (:require [clojure.test :as t]
            [kotoba.compiler.atomic-output-test]
            [kotoba.compiler.aiueos-target-test]
            [kotoba.compiler.accelerator-test]
            [kotoba.compiler.application-syntax-test]
            [kotoba.compiler.cli-test]
            [kotoba.compiler.core-test]
            [kotoba.compiler.coverage-test]
            [kotoba.compiler.coverage-evidence-test]
            [kotoba.compiler.bounded-edn-test]
            [kotoba.compiler.cache-test]
            [kotoba.compiler.compact-graph-value-test]
            [kotoba.compiler.document-value-test]
            [kotoba.compiler.document-ui-render-test]
            [kotoba.compiler.document-digest-style-test]
            [kotoba.compiler.document-sha256-test]
            [kotoba.compiler.document-dom-reconcile-test]
            [kotoba.compiler.document-dual-renderer-test]
            [kotoba.compiler.document-roundtrip-test]
            [kotoba.compiler.document-perf-workload-test]
            [kotoba.compiler.recursive-tree-value-test]
            [kotoba.compiler.recursive-tree-update-test]
            [kotoba.compiler.plan-test]
            [kotoba.compiler.string-operation-test]
            [kotoba.compiler.frontend-fuzz-test]
            [kotoba.compiler.frontend-assert-test]
            [kotoba.compiler.frontend-equality-diagnostic-test]
            [kotoba.compiler.product-value-abi-v1-test]
            [kotoba.compiler.pure-product-profile-test]
            [kotoba.compiler.lang-conformance-test]
            [kotoba.compiler.error-code-contract-test]
            [kotoba.compiler.frontend-condp-test]
            [kotoba.compiler.frontend-doseq-test]
            [kotoba.compiler.frontend-dotimes-test]
            [kotoba.compiler.f64-value-test]
            [kotoba.compiler.f32-value-test]
            [kotoba.compiler.frontend-limits-test]
            [kotoba.compiler.frontend-multimethod-test]
            [kotoba.compiler.frontend-extensions-test]
            [kotoba.compiler.frontend-destructuring-loop-test]
            [kotoba.compiler.frontend-named-capability-test]
            [kotoba.compiler.linear-resource-test]
            [kotoba.compiler.backend-cljs-test]
            [kotoba.compiler.backend-qualification-test]
            [kotoba.compiler.host-profile-test]
            [kotoba.compiler.component-artifact-test]
            [kotoba.compiler.component-composition-test]
            [kotoba.compiler.component-admission-test]
            [kotoba.compiler.i64-bitwise-test]
            [kotoba.compiler.effectful-component-source-test]
            [kotoba.compiler.ios-aot-test]
            [kotoba.compiler.interface-test]
            [kotoba.compiler.native-executor-test]
            [kotoba.compiler.admission-test]
            [kotoba.compiler.guest-grammar-conformance-test]
            [kotoba.compiler.property-test]
            [kotoba.compiler.project-test]
            [kotoba.compiler.receipt-test]
            [kotoba.compiler.release-test]
            [kotoba.compiler.security-fuzz-test]
            [kotoba.compiler.signing-test]
            [kotoba.compiler.source-path-test]
            [kotoba.compiler.typed-value-conformance-test]
            [kotoba.compiler.typed-capability-test]
            [kotoba.compiler.reference-runtime-test]
            [kotoba.compiler.state-provider-test]
            [kotoba.compiler.ui-provider-test]
            [kotoba.compiler.http-provider-test]
            [kotoba.compiler.http-transport-test]
            [kotoba.compiler.llm-provider-test]
            [kotoba.compiler.llm-transport-test]
            [kotoba.compiler.object-provider-test]
            [kotoba.compiler.object-product-vertical-test]
            [kotoba.compiler.object-transport-test]
            [kotoba.compiler.http-ingress-provider-test]
            [kotoba.compiler.storage-provider-test]
            [kotoba.compiler.storage-transport-test]
            [kotoba.compiler.clock-provider-test]
            [kotoba.compiler.clock-transport-test]
            [kotoba.compiler.log-provider-test]
            [kotoba.compiler.provider-conformance-test]
            [kotoba.compiler.wasm-typed-test]
            [kotoba.compiler.verifier-profile-test]))

(defn -main [& _]
  (let [{:keys [fail error]} (t/run-tests 'kotoba.compiler.atomic-output-test
                                          'kotoba.compiler.aiueos-target-test
                                          'kotoba.compiler.accelerator-test
                                          'kotoba.compiler.application-syntax-test
                                          'kotoba.compiler.cli-test
                                          'kotoba.compiler.core-test
                                          'kotoba.compiler.coverage-test
                                          'kotoba.compiler.coverage-evidence-test
                                          'kotoba.compiler.bounded-edn-test
                                          'kotoba.compiler.cache-test
                                          'kotoba.compiler.compact-graph-value-test
                                          'kotoba.compiler.document-value-test
                                          'kotoba.compiler.document-ui-render-test
                                          'kotoba.compiler.document-digest-style-test
                                          'kotoba.compiler.document-sha256-test
                                          'kotoba.compiler.document-dom-reconcile-test
                                          'kotoba.compiler.document-dual-renderer-test
                                          'kotoba.compiler.document-roundtrip-test
                                          'kotoba.compiler.document-perf-workload-test
                                          'kotoba.compiler.recursive-tree-value-test
                                          'kotoba.compiler.recursive-tree-update-test
                                          'kotoba.compiler.plan-test
                                          'kotoba.compiler.string-operation-test
                                          'kotoba.compiler.frontend-fuzz-test
                                          'kotoba.compiler.frontend-assert-test
                                          'kotoba.compiler.frontend-equality-diagnostic-test
                                          'kotoba.compiler.product-value-abi-v1-test
                                          'kotoba.compiler.pure-product-profile-test
                                          'kotoba.compiler.lang-conformance-test
                                          'kotoba.compiler.error-code-contract-test
                                          'kotoba.compiler.frontend-condp-test
                                          'kotoba.compiler.frontend-doseq-test
                                          'kotoba.compiler.frontend-dotimes-test
                                          'kotoba.compiler.f64-value-test
                                          'kotoba.compiler.f32-value-test
                                          'kotoba.compiler.frontend-limits-test
                                          'kotoba.compiler.frontend-multimethod-test
                                          'kotoba.compiler.frontend-extensions-test
                                          'kotoba.compiler.frontend-destructuring-loop-test
                                          'kotoba.compiler.frontend-named-capability-test
                                          'kotoba.compiler.linear-resource-test
                                          'kotoba.compiler.backend-cljs-test
                                          'kotoba.compiler.backend-qualification-test
                                          'kotoba.compiler.host-profile-test
                                          'kotoba.compiler.component-artifact-test
                                          'kotoba.compiler.component-composition-test
                                          'kotoba.compiler.component-admission-test
                                          'kotoba.compiler.i64-bitwise-test
                                          'kotoba.compiler.effectful-component-source-test
                                          'kotoba.compiler.ios-aot-test
                                          'kotoba.compiler.interface-test
                                          'kotoba.compiler.admission-test
                                          'kotoba.compiler.guest-grammar-conformance-test
                                          'kotoba.compiler.signing-test
                                          'kotoba.compiler.source-path-test
                                          'kotoba.compiler.typed-value-conformance-test
                                          'kotoba.compiler.typed-capability-test
                                          'kotoba.compiler.reference-runtime-test
                                          'kotoba.compiler.state-provider-test
                                          'kotoba.compiler.ui-provider-test
                                          'kotoba.compiler.http-provider-test
                                          'kotoba.compiler.http-transport-test
                                          'kotoba.compiler.llm-provider-test
                                          'kotoba.compiler.llm-transport-test
                                          'kotoba.compiler.object-provider-test
                                          'kotoba.compiler.object-product-vertical-test
                                          'kotoba.compiler.object-transport-test
                                          'kotoba.compiler.http-ingress-provider-test
                                          'kotoba.compiler.storage-provider-test
                                          'kotoba.compiler.storage-transport-test
                                          'kotoba.compiler.clock-provider-test
                                          'kotoba.compiler.clock-transport-test
                                          'kotoba.compiler.log-provider-test
                                          'kotoba.compiler.provider-conformance-test
                                          'kotoba.compiler.wasm-typed-test
                                          'kotoba.compiler.native-executor-test
                                          'kotoba.compiler.receipt-test
                                          'kotoba.compiler.release-test
                                          'kotoba.compiler.security-fuzz-test
                                          'kotoba.compiler.verifier-profile-test
                                          'kotoba.compiler.project-test
                                          'kotoba.compiler.property-test)]
    (System/exit (if (pos? (+ fail error)) 1 0))))
