;; Desugar differential (selfhost S3, desugar half): the frontend's HOST `desugar-expr` vs the Kotoba-route port of the
;; same function (the :kotoba view of kotoba-sema's frontend.cljk, generated by ds-gen.sh, run on the KIR interpreter).
;;
;; CORPUS: every `(ns ...)` program embedded as a string in kotoba-sema's test sources (DS_TESTS, a directory) is read with
;; the frontend's own reader; every list form anywhere inside a top-level form is a case (deduplicated, bounded by
;; DS_MAX per program). The function names of the program are the env's `functions` (heads that are ordinary calls).
;; HOST side: `desugar-expr` with `*synthetic-counter*` bound to a fresh volatile; its answer is the printed form, or
;; "ERR <message>" for a refusal. KOTOBA side: the guest compares its own answer with the host's printed form by
;; `form/eq` (inside the guest: no printer agreement is needed) and answers OK / DIFF <form> / ERR <msg> / UNPORTED <what>.
;; UNPORTED cases are counted (they are the coverage figure) and never compared.
;;
;; Env: KROOTS (src roots + lang/compat), DS_GUEST (generated module), DS_TESTS (test dir), DS_MAX, DS_SHOW.
(ns ds-diff
  (:require ["node:fs" :as fs]
            [clojure.string :as str]
            [clojure.edn :as edn]
            [kotoba.sema :as sema]
            [kotoba.kir :as kir]
            [kotoba.compiler.project :as project]
            [kotoba.compiler.project-files :as pf]
            [kotoba.compiler.frontend :as fe]
            [kotoba.compiler.frontend.base :as fe-base]
            [kotoba.compiler.frontend.desugar :as fe-ds]))

(set! *print-namespace-maps* false)
(def env js/process.env)
(def roots (vec (str/split (.-KROOTS env) #":")))
(def guest-path (.-DS_GUEST env))
(def tests-dir (.-DS_TESTS env))
(def max-per-program (if-let [v (.-DS_MAX env)] (js/parseInt v) 400))
(def show (if-let [v (.-DS_SHOW env)] (js/parseInt v) 12))

(defn fe-var [sym] @(resolve (symbol "kotoba.compiler.frontend" (name sym))))
(def host-desugar (fe-var 'desugar-expr))

(defn norm [s] (-> s (str/replace #"#object\[BigInt (-?\d+)\]" "$1") (str/replace #"(\d+)n\b" "$1")))
(defn edn-of [x] (norm (pr-str x)))

;; ---- corpus ----------------------------------------------------------------------------------

(defn files-under [dir]
  (mapcat (fn [n]
            (let [p (str dir "/" n)]
              (if (.isDirectory (fs/statSync p)) (files-under p) [p])))
          (js->clj (fs/readdirSync dir))))

(defn programs-in [text]
  ;; string literals that begin a program: "(ns ...", with \" and \\ escapes
  (for [lit (re-seq #"\"\(ns (?:[^\"\\]|\\.)*\"" text)
        :let [s (try (edn/read-string lit) (catch :default _ nil))]
        :when (string? s)]
    s))

(defn sub-seqs [form]
  (let [acc (atom [])]
    (letfn [(walk [x]
              (cond
                (seq? x) (do (swap! acc conj x) (run! walk x))
                (or (vector? x) (set? x)) (run! walk x)
                (map? x) (run! walk (mapcat identity x))))]
      (walk form))
    @acc))

(defn defn-names [forms]
  (set (for [f forms :when (and (seq? f) (contains? '#{defn defn-} (first f)) (symbol? (second f)))] (second f))))

(defn program-cases [src]
  (try
    (let [forms (vec (fe/read-forms src))
          names (defn-names forms)
          bodies (remove #(and (seq? %) (contains? '#{ns defn defn- def defrecord defprotocol} (first %))) forms)
          subs (->> (mapcat (fn [f]
                              (if (and (seq? f) (contains? '#{defn defn-} (first f)))
                                (mapcat sub-seqs (drop 2 f))
                                (sub-seqs f)))
                            forms)
                    (remove #(and (seq? %) (contains? '#{defn defn- ns def defrecord defprotocol letfn binding for} (first %))))
                    (take max-per-program))]
      (for [s subs] [names s]))
    (catch :default _ [])))

(defn corpus []
  (let [files (filter #(re-find #"\.(cljk|clj|cljc)$" %) (files-under tests-dir))
        tests (distinct (mapcat (fn [f] (programs-in (str (fs/readFileSync f "utf8")))) files))
        ;; DS_EXTRA: colon-separated directories of whole `.kotoba` programs
        extra-files (mapcat (fn [d] (filter #(re-find #"\.kotoba$" %) (files-under d)))
                            (remove str/blank? (str/split (or (.-DS_EXTRA env) "") #":")))
        extra (map (fn [f] (str (fs/readFileSync f "utf8"))) extra-files)
        all (distinct (mapcat program-cases (concat tests extra)))
        total (if-let [v (.-DS_TOTAL env)] (js/parseInt v) 1000000)
        n (count all)]
    (if (<= n total)
      all
      ;; an even sample, so every program keeps some share
      (let [step (/ n total)]
        (vec (map #(nth (vec all) (int (* % step))) (range total)))))))

;; ---- golden host outputs ------------------------------------------------------------------------------------
;; WALL_GOLDEN names a file holding the HOST side (cases and the host's answers) of an earlier identical run: used when it
;; exists, written when it does not. golden-cache.sh keys it by (host function CID, case-set CID), so a rerun after a
;; change that touches only the Kotoba side computes the guest side alone. Unset: nothing changes.
(defn golden [thunk]
  (let [p (.-WALL_GOLDEN env)]
    (if (and p (fs/existsSync p) (pos? (.-size (fs/statSync p))))
      (do (println "golden host outputs reused from" p) (edn/read-string (str (fs/readFileSync p "utf8"))))
      (let [t0 (js/Date.now) v (thunk)]
        (println "host side computed in" (- (js/Date.now) t0) "ms")
        (when p (fs/writeFileSync p (pr-str v))) v))))

;; ---- host ------------------------------------------------------------------------------------

(defn host-answer [names form]
  ;; the answer is [form helpers shapes lambdas dispatchers uses-apply]: what the host registers on the side while lowering
  ;; (`*pending-loop-helpers*`, `*loop-helper-shapes*`, `*pending-lambdas*`, `*required-closure-dispatchers*`, `*uses-apply?*`)
  ;; is part of what the port must reproduce
  (try
    (let [helpers (atom [])
          shapes (volatile! {})
          lambdas (atom [])
          dispatchers (volatile! #{})
          uses-apply (volatile! false)
          uses-lazy (volatile! false)
          r (binding [fe-base/*synthetic-counter* (volatile! 0)
                      fe-ds/*loop-counter* (volatile! 0)
                      fe-ds/*lambda-counter* (volatile! 0)
                      fe-ds/*pending-loop-helpers* helpers
                      fe-ds/*loop-helper-shapes* shapes
                      fe-ds/*pending-lambdas* lambdas
                      fe-ds/*required-closure-dispatchers* dispatchers
                      fe-ds/*uses-apply?* uses-apply
                      fe-ds/*uses-lazy?* uses-lazy
                      fe-ds/*function-arities* (into {} (map (fn [n] [n #{0 1 2 3 4}])) names)]
              (host-desugar form))]
      [:ok (edn-of r) (str/join " " [(edn-of @helpers) (edn-of @shapes) (edn-of @lambdas) (edn-of @dispatchers) (edn-of @uses-apply) (edn-of @uses-lazy)])])
    (catch :default e [:err (ex-message e)])))

;; ---- guest -----------------------------------------------------------------------------------

;; ---- the Kotoba side as COMPILED code (guest-run.sh), the interpreter only on request or when no compiler admits the guest ----
;; Default mode is native (amu aarch64 kexe under tools/kexe_loader.c), then wasm under node (BOOTSTRAP), then the KIR
;; interpreter (BOOTSTRAP). `--interp` (or GUEST_MODE=interp) skips the compilers. The refusal that sent a guest down a
;; mode is printed (and cached by guest-run.sh), so the gap list stays visible. docs/selfhost-native-gaps-20261001.md.
(def ^:private child-process (js/require "node:child_process"))
(def ^:private here (.-SELFHOST_WALL_DIR js/process.env))
(def ^:private interp-only? (or (some #{"--interp"} (js->clj (.-argv js/process))) (= "interp" (.-GUEST_MODE js/process.env))))
(defn- guest-run [args input]
  (.spawnSync child-process "zsh" (clj->js (into [(str here "/guest-run.sh")] args))
              #js {:input input :encoding "utf8" :maxBuffer (* 512 1024 1024)
                   :env (js/Object.assign #js {} js/process.env #js {:GUEST_NOFRESH (if (= "--resolve" (first args)) "" "1")})}))
(defn resolve-guest-mode
  "native | wasm | interp for the guest file and entry (compiles on first use; the answer is cached)."
  [path entry]
  (if interp-only?
    "interp"
    (let [r (guest-run ["--resolve" path entry] "")]
      (when-let [e (not-empty (.-stderr r))] (js/process.stderr.write e))
      (let [m (str/trim (str (.-stdout r)))]
        (if (#{"native" "wasm"} m) m "interp")))))
(defn run-compiled
  "Run the compiled guest on TEXT (one batch); a trap or refusal throws, like the interpreter's."
  [mode path entry text]
  (let [r (guest-run [(str "--" mode "-only") (str "--") path entry] text)]
    (when-not (zero? (.-status r))
      (throw (ex-info (str "guest trap (" mode "): " (subs (str (.-stderr r)) 0 (min 300 (count (str (.-stderr r)))))) {})))
    (.-stdout r)))

(defn- interp-load []
  (let [graph (pf/load-closed-graph guest-path roots)
        linked (project/link-source (:sources graph) (:root graph))
        hir (sema/analyze (:source linked) {:admit-linked-synthetics? true})]
    (kir/lower hir)))

(defn load-guest []
  (let [m (resolve-guest-mode guest-path "ds-run")]
    (println "guest mode:" m (if (= m "interp") "(BOOTSTRAP: KIR interpreter on nbb)" ""))
    (if (= m "interp") {:mode "interp" :lowered (interp-load)} {:mode m})))

(defn run-guest [g text]
  (if (= "interp" (:mode g))
    (kir/execute (:lowered g) 'ds-run [text] {:fuel 100000000000 :frames 100000 :cells 1000000000 :bytes 1000000000})
    (run-compiled (:mode g) guest-path "ds-run" text)))

(defn ascii? [s] (not (re-find #"[^\x09\x0a\x20-\x7e]" s)))

(defn batches-by-size
  "Split ROWS into batches of at most N lines and MAX-BYTES bytes of case text (the guest's string limit is 64 KiB,
  and its answer is text too). A single case bigger than MAX-BYTES is dropped."
  [rows n max-bytes]
  (loop [rows (remove #(> (count (:line %)) max-bytes) rows) cur [] size 0 out []]
    (if-let [r (first rows)]
      (let [sz (inc (count (:line r)))]
        (if (or (>= (count cur) n) (> (+ size sz) max-bytes))
          (recur rows [] 0 (conj out cur))
          (recur (rest rows) (conj cur r) (+ size sz) out)))
      (if (seq cur) (conj out cur) out))))

(defn -probe [path]
  ;; run the guest on the case lines of a file and print its answers (debugging aid)
  (let [text (str (fs/readFileSync path "utf8"))
        res (run-guest (load-guest) text)]
    (println (if (map? res) (or (:value res) (pr-str res)) res))))

(defn -main []
  (let [{:keys [ncs rows]}
        (golden
         (fn []
           (let [cs (corpus)
                 _ (println "corpus forms:" (count cs))
                 rows (vec (for [[names form] cs
                                 :let [[k v side] (host-answer names form)
                                       line  (str "[" (edn-of (into {} (map (fn [n] [n #{0 1 2 3 4}])) names)) " false " (edn-of form) " "
                                                 (if (= k :ok) v "nil") " " (if (= k :ok) side "[] {} [] #{} false false") "]")]
                                 :when (and (not (str/includes? line "\n")) (ascii? line)
                                            (not (str/includes? line "#object")) (not (str/includes? line "#<")))]
                             {:line line :host (if (= k :ok) "OK" (str "ERR " v)) :form (edn-of form)}))]
             {:ncs (count cs) :rows rows})))
        cs (if (.-DS_WHY env) (corpus) [])
        _ (println "cases:" (count rows) "of" ncs "forms; loop-ish:" (count (filter #(re-find #"^\((loop|dotimes|doseq|fn) " (:form %)) rows)) "linking guest ...")
        _ (when (.-DS_WHY env)
            (doseq [[names form] (take 400 cs)
                    :let [[k v side] (host-answer names form)
                          line (str "[" (edn-of form) " " (if (= k :ok) v "nil") " " side "]")]
                    :when (not (and (not (str/includes? line "\n")) (ascii? line)
                                    (not (str/includes? line "#object")) (not (str/includes? line "#<"))))]
              (println "DROPPED" (subs line 0 (min 300 (count line))))))
        lowered (load-guest)
        batch (if-let [v (.-DS_BATCH env)] (js/parseInt v) 100)
        out (atom [])]
    (doseq [part (batches-by-size rows batch 30000)]
      (println "batch of" (count part) "...")
      (letfn [(run-part [part]
                (let [text (str (str/join "\n" (map :line part)) "\n")
                      res (run-guest lowered text)
                      res (if (map? res) (or (:value res) (throw (ex-info "guest trap" {:out (pr-str res)}))) res)
                      lines (str/split res #"\n" -1)]
                  (doseq [[r g] (map vector part lines)] (swap! out conj (assoc r :guest g)))))]
        (try (run-part part)
             (catch :default e
               ;; a trap inside the guest loses the whole batch: rerun case by case so the cases that trap are named
               (println "  batch trapped:" (ex-message e) "-- rerunning case by case")
               (doseq [r part]
                 (try (run-part [r])
                      (catch :default e2
                        (swap! out conj (assoc r :guest (str "TRAP " (ex-message e2))))))))))) 
    (let [rows @out
          unported (filter #(str/starts-with? (:guest %) "UNPORTED") rows)
          compared (remove #(str/starts-with? (:guest %) "UNPORTED") rows)
          bad (remove #(= (:host %) (:guest %)) compared)]
      (println "compared:" (count compared) "agree:" (- (count compared) (count bad)) "disagree:" (count bad)
               "unported (not compared):" (count unported))
      (doseq [[what n] (take 25 (sort-by (comp - val) (frequencies (map #(subs (:guest %) 9) unported))))]
        (println "  unported" n what)
        (when (.-DS_UNPORTED env)
          (doseq [r (take 3 (filter #(= what (subs (:guest %) 9)) unported))]
            (println "      e.g." (subs (:form r) 0 (min 160 (count (:form r))))))))
      (doseq [r (take show bad)]
        (println "DISAGREE" (subs (:form r) 0 (min 240 (count (:form r)))) "\n  host :" (:host r) "\n  guest:" (:guest r)))
      (js/process.exit (if (seq bad) 1 0)))))

(if-let [p (.-DS_LINES env)] (-probe p) (-main))
