#!/usr/bin/env python3
"""seed/amu-main/missing.py <selfbuild-work-dir> -- the exact list of what each amu command entry is missing on the source
route (agent MAINS, 2026-10-04). BOOTSTRAP-TOOL (python3, reads files only).

Input: a scripts/seed/selfbuild.sh work dir (r6/r6-scan.tsv: the seed's verdict per module of the image's 138-module reach
set; r6/order.txt: each module's requires). Output (stdout, tab separated, written to seed/amu-main/missing.tsv by the
caller): one row per module NOT compiled by the seed in the closure each command needs:

  command  need  module  status  seed-verdict  blocked-by

need: the module whose closure the command needs:
  check    kotoba.compiler.frontend.analyze   (what amu.check calls on the KIR route, seed/amu-front/check.cljk)
  check    kotoba.compiler.nbb.check-cli      (the product entry: its closure is check-driver + cli-support)
  compile  kotoba.compiler.nbb.aarch64-cli    (stage-0's compile: frontend, kotoba.kir, machine_ir, aarch64, kexe/v1)
  refactor kotoba.compiler.refactor.*         (the library the :default arm of refactor-cli/run requires; its Kotoba arm
                                               is a stub that throws "not available")
status: REFUSED (a wall: the seed refuses the module itself) or BLOCKED (a require is not compiled); OK modules are not listed.
A last block 'summary' gives per command: closure size, OK, REFUSED, BLOCKED, and the walls.
"""
import os, sys

W = sys.argv[1]
rows = [l.rstrip('\n').split('\t') for l in open(os.path.join(W, 'r6', 'r6-scan.tsv')) if l.strip() and not l.startswith('#')]
st = {r[0]: r for r in rows if len(r) > 1}
deps = {}
for l in open(os.path.join(W, 'r6', 'order.txt')):
    f = l.split()
    deps[f[0]] = [d for d in f[2:] if d != '-']


def closure(ms):
    seen, todo = set(ms), list(ms)
    while todo:
        x = todo.pop()
        for d in deps.get(x, []):
            if d not in seen:
                seen.add(d); todo.append(d)
    return seen


REFACTOR = sorted(m for m in st if m.startswith('kotoba.compiler.refactor.'))
NEEDS = [('check', ['kotoba.compiler.frontend.analyze'], 'kotoba.compiler.frontend.analyze'),
         ('check', ['kotoba.compiler.nbb.check-cli'], 'kotoba.compiler.nbb.check-cli'),
         ('compile', ['kotoba.compiler.nbb.aarch64-cli'], 'kotoba.compiler.nbb.aarch64-cli'),
         ('refactor', REFACTOR, 'kotoba.compiler.refactor.*')]
print('# seed/amu-main/missing.tsv -- generated by seed/amu-main/missing.py from %s (%s)' % (
    W, open(os.path.join(W, 'provenance.txt')).readline().strip() if os.path.exists(os.path.join(W, 'provenance.txt')) else '?'))
print('command\tneed\tmodule\tstatus\tseed-verdict\tblocked-by')
summary = []
for cmd, roots, label in NEEDS:
    c = closure([r for r in roots if r in st])
    walls = []
    for m in sorted(c):
        r = st.get(m)
        if not r or r[1] == 'OK':
            continue
        v = (r[3] + ' ' + r[4]).strip() if r[1] in ('REFUSED', 'TRAP') else '-'
        b = r[4].replace('requires ', '') if r[1] == 'BLOCKED' else '-'
        if r[1] in ('REFUSED', 'TRAP'):
            walls.append(m)
        print('\t'.join([cmd, label, m, r[1], v[:160], b]))
    n = lambda s: sum(1 for m in c if st.get(m, [m, '?'])[1] == s)
    summary.append('%s\t%s\tclosure %d\tOK %d\tREFUSED %d\tBLOCKED %d\twalls %s' % (cmd, label, len(c), n('OK'), n('REFUSED') + n('TRAP'),
                                                                               n('BLOCKED'), ' '.join(walls) or '-'))
print('# summary')
for s in summary:
    print('# ' + s)
