#!/bin/zsh
# scripts/seed/gen-ns.sh [--check] -- regenerate the constant block of seed/00-ns.kotoba and the 00-ns unit test
# (seed/tests/unit/00-ns_t.kotoba, seed/tests/unit/00-ns.expected) from the contract files seed/MEMORY-MAP,
# seed/HEADS and seed/SIR: every `[:c NAME VALUE` occurrence, in file order. BOOTSTRAP-TOOL (zsh + awk).
# --check: regenerate into a temp dir and fail when the committed files differ (no writes).
emulate -L zsh
setopt pipefail
R=$(cd "$(dirname "$0")/../.." && pwd)
out=$R; check=0
if [ "$1" = "--check" ]; then check=1; out=$(mktemp -d /tmp/seed-gen-ns.XXXXXX); mkdir -p $out/seed/tests/unit; fi

consts=$(grep -ohE '\[:c [A-Z][A-Z0-9-]* -?[0-9]+' $R/seed/MEMORY-MAP $R/seed/HEADS $R/seed/SIR | awk '{print $2, $3}')
dups=$(echo "$consts" | awk '{print $1}' | sort | uniq -d)
[ -z "$dups" ] || { echo "gen-ns: duplicate constant names: $dups" >&2; exit 1; }
n=$(echo "$consts" | wc -l | tr -d ' ')

{
  cat <<'EOF'
(ns seed (:export [main]))

;; seed/00-ns.kotoba -- the namespace of the seed compiler (R0), its contract constants and the command entry.
;; Owner: contracts. The unity build puts this file first (seed/MANIFEST). Everything between the GENERATED
;; markers is written by scripts/seed/gen-ns.sh from seed/MEMORY-MAP, seed/HEADS and seed/SIR: edit those files,
;; never the block. `main` is the only public function; `seed-main` comes from 99-entry (or from a unit test).

;; BEGIN GENERATED CONSTANTS
EOF
  echo "$consts" | awk '{printf "(def %s %s)\n", $1, $2}'
  cat <<'EOF'
;; END GENERATED CONSTANTS

(defn main [] :i64 (seed-main))
EOF
} > $out/seed/00-ns.kotoba

# the unit test: print "NAME VALUE" for every constant, as compiled
{
  echo ';; seed/tests/unit/00-ns_t.kotoba -- GENERATED by scripts/seed/gen-ns.sh. Prints every contract constant as'
  echo ';; compiled, so unit.sh 00-ns proves seed/00-ns.kotoba agrees with MEMORY-MAP/HEADS/SIR.'
  cat <<'EOF'
(defn- t-digit [d :i64] :string
  (cond (= d 0) "0" (= d 1) "1" (= d 2) "2" (= d 3) "3" (= d 4) "4"
        (= d 5) "5" (= d 6) "6" (= d 7) "7" (= d 8) "8" :else "9"))
(defn- t-dec-pos [n :i64] :string
  (if (< n 10) (t-digit n)
    (string-concat (t-dec-pos (quot n 10)) (t-digit (- n (* 10 (quot n 10)))))))
(defn- t-dec [n :i64] :string
  (if (< n 0) (string-concat "-" (t-dec-pos (- 0 n))) (t-dec-pos n)))
(defn- t-line [name :string v :i64] :i64
  (let [o (typed-cap-call :io/write :string :string (string-concat name (string-concat " " (string-concat (t-dec v) "\n"))))]
    0))
EOF
  echo "$consts" | awk -v N=$n '
    { name[NR-1]=$1 }
    END {
      C=40
      for (c = 0; c * C < N; c++) {
        printf "(defn- t-chunk%d [k :i64] :i64\n  (cond\n", c
        for (i = c * C; i < (c + 1) * C && i < N; i++)
          printf "    (= k %d) (t-line \"%s\" %s)\n", i, name[i], name[i]
        printf "    :else 0))\n"
      }
      printf "(defn- t-one [k :i64] :i64\n  (cond\n"
      for (c = 0; c * C < N; c++) printf "    (< k %d) (t-chunk%d k)\n", (c + 1) * C, c
      printf "    :else 0))\n"
      printf "(defn- t-all [k :i64] :i64\n  (if (= k %d) 0\n    (let [r (t-one k)] (t-all (+ k 1)))))\n", N
      printf "(defn- seed-main [] :i64\n  (let [o (typed-cap-call :io/write :string :string \"00-ns constants %d\\n\")\n        r (t-all 0)]\n    r))\n", N
    }'
} > $out/seed/tests/unit/00-ns_t.kotoba

{ echo "00-ns constants $n"; echo "$consts"; echo "exit=0"; } > $out/seed/tests/unit/00-ns.expected

if [ $check -eq 1 ]; then
  rc=0
  for f in seed/00-ns.kotoba seed/tests/unit/00-ns_t.kotoba seed/tests/unit/00-ns.expected; do
    cmp -s $out/$f $R/$f || { echo "gen-ns --check: $f is stale (run scripts/seed/gen-ns.sh)"; rc=1; }
  done
  rm -rf $out; exit $rc
fi
echo "gen-ns: $n constants -> seed/00-ns.kotoba, seed/tests/unit/00-ns_t.kotoba, seed/tests/unit/00-ns.expected"
