#!/usr/bin/env python3
# scripts/seed/gen-50-out-test.py -- regenerates seed/tests/unit/50-out_t.kotoba (BOOTSTRAP-TOOL, test generator only).
# The expected container is built here in Python from the kseed/v1 description (seed/SIR :kseed), independently of 50-out.
# Run: python3 scripts/seed/gen-50-out-test.py ; then scripts/seed/unit.sh 50-out
import os
def wrap(x):
    x &= (1 << 64) - 1
    return x - (1 << 64) if x >> 63 else x
def hsh(bs):
    h = 7
    for b in bs: h = wrap(h * 1000003 + b)
    return h
NAMES = "alpha-beta-main"            # the source string S: alpha 0..5, beta 6..10, main 11..15
SYMS = {1: (0, 5), 2: (11, 15), 3: (6, 10)}   # sym index -> span
FNS = {1: dict(sym=1, code=1, np=2, ex=1), 2: dict(sym=3, code=10, np=1, ex=0), 3: dict(sym=2, code=21, np=0, ex=1)}
NW = 40
CODE = [((i * 2654435761) ^ 0xD2800000) & 0xFFFFFFFF for i in range(1, NW + 1)]
CODE[4] = 0xFFFFFFFF; CODE[5] = 0; CODE[6] = 0x80000000
LITS = {1: b"hello", 2: b"abcdefgh", 3: b"end"}
ncode = NW + 1
cb = NW * 4
poff = (cb + 7) // 8 * 8
pos = {}; cur = poff
for k in sorted(LITS): pos[k] = cur; cur = (cur + len(LITS[k]) + 7) // 8 * 8
total = pos[3] + len(LITS[3])
code = bytearray()
for w in CODE: code += w.to_bytes(4, "little")
code += bytes(poff - len(code))
pool = bytearray(code)
for k in sorted(LITS):
    pool += bytes(pos[k] - len(pool)); pool += LITS[k]
assert len(pool) == total
exports = [(f, (FNS[f]["code"] - 1) * 4, FNS[f]["np"]) for f in sorted(FNS) if FNS[f]["ex"]]
hdr = b"KSEED1 %d %d\n" % (total, len(exports))
for f, off, ar in exports:
    a, b = SYMS[FNS[f]["sym"]]
    hdr += NAMES[a:b].encode() + b" %d %d\n" % (off, ar)
hdr += b"\n"
CONT = hdr + bytes(pool)
CS = len(hdr)

L = []   # lines of the test
def W(addr, val): return (addr, val)
def CODEA(i): return f"(+ MM-CODE-BASE {i})"
def FNF(k, f): return f"(+ (+ MM-FN-BASE (* {k} MM-FN-W)) {f})"
def SYMF(k, f): return f"(+ (+ MM-SYM-BASE (* {k} MM-SYM-W)) {f})"
def LITF(k, f): return f"(+ (+ MM-LIT-BASE (* {k} MM-LIT-W)) {f})"
def LITB(i): return f"(+ MM-LITB-BASE {i})"
def setup(code_words=CODE, fills=True):
    w = [("MM-CODE-N", len(code_words) + 1), ("MM-FIX-N", 1), ("MM-LIT-N", 4), ("MM-FN-N", 4), ("MM-EXP-N", 1), ("MM-LABEL-N", 1),
         ("MM-ERR", 0), ("MM-ERR-POS", 0), ("MM-ERR-N", 0), ("MM-OUT-N", 1)]
    for i, c in enumerate(code_words, 1): w.append((CODEA(i), c))
    for s, (a, b) in SYMS.items(): w += [(SYMF(s, "SF-START"), a), (SYMF(s, "SF-END"), b)]
    for f, d in FNS.items(): w += [(FNF(f, "FF-SYM"), d["sym"]), (FNF(f, "FF-CODE"), d["code"]), (FNF(f, "FF-NPARAMS"), d["np"]), (FNF(f, "FF-EXPORT"), d["ex"])]
    bi = 1
    for k in sorted(LITS):
        w += [(LITF(k, "LF-B"), bi), (LITF(k, "LF-LEN"), len(LITS[k]))]
        for j, c in enumerate(LITS[k]): w.append((LITB(bi + j), c))
        bi += len(LITS[k])
    return w

scen = []   # (name, writes, post-run call, reads/checks) ; every scenario starts from the same M threaded through
# s1: layout + build + checks on the container, then parse round trips
checks = [("build ERR", "(vector-at M2 MM-ERR)", 0), ("build total", "(vector-at M2 MM-R0)", len(CONT)),
          ("build OUT-N", "(vector-at M2 MM-OUT-N)", len(CONT) + 1),
          ("layout CODE-BYTES", "(vector-at M1 MM-CODE-BYTES)", total), ("layout EXP-N", "(vector-at M1 MM-EXP-N)", 1 + len(exports)),
          ("hash", "(t-hash M2 (+ MM-OUT-BASE 1) %d 7)" % len(CONT), hsh(CONT)), ("first byte K", "(vector-at M2 (+ MM-OUT-BASE 1))", CONT[0]),
          ("last byte", "(vector-at M2 (+ MM-OUT-BASE %d))" % len(CONT), CONT[-1]), ("header newline", "(vector-at M2 (+ MM-OUT-BASE %d))" % CS, 10),
          ("code word 5 byte 0", "(vector-at M2 (+ MM-OUT-BASE %d))" % (CS + 4 * 4 + 1), CONT[CS + 16]),
          ("code word 5 byte 3", "(vector-at M2 (+ MM-OUT-BASE %d))" % (CS + 4 * 4 + 4), CONT[CS + 19]),
          ("pad byte", "(vector-at M2 (+ MM-OUT-BASE %d))" % (CS + cb + 1), CONT[CS + cb]),
          ("lit2 first byte", "(vector-at M2 (+ MM-OUT-BASE %d))" % (CS + pos[2] + 1), CONT[CS + pos[2]]),
          ("lit3 last byte", "(vector-at M2 (+ MM-OUT-BASE %d))" % (CS + total), CONT[CS + total - 1])]
scen.append(("s1", setup(), checks))

def sname(n): return n.replace("_", "-")
out = []
out.append(''';; seed/tests/unit/50-out_t.kotoba -- GENERATED by scripts/seed/gen-50-out-test.py. Unit test of 50-out: the container
;; is built from synthetic tables (after 42-layout) and compared with a container computed in Python.
;; deps: 42-layout
(defn- t-digit [d :i64] :string
  (cond (= d 0) "0" (= d 1) "1" (= d 2) "2" (= d 3) "3" (= d 4) "4"
        (= d 5) "5" (= d 6) "6" (= d 7) "7" (= d 8) "8" :else "9"))
(defn- t-dec-pos [n :i64] :string
  (if (< n 10) (t-digit n)
    (string-concat (t-dec-pos (quot n 10)) (t-digit (- n (* 10 (quot n 10)))))))
(defn- t-dec-neg [n :i64] :string
  (if (< n 0) (string-concat "-" (t-dec-pos (- 0 n))) (t-dec-pos n)))
(defn- t-dec [n :i64] :string
  (if (= n -9223372036854775808) "MIN" (t-dec-neg n)))
(defn- t-say [s :string] :i64
  (let [o (typed-cap-call :io/write :string :string s)] 0))
(defn- t-b2i [b :bool] :i64
  (if b 1 0))
(defn- t-bad [got :i64 want :i64] :i64
  (if (= got want) 0 1))
(defn- t-verdict [got :i64 want :i64] :string
  (if (= got want) "ok" "FAIL"))
;; M[200] counts failures
(defn- t-chk [M :vector-i64 name :string got :i64 want :i64] :vector-i64
  (let [o (t-say (string-concat name (string-concat " " (string-concat (t-dec got) (string-concat " " (string-concat (t-dec want) (string-concat " " (string-concat (t-verdict got want) "\\n"))))))))
        f (vector-at M 200)]
    (vector-assoc! M 200 (+ f (t-bad got want)))))
;; hash of n bytes at M[addr..]: h = h * 1000003 + byte (wraps)
(defn- t-hash [M :vector-i64 addr :i64 n :i64 h :i64] :i64
  (if (<= n 0)
    h
    (t-hash M (+ addr 1) (- n 1) (+ (* h 1000003) (vector-at M addr)))))
(defn- t-init [] :vector-i64
  (vector-alloc MM-WORDS))
;; two runtime strings: the source with the names, and symbol strings built by concatenation
(defn- t-src [] :string (string-concat "alpha-bet" "a-main"))
(defn- t-sym-alpha [] :string (string-concat "al" "pha"))
(defn- t-sym-main [] :string (string-concat "ma" "in"))
(defn- t-sym-beta [] :string (string-concat "be" "ta"))
(defn- t-sym-prefix [] :string (string-concat "ma" "i"))
(defn- t-sym-longer [] :string (string-concat "main" "s"))
(defn- t-w [M :vector-i64 i :i64 x :i64] :vector-i64
  (vector-assoc! M i x))
(defn- t-reset [M :vector-i64] :vector-i64
  (let [M1 (vector-assoc! M MM-ERR 0)
        M2 (vector-assoc! M1 MM-ERR-POS 0)]
    (vector-assoc! M2 MM-ERR-N 0)))
''')

def chain(writes, start="M0", prefix="W", leaf=False):
    # leaf=True: write through t-w (needed when the handle came out of a user-function call)
    lets = []; cur = start
    for j, (a, v) in enumerate(writes):
        nxt = f"{prefix}{j+1}"; lets.append(f"{nxt} ({'t-w' if leaf else 'vector-assoc!'} {cur} {a} {v})"); cur = nxt
    return lets, cur

def checks_block(ck, final, cname):
    lets = []
    for j, (n, e, x) in enumerate(ck): lets.append(f"g{cname}{j} {e}")
    cur = final
    for j, (n, e, x) in enumerate(ck):
        nxt = f"C{cname}{j}"; lets.append(f"{nxt} (t-chk {cur} \"{n}\" g{cname}{j} {x})"); cur = nxt
    return lets, cur

# scenario 1: setup, ly-run, out-build, checks
lets, cur = chain(setup())
lets.append(f"M1 (ly-run {cur})")
lets.append("M2 (out-build M1 (t-src))")
l2, cur2 = checks_block(checks, "M2", "a")
lets += l2
out.append("(defn- t-s1 [M0 :vector-i64] :vector-i64\n  (let [" + "\n        ".join(lets) + "]\n    " + cur2 + "))\n")

# parse round trips on the OUT buffer of the previous scenario
def parse_scen(name, symfn, want_off, want_cs, want_cl, want_ar, err, base_expr="(+ MM-OUT-BASE 1)", len_expr=str(len(CONT)), pre=None):
    lets = []
    cur = "M0"
    lets.append(f"R0 (t-reset M0)")
    lets.append(f"R1 (out-parse R0 {base_expr} {len_expr} ({symfn}))")
    ck = [(f"{name} ERR", "(vector-at R1 MM-ERR)", err)]
    if err == 0:
        ck += [(f"{name} offset", "(vector-at R1 MM-R0)", want_off), (f"{name} code start", "(vector-at R1 MM-R1)", want_cs),
               (f"{name} code length", "(vector-at R1 MM-R2)", want_cl), (f"{name} arity", "(vector-at R1 MM-R3)", want_ar)]
    l2, cur2 = checks_block(ck, "R1", "p")
    lets += l2
    out.append(f"(defn- t-{name} [M0 :vector-i64] :vector-i64\n  (let [" + "\n        ".join(lets) + "]\n    " + cur2 + "))\n")

parse_scen("p-main", "t-sym-main", 80, CS, total, 0, 0)
parse_scen("p-alpha", "t-sym-alpha", 0, CS, total, 2, 0)
parse_scen("p-beta-absent", "t-sym-beta", 0, 0, 0, 0, 5002)
parse_scen("p-prefix-absent", "t-sym-prefix", 0, 0, 0, 0, 5002)
parse_scen("p-longer-absent", "t-sym-longer", 0, 0, 0, 0, 5002)
parse_scen("p-truncated", "t-sym-main", 0, 0, 0, 0, 5003, len_expr=str(len(CONT) - 1))
parse_scen("p-too-short", "t-sym-main", 0, 0, 0, 0, 5003, len_expr="5")
parse_scen("p-extra-byte", "t-sym-main", 0, 0, 0, 0, 5003, len_expr=str(len(CONT) + 1))

# corrupted magic: write a 0 into the first byte, parse, restore
out.append(f"""(defn- t-p-badmagic [M0 :vector-i64] :vector-i64
  (let [R0 (t-reset M0)
        R1 (t-w R0 (+ MM-OUT-BASE 1) 0)
        R2 (out-parse R1 (+ MM-OUT-BASE 1) {len(CONT)} (t-sym-main))
        g0 (vector-at R2 MM-ERR)
        R3 (t-w R2 (+ MM-OUT-BASE 1) 75)
        C0 (t-chk R3 "p-badmagic ERR" g0 5003)]
    C0))
""")

# header offset == extracted offset, for every export: a loop-free check on the 2 exports is done above (80 and 0 equal
# the EXP offsets (code word index - 1) * 4 = 80 and 0).

# build errors: code word out of range; code too long (OUT full); CODE-BYTES mismatch
def build_scen(name, writes, errcode, post=(), extra_checks=()):
    lets, cur = chain([("MM-ERR", 0), ("MM-ERR-POS", 0), ("MM-ERR-N", 0)] + writes)
    lets.append(f"M1 (ly-run {cur})")
    cur = "M1"
    if post:
        l3, cur = chain(list(post), start="M1", prefix="P", leaf=True)
        lets += l3
    lets.append(f"M2 (out-build {cur} (t-src))")
    ck = [(f"{name} ERR", "(vector-at M2 MM-ERR)", errcode)] + list(extra_checks)
    l2, cur2 = checks_block(ck, "M2", "b")
    lets += l2
    out.append(f"(defn- t-{name} [M0 :vector-i64] :vector-i64\n  (let [" + "\n        ".join(lets) + "]\n    " + cur2 + "))\n")
build_scen("b-word-range", [(CODEA(7), 4294967296)], 5003)
build_scen("b-word-negative", [(CODEA(7), -1)], 5003)
build_scen("b-out-full", [(CODEA(7), CODE[6]), ("MM-CODE-N", 300000)], 5001)
build_scen("b-length-mismatch", [("MM-CODE-N", NW + 1)], 5003, post=[("MM-CODE-BYTES", total + 4)])
# restore a good state and rebuild: the build is re-entrant
lets, cur = chain([(CODEA(7), CODE[6]), ("MM-CODE-N", NW + 1), ("MM-ERR", 0), ("MM-ERR-POS", 0), ("MM-ERR-N", 0), ("MM-EXP-N", 1), ("MM-OUT-N", 77)])
lets.append(f"M1 (ly-run {cur})")
lets.append("M2 (out-build M1 (t-src))")
l2, cur2 = checks_block([("rebuild ERR", "(vector-at M2 MM-ERR)", 0), ("rebuild total", "(vector-at M2 MM-R0)", len(CONT)),
                          ("rebuild hash", "(t-hash M2 (+ MM-OUT-BASE 1) %d 7)" % len(CONT), hsh(CONT))], "M2", "c")
lets += l2
out.append("(defn- t-b-rebuild [M0 :vector-i64] :vector-i64\n  (let [" + "\n        ".join(lets) + "]\n    " + cur2 + "))\n")

out.append("""(defn- t-hex [M0 :vector-i64] :vector-i64
  (let [o (t-say "hex begin\\n")
        M1 (out-write-hex M0 (t-src))
        g (vector-at M1 MM-R0)
        o2 (t-say "hex end\\n")]
    (t-chk M1 "hex total" g %d)))
""" % len(CONT))
names = ["t-s1", "t-hex", "t-p-main", "t-p-alpha", "t-p-beta-absent", "t-p-prefix-absent", "t-p-longer-absent", "t-p-truncated", "t-p-too-short",
         "t-p-extra-byte", "t-p-badmagic", "t-b-word-range", "t-b-word-negative", "t-b-out-full", "t-b-length-mismatch", "t-b-rebuild"]
lets = []; cur = "A0"
for k, fn in enumerate(names):
    nxt = f"A{k+1}"; lets.append(f"{nxt} ({fn} {cur})"); cur = nxt
out.append("(defn- t-all [A0 :vector-i64] :i64\n  (let [" + "\n        ".join(lets) + f"\n        fails (vector-at {cur} 200)]\n    fails))\n")
out.append('''(defn- seed-main [] :i64
  (let [o (t-say "50-out unit test\\n")
        n (t-all (t-init))
        o2 (t-say (string-concat "failures " (string-concat (t-dec n) "\\n")))]
    n))
''')
dest = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../seed/tests/unit/50-out_t.kotoba")
open(dest, "w").write("".join(out))
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../seed/tests/unit/50-out.hex"), "w").write("\n".join(CONT[i:i+64].hex() for i in range(0, len(CONT), 64)) + "\n")
print("container bytes", len(CONT), "header", CS, "code", cb, "total", total, "scenarios", len(names))
