#!/bin/zsh
# scripts/seed/package.sh [N] [--scope LIST] [--out PATH] [--allow CSV] -- package seed-N as the `seed` command (design 3.1 step 5,
# 3.4). BOOTSTRAP-TOOL: only cc, xxd, otool, shasum and the repo's tools/kexe_loader.c are used (no node, JVM or nbb).
#
#   N        which build stage to package (default 1: the first self-built compiler). Needs build/seed/seed-N.bin and
#            seed-N.offset from `scripts/seed/build.sh N`.
#   --scope  wire-35 (:fs/app-data) scope baked into the binary, colon separated absolute directories. A packaged command
#            ignores the environment, so this IS the set of directories the seed may read and write. Default: the repo,
#            its build/ directory, /private/tmp and /tmp (the qualification runner writes under --output and TMPDIR=/tmp).
#   --out    the command to write (default build/seed/seed)
#   --allow  the capability wires granted (default $SEED_GRANT = 35,37,38,39: fs, stdout, argv, stderr; NOT 20/spawn)
#
# The loader is used unchanged in its KEXE_EMBEDDED form, like scripts/package-command.cljk does, with this header:
# the code is the extracted seed-N.bin, entry = the arity-0 `main` at seed-N.offset, argv of the process = the guest's
# argv (wire 38). Budgets are the seed's (design 2.3: M is 8M words; 128M vector items leave room for the 8 B/byte copy of a
# file read; string pool 256 MiB as measured in docs/selfhost-seed-t2-t3-20261002.md).
# Prints: build/seed/seed-package.info (sha256 of the code and the binary, scope, allow, budgets) and a one-line summary.
emulate -L zsh
setopt pipefail
source "$(dirname "$0")/lib.sh"
B=$SEED_BUILD
n=1; scope=""; out=$B/seed; allow=$SEED_GRANT
while [ $# -gt 0 ]; do
  case $1 in
    --scope) scope=$2; shift 2 ;;
    --out) out=$2; shift 2 ;;
    --allow) allow=$2; shift 2 ;;
    <->) n=$1; shift ;;
    *) echo "usage: package.sh [N] [--scope LIST] [--out PATH] [--allow CSV]" >&2; exit 2 ;;
  esac
done
[ -n "$scope" ] || scope="$SEED_REPO:$B:/private/tmp:/tmp"
bin=$B/seed-$n.bin; offf=$B/seed-$n.offset
[ -s $bin ] && [ -s $offf ] || { echo "package: missing $bin / $offf (run scripts/seed/build.sh $n)" >&2; exit 2; }
off=$(cat $offf); len=$(wc -c < $bin | tr -d ' ')
[ $off -lt $len ] || { echo "package: offset $off is not inside the $len code bytes" >&2; exit 2; }
case $scope in *\"*|*\\*) echo "package: scope must not contain a quote or backslash" >&2; exit 2 ;; esac
[[ $allow =~ '^[0-9]+(,[0-9]+)*$' ]] || { echo "package: --allow must be a comma separated list of wires" >&2; exit 2; }
case ",$allow," in *,20,*) echo "package: refusing to grant wire 20 (spawn) to the seed" >&2; exit 2 ;; esac

D=$B/package-$n; rm -rf $D; mkdir -p $D
POOL=${SEED_PKG_POOL:-268435456}; PAIRS=${SEED_PKG_PAIRS:-4194304}; VECS=${SEED_PKG_VECTORS:-65536}
ITEMS=${SEED_PKG_VECTOR_ITEMS:-134217728}; CPU=${SEED_PKG_CPU:-120}; WALL=${SEED_PKG_WALL:-120}
{
  echo "/* generated by scripts/seed/package.sh from seed-$n.bin -- do not edit */"
  echo "#define KEXE_EMBEDDED 1"
  echo "#define KEXE_EMBEDDED_OFFSET ${off}u"
  echo "#define KEXE_EMBEDDED_ARITY 0u"
  echo "#define KEXE_EMBEDDED_ISA \"aarch64\""
  echo "#define KEXE_EMBEDDED_ALLOW \"$allow\""
  echo "#define KEXE_EMBEDDED_SCOPE35 \"$scope\""
  echo "#define KEXE_EMBEDDED_SCOPE34 \"\""
  echo "#define KEXE_EMBEDDED_SPAWN_PROGRAMS \"\""
  echo "#define KEXE_EMBEDDED_SPAWN_ENV \"\""
  echo "#define KEXE_EMBEDDED_SPAWN_PATH_LOOKUP 0"
  echo "#define KEXE_EMBEDDED_STRING_POOL ${POOL}u"
  echo "#define KEXE_EMBEDDED_FUEL 0u"
  echo "#define KEXE_EMBEDDED_PAIRS ${PAIRS}u"
  echo "#define KEXE_EMBEDDED_VECTORS ${VECS}u"
  echo "#define KEXE_EMBEDDED_VECTOR_ITEMS ${ITEMS}u"
  echo "#define KEXE_EMBEDDED_CPU_SECONDS ${CPU}u"
  echo "#define KEXE_EMBEDDED_WALL_SECONDS ${WALL}u"
  echo "static const unsigned char kexe_embedded_code[$len] = {"
  xxd -i < $bin
  echo "};"
} > $D/kexe_embedded.h
mkdir -p $(dirname $out)
cc -O2 -std=c11 -I $D -include $D/kexe_embedded.h $SEED_REPO/tools/kexe_loader.c -o $out.tmp.$$ 2> $D/cc.log \
  || { echo "package: cc failed (see $D/cc.log)"; head -5 $D/cc.log; rm -f $out.tmp.$$; exit 1; }
chmod 755 $out.tmp.$$; mv $out.tmp.$$ $out
deps=$(otool -L $out | tail -n +2 | awk '{print $1}')
echo "$deps" | grep -vq '^/usr/lib/' && { echo "package: unexpected library dependency:"; echo "$deps"; exit 1; }
sha() { shasum -a 256 $1 | cut -c1-64; }
{ echo "label seed-$n packaged command (KEXE_EMBEDDED build of tools/kexe_loader.c)"
  echo "code seed-$n.bin sha256 $(sha $bin) bytes $len offset $off"
  echo "command $out sha256 $(sha $out) bytes $(wc -c < $out | tr -d ' ')"
  echo "loader-source sha256 $(sha $SEED_REPO/tools/kexe_loader.c)"
  echo "allow $allow"; echo "scope35 $scope"
  echo "budgets string-pool $POOL pairs $PAIRS vectors $VECS vector-items $ITEMS cpu-seconds $CPU wall-seconds $WALL"
  echo "libraries $(echo $deps | tr '\n' ' ')"; } > $B/seed-package.info
echo "package: $out ($(wc -c < $out | tr -d ' ') bytes, code $len bytes, entry $off, libraries: $(echo $deps | tr '\n' ' '))"
