from pathlib import Path
import json,hashlib,stat,sys,re
W=Path('/Users/junkawasaki/github/workspaces/codex');D=W/'published-mode2-x8-statemate-vector-runtime12-source-v1-20261009';S=D/'run-outputs';O=Path(__file__).resolve().parent;sys.dont_write_bytecode=True;sys.path.insert(0,str(D))
def rec(p):
 p=Path(p);a=p.lstat();assert stat.S_ISREG(a.st_mode)and not p.is_symlink();b=p.read_bytes();z=p.lstat();assert(a.st_dev,a.st_ino,a.st_size,a.st_mtime_ns)==(z.st_dev,z.st_ino,z.st_size,z.st_mtime_ns);return dict(path=str(p),bytes=len(b),sha256=hashlib.sha256(b).hexdigest())
def ck(p,r):a=rec(p);assert all(a[k]==r[k]for k in ['bytes','sha256']);return Path(p).read_bytes()
def load(p):return json.loads(Path(p).read_bytes())
sp=load(D/'source-pins.json');ip=load(D/'input-pins.json');pr=load(D/'preregistration.json');completion=load(S/'report.json')
for n,r in sp.items():ck(D/n,r)
for p,r in ip.items():ck(p,r)
G=Path(completion['rootGO']['path']);g=json.loads(ck(G,completion['rootGO']));import run
proofKeys=run.go_header(g,pr,S);assert run.source_scope(pr)
for n,k in [('source-pins.json','sourcePinsSHA256'),('input-pins.json','inputPinsSHA256'),('run.py','driverSHA256'),('preregistration.json','preregistrationSHA256')]:assert rec(D/n)['sha256']==g[k]
assert len(g['sourceReviews'])==2 and len({r['path']for r in g['sourceReviews']})==2
for rp in g['sourceReviews']:
 q=json.loads(ck(rp['path'],rp));assert q['status']==pr['sourceReviewStatus']and all(q[k]==g[k]for k in ['sourcePinsSHA256','driverSHA256','preregistrationSHA256'])
for k in proofKeys:assert g[k]==pr['qualifiedIntegrationFixtureProof'if k=='integrationFixtureProof'else k];ck(g[k]['path'],g[k])
f=load(g['integrationFixtureProof']['path']);assert f['status']=='PASS_INDEPENDENT_SAVED_FILEIO_CAPTURE_CONTROLLER_FIXTURE_ONLY'
for n,k in [('capture.py','captureSHA256'),('integration.py','integrationSHA256'),('controller.py','controllerSHA256')]:assert f[k]==sp[n]['sha256']
for p,r in load(S/'generated-pins.json').items():ck(p,r)
assert load(S/'effective-environment.json')==pr['environment']
rows=load(S/'attempts.json');results=load(S/'results.json');assert len(rows)==len(results)==12
FIELDS=['pairs','string-pool-bytes','vectors','vector-items','heap-bytes','conj','conj-tail','conj-region','conj-copy','copied-words','reserved-words','regions','scope-releases','string-regions','string-region-appends','string-copied-bytes','string-reserved-bytes'];summ=[];gaps=[]
pat=re.compile(rb'\{:status :ok :result (-?[0-9]{1,20}) :fuel \{:initial ([0-9]{1,20}) :remaining ([0-9]{1,20})\} :heap \{:capacity ([0-9]{1,20}) :used ([0-9]{1,20})\} :string-pool \{:capacity ([0-9]{1,20}) :used ([0-9]{1,20})\} :vectors \{:capacity ([0-9]{1,20}) :used ([0-9]{1,20})\} :vector-items \{:capacity ([0-9]{1,20}) :used ([0-9]{1,20})\}\}\n')
for i,(r,c,z)in enumerate(zip(rows,pr['cases'],results),1):
 label=c['label'];assert r['index']==i and r['label']==label and r['nativeArgv']==c['nativeArgv']and r['environment']==pr['environment']and r['state']=='terminal'and r['returncode']==0 and r['failure']is None and r['waitEntered']and not r['waitUncertain']and r['signalingAuthorityRetired']and r['captureStopAcknowledged']and not r['watchdogErrors']
 sealP=S/(label+'.admission.json');seal=load(sealP);assert rec(sealP)['bytes']<=4096 and sealP.stat().st_mode&0o222==0;assert seal['index']==i and seal['rootGO']==rec(G)and seal['sourcePinsSHA256']==g['sourcePinsSHA256']and seal['preregistrationSHA256']==g['preregistrationSHA256']
 for k in ['label','nativeArgv','workload','arm','profile','symbol','offset','arity','native','container','source']:assert seal[k]==c[k]
 assert r['argv'][:3]==[pr['interpreter']['path'],str(D/'launch-wrapper.py'),'--journal-fd']and r['argv'][3].isdigit()and r['argv'][4:6]==['--admission-sha',rec(sealP)['sha256']]and r['argv'][6:]==['--',*c['nativeArgv']]
 for k in ['native','container','source']:ck(c[k]['path'],c[k])
 payload,ex=run.container(Path(c['container']['path']).read_bytes());assert payload==Path(c['native']['path']).read_bytes()and(c['symbol'],c['offset'],1)in ex
 raw={k:ck(S/(label+ext),r[k])for k,ext in [('stdout','.stdout'),('stderr','.stderr'),('limitJournal','.limit-journal.jsonl'),('memoryJournal','.memory-journal.jsonl')]};obs=r['controllerObservation'];cap=obs['capture'];mr=obs['memoryAdmissionRecord'];assert cap['completeRaw']and cap['stoppedWriter']and cap['EOF']==dict(stdout=True,stderr=True)and not any(cap['dropped'].values())and not cap['errors']and cap['hashes']=={k:r[k]for k in ['stdout','stderr']}
 m=pat.fullmatch(raw['stdout']);assert m and len(raw['stdout'])<=65536;ns=list(map(int,m.groups()));ans,initial,remaining=ns[:3];caps=ns[3::2];used=ns[4::2];assert ans==c['expectedResult']and -(1<<63)<=ans<(1<<63)and initial==16777216 and 0<=remaining<=initial and caps==[2097152,65536,4096,65536]and all(0<=v<=a for v,a in zip(used,caps))
 kv=re.findall(rb':([a-z-]+) ([0-9]{1,20})',raw['stderr']);ar={k.decode():int(v)for k,v in kv};assert len(kv)==17 and list(ar)==FIELDS and b'KEXE_ARENA_USE {'+b' '.join(b':'+k+b' '+v for k,v in kv)+b'}\n'==raw['stderr'];assert all(0<=v<2**64 for v in ar.values())and ar['heap-bytes']==16*ar['pairs']+ar['string-pool-bytes']+16*ar['vectors']+8*ar['vector-items']and [ar[k]for k in ['pairs','string-pool-bytes','vectors','vector-items']]==used
 rr=z['report'];assert rr['result']==ans and rr['fuelInitial']==initial and rr['fuelRemaining']==remaining and rr['fuelConsumed']==initial-remaining and rr['arena17']==ar and rr==r['structuredReportObservation']and z['arena']==ar and r['counterObservation']==dict(status='valid',values=ar)and z['case']==c and z['returncode']==0 and z['rawStdoutSHA256']==r['stdout']['sha256']and z['rawStderrSHA256']==r['stderr']['sha256']
 q=rr['structured'];assert q==dict(status='ok',result=ans,trapExit=None,initialFuel=initial,remainingFuel=remaining,metered=True,arenaCapacities=dict(zip(['pairs','string-pool-bytes','vectors','vector-items'],caps)),arenaUsed=dict(zip(['pairs','string-pool-bytes','vectors','vector-items'],used)))
 jl=[json.loads(x)for x in raw['limitJournal'].splitlines()];assert len(jl)==6 and len(raw['limitJournal'])<=65536;ew=jl[0];keys=sorted(pr['environment']);assert ew==dict(stage='environment-admission',suppliedKeyNames=keys,runtimeExtraKeyNames=ew['runtimeExtraKeyNames'],missingKeyNames=[],changedExpectedKeyNames=[],nativeExecKeyNames=keys,nativeExecEnvironmentExact=True)and ew['runtimeExtraKeyNames']in [[],['__CF_USER_TEXT_ENCODING']]
 for j,(nm,want)in enumerate([('RLIMIT_FSIZE',[67108864,67108864]),('RLIMIT_CPU',[30,31])],1):
  a,b=jl[2*j-1:2*j+1];assert a['index']==j and a['limit']==nm and a['stage']=='before'and a['desired']==want and all(v==9223372036854775807 or v>=w for v,w in zip(a['before'],want))and b==dict(index=j,limit=nm,stage='outcome',outcome='installed',readback=want)
 assert jl[-1]==dict(stage='exec-ready',argv=c['nativeArgv'],ASSetterRequested=False,CPUGraceHardSeconds=31)
 sm=[json.loads(x)for x in raw['memoryJournal'].splitlines()];assert 0<len(sm)==r['memorySamples']==obs['sampleCount']==mr['acceptedSamples']<=2048 and len(raw['memoryJournal'])==r['memoryJournalBytes']<=8388608;sums=[];births={};prev=0
 for ordinal,tm,pg,mem in sm:
  assert ordinal==len(sums)+1 and tm>prev and pg==r['pid']and 1<=len(mem)<=2 and len({x[0]for x in mem})==len(mem)and len([x for x in mem if x[0]==pg])==1;prev=tm
  for pid,bt,foot in mem:assert bt>0 and 0<=foot<2**64 and(pid not in births or births[pid]==bt);births[pid]=bt
  total=sum(x[2]for x in mem);assert total<=4294967296;sums.append(total)
 assert obs['semanticQualification']and obs['sampleReceiptPersistenceQualified']and mr['acceptedLeaderBirthBound']and mr['completePipeEOF']and mr['stoppedClosedCapture']and not mr['rawTruncated']and not mr['captureErrors']and mr['exactDirectChildWait']=='closed0'and not mr['waitUncertain']and mr['withinOriginalDeadline']and mr['groupAuthorityRetired']and mr['groupOperationsAfterWait']==mr['groupOperationsAfterUncertainty']==0 and not mr['otherRefusals']
 if mr['failure']is None:assert obs['status']=='COMPLETE_SEMANTIC_SAMPLED_MEMORY'and obs['strictOldMemoryPolicyPassed']
 else:
  f=mr['failure'];assert f['contextVersion']=='owned-group-sampling-failure-context-v1'and f['typedOrigin']=='fresh-owned-group-api-v1'and f['failureClass']in ['kernel-oserror','kernel-failed-return']and f['errno']==3 and f['stage']in ['leader-getpgid','member-getpgid','member-rusage']and f['pid']in births and f['queryOrdinal']>0 and obs['status']=='SEMANTIC_DIAGNOSTIC_TERMINATION_GAP'and not obs['strictOldMemoryPolicyPassed']and cap['firstFailure']=='sampling-uncertainty'and obs['memoryObservation']['missingFootprint']is None and not obs['memoryObservation']['zeroSynthesized'];gaps.append(dict(label=label,failure=f))
 assert z['memoryObservation']==obs['memoryObservation']and z['strictOldMemoryPolicyPassed']==obs['strictOldMemoryPolicyPassed'];ev=obs['controllerEvents'];assert ev.count('wait-enter')==1 and ev.index('retire:before-watchdog-stop-and-wait')<ev.index('wait-enter')and 'group-operation'not in ev[ev.index('wait-enter')+1:]
 summ.append(dict(index=i,label=label,workload=c['workload'],profile=c['profile'],arm=c['arm'],result=ans,fuelInitial=initial,fuelRemaining=remaining,fuelConsumed=initial-remaining,arena17=ar,acceptedSamples=len(sm),sampleSums=sums,strictSampledPassed=obs['strictOldMemoryPolicyPassed'],memoryAdmissionRecord=mr,wait=0,raw={k:r[k]for k in ['stdout','stderr','limitJournal','memoryJournal']},seal=rec(sealP)))
pairs=[]
for a,b in zip(summ[::2],summ[1::2]):
 assert a['workload']==b['workload']and a['profile']==b['profile']and a['arm']=='OFF'and b['arm']=='ON'and all(a[k]==b[k]for k in ['result','fuelInitial','fuelRemaining','fuelConsumed','arena17']);pairs.append({k:a[k]for k in ['workload','profile','result','fuelInitial','fuelRemaining','fuelConsumed','arena17']})
assert len(pairs)==6 and len(gaps)==1 and sum(x['strictSampledPassed']for x in summ)==11
assert load(S/'terminal.json')==dict(loaderCalls=12,allChildrenClosed=True,failure=False)and not(S/'failure.json').exists();assert completion['status']=='COMPLETE_PUBLISHED_MODE2_X8_STATEMATE_VECTOR_RUNTIME12_DIAGNOSTIC_ONLY'and completion['results']==results and completion['runtimeCalls']==12 and not completion['new12StrictSampledPolicyPassed']
for n,r in completion['evidence'].items():ck(S/n,r)
for k in ['full19FunctionalQualified','generalCandidateAdoptionQualified','fullClobberCertificateQualified','actualTypedMode2AdmissionObserved','performanceQualified','hardPeakQualified','strictPhysicalMemoryQualified','C2']:assert completion[k]is False
assert completion['C95FuelArenaAvailable']is False and completion['C95FuelArena']is None
oracle=load(pr['C95Oracle']['path']);crows=[x for x in oracle['rows']if x['workload']=='statemate'];assert crows==pr['C5StatemateRows'];assert all(p['result']==next(c['result']for c in crows if c['n']==p['profile'])for p in pairs if p['workload']=='statemate')and pairs[-1]['result']==3
out={'status':'PASS_INDEPENDENT_SAVED_PUBLISHED_MODE2_X8_STATEMATE_VECTOR_RUNTIME12_DIAGNOSTIC_ONLY','independent':True,'priorImplementationAuthorship':False,'sourcePinsSHA256':g['sourcePinsSHA256'],'inputPinsSHA256':g['inputPinsSHA256'],'driverSHA256':g['driverSHA256'],'preregistrationSHA256':g['preregistrationSHA256'],'rootGO':rec(G),'sourceReviews':g['sourceReviews'],'completion':rec(S/'report.json'),'verifiedClosure':dict(sourceFiles=len(sp),inputFiles=len(ip),inputLogicalBytes=sum(x['bytes']for x in ip.values())),'closedRuntimeCalls':12,'calls':summ,'pairedCases':pairs,'acceptedFiniteSamples':sum(x['acceptedSamples']for x in summ),'strictSamplingPassedCalls':11,'admittedTypedTerminationGaps':gaps,'C5StatemateResultOnly':crows,'vectorFixtureI64Expected':3,'boundProofs':{k:g[k]for k in proofKeys},'images':pr['images'],'conclusion':'All fixed12 calls closed0 with complete savedraw, exact case result and six adjacent OFF/ON result/meteredfuel/all17arena parity. Five unchanged statemate profiles match saved C result-only oracle; synthetic vector n1 result3. Eleven strict sampled admissions plus one typed termination-gap admission; no full strict physicalmemory/hardpeak or general optimizer qualification.','qualification':dict(finiteRuntime12CasesOnly=True,full19Functional=False,fullClobberCertificate=False,actualTypedMode2Admission=False,generalCandidateAdoption=False,fixedpoint=False,performance=False,hardPeak=False,C2=False,ComputeCIDResultCIDPerformance=False),'limits':['Finite cases are runtime diagnostics, not general GPR/context/vector lifetime/alias certificate or adoption proof.','SavedC has no fuel/arena/timing data; pair fuel/arena comparisons are OFF versus ON only.','Source-bound capture/ownership/resource/wait receipts are not external syscall chronology or universal descendant wait proof.','One persisted sampling uncertainty retained with missing footprint null and no zero synthesized; kernel cause not inferred.','Root reports once host require_escalated session99269 CLOSED0; separate outer attribution, no independent outer raw inspected.'],'operationalCalls':0,'subjectWrites':False,'auditSHA256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}
p=O/'report.json';p.write_text(json.dumps(out,indent=2)+'\n');print(rec(p))
