from pathlib import Path
import json,hashlib,tarfile,subprocess
r=Path('/Users/junkawasaki/github/wt/amu-seed17');w=Path('/private/tmp/amu-vector-validity-20261006');d=r/'docs/evidence/coscientist-vector-validity-20261006';d.mkdir(parents=True,exist_ok=True);load=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();t=load(w/'timing-audit-wikisort.json');assert not t['qualifies'];assert (r/'seed/41-a64gen.kotoba').read_bytes()==(w/'baseline-41-a64gen.kotoba').read_bytes()
s={'status':'rejected-native-validity-dominance-performance-experiment','baselineSourceCommit':'d93aa15fb9c77dcdcfd7569ad7598f96fc50e03f','decision':'Native semantic proof passes, fresh timing fails unchanged prospective speedup and gap-versus-SD requirements. Product remains unchanged. No identical-code retiming.','hypothesis':load(w/'hypothesis.json'),'generations':load(w/'generations.json'),'nativeAdmission':load(w/'meta-admission.json'),'codeChanges':load(w/'code-change.json'),'independentNativeAudit':load(w/'preflight-audit.json'),'timing':t,'timingPins':load(w/'timing-artifact-audit.json'),'productChanged':False,'officialEmbenchScore':False,'COrBetter':False,'productGatesAndIntegratedRebuild':'Not run: performance rejection occurs before promotion; previous qualified product remains current.'}
for name,key in [('state-proof.json','handStateProof'),('import-proof.json','allocatingImportProof'),('resource-proof.json','resourceExhaustionProof')]:s[key]={k:v for k,v in load(w/name).items() if k!='runs'}
for name,key in [('layout-proof.json','newRealTestLayout'),('base-layout-proof.json','priorFixtureArtifactContinuity'),('observer-byte-audit.json','observerByteProof')]:s[key]=load(w/name)
(d/'summary.json').write_text(json.dumps(s,indent=2)+'\n');(d/'archive.py').write_bytes(Path(__file__).read_bytes());(d/'timing-audit.json').write_bytes((w/'timing-audit-wikisort.json').read_bytes())
q=subprocess.run(['git','diff','--no-index',str(w/'baseline-41-a64gen.kotoba'),str(w/'41-a64gen-prototype.kotoba')],capture_output=True,text=True);assert q.returncode==1;(d/'prototype.diff').write_text(q.stdout)
with tarfile.open(d/'native-proof.tgz','w:gz') as a:
 for x in sorted(w.iterdir()):
  if x.name in ['__pycache__','timing-package','timing.log']:continue
  a.add(x,arcname=x.name)
 for n in ['seed/MANIFEST','seed/SIR','seed/HEADS','seed/MEMORY-MAP','tools/kexe_loader.c','AGENTS.md','scripts/seed/a64gen-fixtures.py','seed/tests/unit/41-a64gen.expected']:a.add(r/n,arcname='baseline-source/'+n)
 for n in ['clobber-state-loader.c','clobber-state-loader']:a.add(Path('/private/tmp/amu-context-call-20261005')/n,arcname='diagnostic/'+n)
with tarfile.open(d/'timing.tgz','w:gz') as a:
 for n in ['remote-timing.py','timing-package','audit-workload.py','timing-audit-wikisort.json','timing-artifact-audit.py','timing-artifact-audit.json','timing.log']:a.add(w/n,arcname=n)
next={'status':'registered-not-implemented-or-measured','hypothesis':'Guard and specialize a bounded loop region with repeated vector reads. Prove unchanged handle and entry dominance; reuse descriptor/data base in dedicated preserved registers only across a fully proven region. Keep each original signed wrapping index, per-access bounds and exact fuel/trap publication; use original path when entry guards fail.','evidence':'Straight-line validity reuse admits only3 WikiSort sites, saves60B and does not qualify timing. Wider ordinary vector-at/loop coverage needs actual native SIR admission census before performance claims. Existing93139 ordinary vector-at census is a count, not a time share.','invalidation':'Refuse unknown calls/capabilities/open imports, handle reassignment, unproved control flow and any arena/reset/table mutation. Item stores invalidate loaded-value reuse; this hypothesis does not cache item values. Runtime conj creates a new descriptor; previous contrary statement is amended in this experiment.','qualification':'Preserve all19 originals, exact native state/fuel/resources/partial writes, allocating imports and invalid guards, native fixedpoint, originalquiet30rotatingtriples for every changedguest; require1.05andmeanGap>sumSD before fullproductgates/integrated3gen/per-casecorpus.','scope':'C-level-or-better on all19 aligned original workloads; no official-score or100percent claim.'};(d/'next-hypothesis.json').write_text(json.dumps(next,indent=2)+'\n')
(d/'checksums.sha256').write_text(''.join(sha(x)+'  '+x.name+'\n' for x in sorted(d.iterdir()) if x.is_file() and x.name!='checksums.sha256'));print('PASS rejected candidate proof and fresh raw timing archived')
