#!/usr/bin/env python3
"""seed/tests/r6d/dec/gen-dec.py OUT.kotoba [N] -- the R6D decimal-f64-parse / decimal-f64x3-parse cases (agent R6D,
2026-10-03; BOOTSTRAP-TOOL, a generator only). Stage-0 refuses both operations natively, so the oracle is the reference's
own reading (kotoba.kir.decimal :default arm = Double/parseDouble under the ADR 0019 grammar), here Python's float() (also
correctly rounded, round half even) under the same grammar and byte bounds. main answers 0 when every case agrees, else
mismatches * 100000 + the 1-based index of the first one."""
import re, struct, sys, random
GRAM = re.compile(r'^[+-]?(?:(?:[0-9]+(?:\.[0-9]*)?)|(?:\.[0-9]+))(?:[eE][+-]?[0-9]{1,3})?$')
def ref(s):
    if len(s.encode()) > 64 or not GRAM.match(s): return None
    x = float(s)
    if x in (float('inf'), float('-inf')): return None
    b = struct.unpack('<q', struct.pack('<d', x))[0]
    return b
def ref3(s):
    if len(s.encode()) > 194 or not re.fullmatch(r'[0-9eE+.\- \t\r\n]+', s): return None
    parts = [p for p in re.split(r'[ \t\r\n]+', s.strip(' \t\r\n')) if p != ''] if s.strip(' \t\r\n') else []
    if len(parts) != 3: return None
    v = [ref(p) for p in parts]
    return None if any(x is None for x in v) else v
FIXED = ['0', '-0', '+0', '0.0', '-0.0', '.0', '0.', '1', '-1', '0.1', '0.2', '0.3', '1.5', '2.5', '1e0', '1E1', '1e+1', '1e-1',
  '123456789012345678901234567890', '9007199254740993', '9007199254740995', '9007199254740992.5', '4503599627370496.5',
  '1e308', '1.7976931348623157e308', '1.7976931348623158e308', '1.7976931348623159e308', '1.8e308', '1e309', '-1e309',
  '2.2250738585072014e-308', '2.2250738585072011e-308', '2.225073858507201e-308', '4.9e-324', '5e-324', '-5e-324',
  '2.4703282292062327e-324', '2.4703282292062328e-324', '2.4703282292062327208828439643411068618252990130716238221279284125033775364e-324',
  '1e-323', '1e-400', '-1e-400', '1e-999', '9e999', '0e999', '0.000000000000000000000000000000000000000000001e-300',
  '3.141592653589793', '2.718281828459045', '6.02214076e23', '1.602176634e-19', '123.456e-7', '000000123.000', '.5e1',
  '5.e-1', '1234567890123456789012345678901234567890123456789012345678901234',
  '', '+', '-', '.', '+.', 'e1', '1e', '1e+', '1e1234', '1.2.3', ' 1', '1 ', 'inf', 'NaN', 'nan', '0x10', '1_000', '1,5',
  '12345678901234567890123456789012345678901234567890123456789012345', '--1', '+-1', '1e--1', '1.e5', '1..2', '١']
X3 = ['1 2 3', ' 1.5\t-2e3\n0.1 ', '1 2', '1 2 3 4', '1  2\r\n3', '', '   ', '1 2 x', '1e999 2 3', '0 -0 5e-324',
      '1,2,3', '1e308 1e-308 0.5']
def main():
    out = sys.argv[1]; n = int(sys.argv[2]) if len(sys.argv) > 2 else 300
    rnd = random.Random(20261003)
    cases = list(FIXED)
    while len(cases) < len(FIXED) + n:
        k = rnd.randint(1, 25); digs = ''.join(rnd.choice('0123456789') for _ in range(k))
        p = rnd.randint(0, k); s = digs[:p] + ('.' + digs[p:] if p < k or rnd.random() < 0.2 else '')
        if rnd.random() < 0.7: s += rnd.choice('eE') + rnd.choice(['', '+', '-']) + str(rnd.randint(0, 340))
        if rnd.random() < 0.3: s = '-' + s
        cases.append(s)
    for _ in range(40):   # halfway cases: exact binary64 midpoints written in full
        m = rnd.getrandbits(52) | (1 << 52); e = rnd.randint(-1070, 960)
        from fractions import Fraction
        v = Fraction(2 * m + 1) * (Fraction(2) ** (e - 1))
        # shortest exact decimal of v: v = a / 2^k -> a * 5^k / 10^k
        num, den = v.numerator, v.denominator
        k = 0
        while den % 2 == 0: den //= 2; k += 1
        if den != 1 or k > 60: continue
        s = str(num * 5 ** k); s = (s[:-k] or '0') + '.' + s[-k:] if k else s
        if len(s) <= 64: cases.append(s)
    def kstr(s): return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'
    lines = [';; GENERATED by seed/tests/r6d/dec/gen-dec.py: %d decimal-f64-parse cases, %d decimal-f64x3-parse cases' % (len(cases), len(X3)),
             ';; want: 0', '(ns r6d.dec (:export [main]))',
             '(defn- chk [s :string w :i64 sm :bool] :i64 (let [o (decimal-f64-parse s)] (if (option-some?-of [:option :f64] o) (if (and sm (= (f64-to-bits (option-value-of [:option :f64] o (f64-from-bits 0))) w)) 0 1) (if sm 1 0))))',
             '(defn- chk3 [s :string a :i64 b :i64 c :i64 sm :bool] :i64 (let [o (decimal-f64x3-parse s)] (if (option-some?-of [:option [:vector [:f64 :f64 :f64]]] o) (let [v (option-value-of [:option [:vector [:f64 :f64 :f64]]] o (__r6d-none3))] (if (and sm (= (f64-to-bits (nth v 0)) a) (= (f64-to-bits (nth v 1)) b) (= (f64-to-bits (nth v 2)) c)) 0 1)) (if sm 1 0))))',
             '(defn- __r6d-none3 [] [:vector [:f64 :f64 :f64]] (__r6-as [:vector [:f64 :f64 :f64]] [0 0 0]))',
             '(defn- acc [r :i64 i :i64 x :i64] :i64 (if (= x 0) r (if (= (bit-and r 65535) 0) (+ r 100000 i) (+ r 100000))))']
    allc = []
    for s in cases:
        b = ref(s); allc.append('(chk %s %d %s)' % (kstr(s), b if b is not None else 0, 'true' if b is not None else 'false'))
    for s in X3:
        v = ref3(s); allc.append('(chk3 %s %d %d %d %s)' % (kstr(s), *(v if v else (0, 0, 0)), 'true' if v else 'false'))
    fns = []
    for k in range(0, len(allc), 16):
        body = '0'
        for j, c in enumerate(allc[k:k + 16]):
            body = '(acc %s %d %s)' % (body, k + j + 1, c)
        fns.append('(defn- g%d [r :i64] :i64 %s)' % (k // 16, body.replace('(acc 0 ', '(acc r ', 1)))
    lines += fns
    expr = 'r0'
    lines.append('(defn main [] :i64 (let [r0 0 %s] r%d))' % (' '.join('r%d (g%d r%d)' % (i + 1, i, i) for i in range(len(fns))), len(fns)))
    open(out, 'w').write('\n'.join(lines) + '\n')
    print(len(allc))
main()
