;; scripts/package-command.cljs — turn an extracted native entry into a
;; STANDALONE executable.
;;
;; Until now a Kotoba "command" was an invocation:
;;
;;   kexe-loader cmd.bin 940 0 aarch64 37,38 -- hello world
;;
;; and four of those six things are facts about the program, not choices its
;; caller should be making. This writes them into a C header and links the
;; loader against it, so what comes out is `./cmd hello world` -- one file,
;; on PATH, with no arguments that select what it runs or what it may do.
;;
;; That is the same shape a Rust binary has: machine code plus the runtime it
;; needs. The loader IS the runtime here -- kotoba-native owns instruction
;; selection and explicitly does not own syscalls or capability tables (its
;; README says so), so a command is guest code plus this host, linked.
;;
;; The grant travels as the SAME allow-csv text a loader invocation takes and
;; is parsed by the same `parse_allow`, so packaging cannot widen authority:
;; a packaged command has no argument that names a capability, and the bytes
;; it executes are a constant of the binary rather than a path it is handed.
;;
;;   nbb scripts/package-command.cljs --code cmd.bin --offset 940 \
;;     --isa aarch64 --allow 37,38 --output ./cmd
;;
;; `--offset` and `--isa` are what `amu extract-native` reported. Arity must
;; be 0: a command takes its input through :cli/args, not through i64
;; parameters there is nowhere to write.
(ns package-command
  (:require [clojure.string :as str] ["fs" :as fs] ["path" :as path] ["os" :as os]))

(def cp (js/require "node:child_process"))
(def argv (vec (drop 3 (.-argv js/process))))

(defn- opt [flag]
  (let [i (.indexOf (to-array argv) flag)]
    (when (>= i 0) (nth argv (inc i) nil))))

(defn- die [message]
  (println (pr-str {:kotoba.cli/ok? false :kotoba.cli/message message}))
  (.exit js/process 2))

(let [code-path (opt "--code")
      offset (opt "--offset")
      isa (or (opt "--isa") "aarch64")
      allow (or (opt "--allow") "-")
      out (opt "--output")
      cc (or (opt "--cc") (.-CC js/process.env) "cc")
      ;; nbb puts the script path at argv[2]; the loader source is its
      ;; sibling, so the packager works from any working directory.
      script (.resolve path (aget (.-argv js/process) 2))
      loader (.join path (.dirname path (.dirname path script))
                    "tools" "kexe_loader.c")]
  (when-not (and code-path offset out) (die "--code, --offset and --output are required"))
  (when-not (contains? #{"aarch64" "x86_64"} isa) (die (str "unknown isa: " isa)))
  (when-not (re-matches #"[0-9]+" (str offset)) (die "--offset must be a decimal"))
  ;; The allow list is copied through verbatim and re-parsed by the loader's
  ;; own parse_allow at run time; refusing anything but the two shapes it
  ;; accepts here keeps a typo from becoming a C string that fails closed at
  ;; the far end with no explanation.
  (when-not (or (= allow "-") (re-matches #"[0-9]+(,[0-9]+)*" allow))
    (die "--allow must be a comma-separated list of wire ids, or - for none"))
  (when-not (.existsSync fs code-path) (die (str "no such file: " code-path)))
  (when-not (.existsSync fs loader) (die (str "loader source not found: " loader)))
  (let [bytes (.readFileSync fs code-path)
        n (.-length bytes)
        _ (when (zero? n) (die "the extracted code is empty"))
        _ (when (>= (js/parseInt offset 10) n)
            (die (str "offset " offset " is past the end of " n " bytes")))
        rows (->> (range n)
                  (map #(str "0x" (.padStart (.toString (aget bytes %) 16) 2 "0")))
                  (partition-all 12)
                  (map #(str "  " (str/join ", " %)))
                  (str/join ",\n"))
        header (str "/* generated by scripts/package-command.cljs -- do not edit */\n"
                    "#define KEXE_EMBEDDED 1\n"
                    "#define KEXE_EMBEDDED_OFFSET " offset "u\n"
                    "#define KEXE_EMBEDDED_ARITY 0u\n"
                    "#define KEXE_EMBEDDED_ISA \"" isa "\"\n"
                    "#define KEXE_EMBEDDED_ALLOW \"" allow "\"\n"
                    "static const unsigned char kexe_embedded_code[" n "] = {\n"
                    rows "\n};\n")
        dir (.mkdtempSync fs (.join path (.tmpdir os) "kexe-package-"))
        header-path (.join path dir "kexe_embedded.h")]
    (.writeFileSync fs header-path header "utf8")
    (let [r (.spawnSync cp cc (clj->js ["-O2" "-std=c11" "-I" dir
                                        "-include" header-path
                                        loader "-o" out])
                        #js {:encoding "utf8"})]
      (if (not= 0 (.-status r))
        (die (str "cc failed: " (.-stderr r)))
        (do (.chmodSync fs out 0755)
            (println (pr-str {:ok true :output out :code-bytes n
                              :offset (js/parseInt offset 10) :isa isa :allow allow
                              :size (.-size (.statSync fs out))})))))))
