#!/usr/bin/env python3
"""seed/tests/r6b/srclib/gen-srclib.py [--check] -- embed the R6B source-route library into seed/21-check.kotoba
(agent R6B, 2026-10-03; BOOTSTRAP-TOOL: a generator only, never in a seed's process tree).

Sources (one authority each): r6b-lib.kotoba (groups `;; @group NAME`, one defn per line) and, for the doc group, the KIR
document library seed/tests/kir/doclib/doclib.kotoba (its defns made private: `(defn ` -> `(defn- `). The block between
';; BEGIN R6B srclib' and ';; END R6B srclib' of 21-check is rewritten: one string function ck-r6b-t-<group> per group
(chunked), the group bits, and ck-r6b-name-bit (the group of a call-head spelling, by its FNV-1a hash = 20-names nm-hash).
--check exits 1 when the file differs.
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..', '..', '..'))
LIB = os.path.join(HERE, 'r6b-lib.kotoba')
DOCLIB = os.path.join(REPO, 'seed', 'tests', 'kir', 'doclib', 'doclib.kotoba')
DST = os.path.join(REPO, 'seed', '21-check.kotoba')
# the capability catalogue (one authority: the vendored copy of kotoba-lang lang/capability-catalog.edn; --check also compares it
# with the kotoba-lang worktree when that exists)
CATALOG = os.path.join(REPO, 'resources', 'kotoba', 'lang', 'capability-catalog.edn')
CATALOG_UPSTREAM = '/private/tmp/wt-K-kotoba-lang/lang/capability-catalog.edn'
BEGIN = ';; BEGIN R6B srclib (generated by seed/tests/r6b/srclib/gen-srclib.py)'
END = ';; END R6B srclib'
GROUPS = ['kw', 'doc', 'sfb', 'min', 'max', 'exi', 'rem', 'utf8', 'parse', 'sym', 'vec', 'f64', 'oi64', 'dec']   # R6C: vec f64; R6D: oi64 dec
# exact call-head spellings that select a group (a head that starts with "document-" selects doc, see ck-r6b-head-bit)
NAMES = [('keyword-name', 'kw'), ('keyword-from-string', 'kw'), ('str', 'kw'), ('ex-info', 'exi'), ('ex-message', 'exi'),
         ('ex-data', 'exi'), ('string-find-byte', 'sfb'), ('min', 'min'), ('max', 'max'),
         ('nil?', 'doc'), ('some?', 'doc'), ('map?', 'doc'), ('boolean?', 'doc'), ('integer?', 'doc'), ('string?', 'doc'),
         ('keyword?', 'doc'), ('vector?', 'doc'), ('list?', 'doc'), ('seq?', 'doc'), ('set?', 'doc'), ('coll?', 'doc'), ('first', 'doc'), ('second', 'doc'), ('rest', 'doc'), ('rem', 'rem'), ('string-to-utf8', 'utf8'),
         ('string-parse-i64', 'parse'), ('parse-long', 'parse'), ('symbol', 'sym'),
         ('vector-drop', 'vec'), ('vector-take', 'vec'), ('subvec', 'vec'), ('into', 'vec'),
         ('f64-to-bits', 'f64'), ('f64-from-bits', 'f64'),   # R6C
         ('some', 'oi64'), ('option-none', 'oi64'), ('option-some?', 'oi64'), ('option-value', 'oi64'),
         ('decimal-f64-parse', 'dec'), ('decimal-f64x3-parse', 'dec')]   # R6D
CHUNK = 6
# spellings 21-check's R6B desugaring recognises by their FNV-1a hash (SF-HASH of the head symbol): (def ck-r6b-h-<name> H)
HASHED = ['str', 'match-option', 'none', 'some', 'ex-info', '__r6-i2s', '__r6-b2s', '__r6-kwtext', 'document-i64',
          'document-string', 'document-keyword', 'document-bool', 'vector-i64', 'document-vector', 'document-list', 'document-set', 'document-map', 'document-get',
          'document-contains', 'document-assoc', 'document-dissoc', 'record-assoc', '__r6-dnth', 'document-count', '__r6-dkeys']


def fnv(s):
    h = 0xcbf29ce484222325
    for ch in s.encode():
        h = ((h ^ ch) * 0x100000001b3) & 0xFFFFFFFFFFFFFFFF
    return h - (1 << 64) if h >= (1 << 63) else h


def esc(s):
    assert 'WRITE_SEP' not in s and 'APPEND_SEP' not in s
    return s.replace('\\', '\\\\').replace('"', '\\"')


def groups():
    g = {k: [] for k in GROUPS}
    cur = None
    for line in open(LIB, encoding='utf-8'):
        m = re.match(r';; @group (\S+)', line)
        if m:
            cur = m.group(1); continue
        if line.startswith('(defn- ') or line.startswith('(def '):
            g[cur].append(line.rstrip('\n'))
    doc = [l.rstrip('\n').replace('(defn ', '(defn- ', 1) for l in open(DOCLIB, encoding='utf-8') if l.startswith('(defn ')]
    g['doc'] = doc + g['doc']
    return g


def strfn(name, defs):
    out = []
    chunks = [defs[i:i + CHUNK] for i in range(0, len(defs), CHUNK)]
    for k, ch in enumerate(chunks):
        parts = ['"' + esc(d) + '\\n"' for d in ch]
        expr = parts[-1]
        for p in reversed(parts[:-1]):
            expr = f'(string-concat {p}\n  {expr})'
        out.append(f'(defn- {name}{k} [] :string\n  {expr})')
    expr = f'({name}{len(chunks) - 1})'
    for k in range(len(chunks) - 2, -1, -1):
        expr = f'(string-concat ({name}{k}) {expr})'
    out.append(f'(defn- {name} [] :string {expr})')
    return out


def catalog():
    text = open(CATALOG, encoding='utf-8').read()
    out = re.findall(r':source-operation (\S+)[^{}]*?:compiler-wire-id (\d+)', text)
    assert len(out) >= 40 and len({n for n, _ in out}) == len(out), 'capability catalogue: unexpected shape'
    return [(n, int(w)) for n, w in out]


def block():
    g = groups()
    out = [BEGIN, ';; edit seed/tests/r6b/srclib/r6b-lib.kotoba (or the KIR doclib), then run the generator']
    for i, k in enumerate(GROUPS):
        out.append(f'(def ck-r6b-g-{k} {1 << i})')
    for n in HASHED:
        out.append(f'(def ck-r6b-h-{n} {fnv(n)})')
    out.append(';; the group bit of the call-head spelling with hash h (exact names; the document- prefix is tested apart)')
    out.append('(defn- ck-r6b-name-bit [h :i64] :i64')
    out.append('  (cond ' + '\n        '.join(f'(= h {fnv(n)}) ck-r6b-g-{gr}   ; {n}' for n, gr in NAMES) + '\n        :else 0))')
    out.append(';; the capability catalogue (resources/kotoba/lang/capability-catalog.edn): the wire id of the friendly qualified')
    out.append(';; name (:source-operation) with FNV-1a hash h, 0 for none')
    cat = catalog()
    out.append('(defn- ck-r6b-capwire [h :i64] :i64')
    out.append('  (cond ' + '\n        '.join(f'(= h {fnv(n)}) {w}   ; {n}' for n, w in cat) + '\n        :else 0))')
    out.append(f'(def ck-r6b-h-fs-app-data-bytes {fnv("fs/app-data-bytes")})')
    for k in GROUPS:
        out += strfn(f'ck-r6b-t-{k}', g[k])
    out.append(END)
    return '\n'.join(out) + '\n'


def main():
    text = open(DST, encoding='utf-8').read()
    i = text.find(BEGIN); j = text.find(END)
    if i < 0 or j < 0:
        sys.exit('gen-srclib: markers not found in ' + DST)
    j = text.find('\n', j) + 1
    new = text[:i] + block() + text[j:]
    if '--check' in sys.argv:
        if os.path.exists(CATALOG_UPSTREAM) and open(CATALOG_UPSTREAM, 'rb').read() != open(CATALOG, 'rb').read():
            print('gen-srclib: the vendored capability catalogue differs from ' + CATALOG_UPSTREAM); sys.exit(1)
        if new != text:
            print('gen-srclib: 21-check.kotoba is out of date'); sys.exit(1)
        print('gen-srclib: up to date'); return
    open(DST, 'w', encoding='utf-8').write(new)
    print('gen-srclib: wrote', DST)


if __name__ == '__main__':
    main()
