from pathlib import Path
import json,hashlib,tarfile,subprocess
r=Path('/Users/junkawasaki/github/wt/amu-seed17');w=Path('/private/tmp/amu-loop-descriptor-20261006');c=Path('/private/tmp/amu-loop-region-census-20261006');d=r/'docs/evidence/coscientist-loop-descriptor-20261006';d.mkdir(parents=True,exist_ok=True);load=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();t=load(w/'timing-summary.json');assert not t['fullCandidateQualifies'] and not t['individuallyQualifies'];assert (r/'seed/41-a64gen.kotoba').read_bytes()==(w/'baseline-41-a64gen.kotoba').read_bytes()
s={'status':'rejected-native-dynamic-key-loop-descriptor-cache','baselineSourceCommit':load(w/'hypothesis.json')['sourceCommit'],'decision':'All17 changed original guests freshly timed. None qualifies unchanged1.05+gap>sumSD rule; reject complete prototype, no product change and no identical-code retiming.','hypothesis':load(w/'hypothesis.json'),'generations':load(w/'generations.json'),'nativeAdmission':load(w/'meta-admission.json'),'instructionAudit':load(w/'instruction-audit.json'),'codeChanges':load(w/'code-change.json'),'nativePreflightSealedBeforeTiming':load(w/'preflight-audit.json'),'timing':t,'productChanged':False,'officialEmbenchScore':False,'COrBetter':False,'productGatesAndIntegration':'Not rerun after performance rejection; preceding qualified product remains current.','nativeCensus':{'entries':load(c/'loop-census.json')['entries'],'countsAreNotTimeShares':True,'observerTargetBytesEqualAll19':True},'nextActualHighTempCensus':load(c/'high-temp-read-census.json'),'authoringCorrections':load(w/'proof-authoring-corrections.json'),'additionalPostTimingStartObserverCorrection':load(w/'ports-state-observer-correction.json')}
for name,key in [('loop-state-proof.json','loopHandProof'),('leaf-proof.json','leafOwnershipProof'),('import-proof.json','openImportProof'),('effect-proof.json','actualEffectsProof'),('resource-proof.json','resourcePartialWrites'),('regression-proof.json','freshOriginalRegression'),('ports-state.json','additionalOriginal19StateProof')]:
 v=load(w/name);s[key]={k:x for k,x in v.items() if k not in ['runs','observations']}
s['additionalOriginal19StateProof']['completedAfterTimingStarted']=True;s['newFixtureLayout']=load(w/'loop-layout-audit.json');(d/'summary.json').write_text(json.dumps(s,indent=2)+'\n');(d/'archive.py').write_bytes(Path(__file__).read_bytes());(d/'timing-summary.json').write_bytes((w/'timing-summary.json').read_bytes());q=subprocess.run(['git','diff','--no-index',str(w/'baseline-41-a64gen.kotoba'),str(w/'41-a64gen-prototype.kotoba')],capture_output=True,text=True);assert q.returncode==1;(d/'prototype.diff').write_text(q.stdout)
with tarfile.open(d/'native-proof.tgz','w:gz') as a:
 for x in sorted(w.iterdir()):
  if x.name in ['__pycache__','timing-package','timing.log','regression-run']:continue
  if x.name.startswith('timing-artifact-audit-') or x.name.startswith('timing-audit-'):continue
  a.add(x,arcname=x.name)
 for n in ['seed/MANIFEST','seed/SIR','seed/HEADS','seed/MEMORY-MAP','AGENTS.md','tools/kexe_loader.c','scripts/seed/a64gen-fixtures.py','seed/tests/unit/41-a64gen.expected']:a.add(r/n,arcname='baseline-source/'+n)
 for n in ['clobber-state-loader.c','clobber-state-loader']:a.add(Path('/private/tmp/amu-context-call-20261005')/n,arcname='diagnostic/'+n)
with tarfile.open(d/'census.tgz','w:gz') as a:
 for x in sorted(c.iterdir()):
  if x.name=='__pycache__':continue
  a.add(x,arcname=x.name)
with tarfile.open(d/'timing.tgz','w:gz') as a:
 for n in ['remote-timing.py','timing-package','audit-workload.py','timing-artifact-audit.py','timing-summary.json','batch-status.json','timing.log']:a.add(w/n,arcname=n)
 for x in sorted(w.iterdir()):
  if x.name.startswith('timing-audit-') or x.name.startswith('timing-artifact-audit-'):a.add(x,arcname=x.name)
next={'status':'registered-not-implemented-or-measured','hypothesis':'Inline high-temp vector-at in retained original nonleaf frame: preserve original gn-save0t homes, load vector/index into free x0/x1, restore x7, emit original handle/index checks and load, then original gn-take. Keep gn-inl/prescan unchanged so caller register assignment/frame/fuel publication remain original. No loop cache and no handle/descriptor hoisting.','actualCensus':load(c/'high-temp-read-census.json'),'evidence':'Matmult inner loop has an ordinary read at t5 and second read at t6. Originalgn-inl accepts only t<=5; t6 executes real C helper, invalidates loop cache each iteration. SHA256 has5 additional high-temp C-read sites. Staticcounts are not time shares.','proofRequirements':'Actualnativeall19 admission/quietbytes, signed/rawinvalidhandles/indices, highdepth/livehomes/locals/coalescedresults, private/public fuel and SIGILL/resource parity, actualallocatingimports, fixedpoint; freshquiet30triples everychangedguest original1.05+sumSD, thenpermanentregression/fullgates/integrated3gen/per-casecorpus beforepromotion.','scope':'C-or-better acrossall19 canonical originalalignedworkloads; no official-score or100percent claim.','ABI':'No x18, no ABI mutation, x0/x1 only if originalnonleaf; refuse if scratch ownership not proved.'};(d/'next-hypothesis.json').write_text(json.dumps(next,indent=2)+'\n');(d/'checksums.sha256').write_text(''.join(sha(x)+'  '+x.name+'\n' for x in sorted(d.iterdir()) if x.is_file() and x.name!='checksums.sha256'));print('PASS rejected all17 experiment, actualnativecensus, full proofs and rawtiming archived')
