p = 'docs/codegen-coscientist.md'
s = open(p).read()
entry = '''2026-09-07 23:24 JST (amu-rank cron, tick 241): rank-only busy pass, no measurement by role. git fetch: origin/main ADVANCED since tick-240 read - 69c1fd9a -> 55e47f90 (two commits: 1f9c8e07 docs "name the whole delivery path, not just the release", and 55e47f90 Merge PR #880 from agent/build-scaling-delivery-note - both doc-only, origin-namespace, NOT local-reconcilable, NOT cited as a local verdict (rank rule: reconciliation authoritative only after operator merge); neither alters the local fleet gate). Host busy (pre-run monitor 23:21 load1 22.36 / 5m 29.40 / 15m 27.32; live probe 23:22 load1 20.72 / 5m 27.33 / 15m 26.71, up 2d 16:05, 10 users, threshold 7.5) - measurement refused; the only correct measurement route (fleet) remains blocked locally below. Working-tree evidence reviewed since the tick-240 commit (HEAD f99e744b, via git diff HEAD): the ONLY uncommitted doc change is a sibling amu-bench 23:08 busy-refusal (load1 53.47 / 5m 29.41 / 15m 22.02, up 2d 15:51, 10 users, no measurement, no numbers) folded into the Iteration-log tail - a busy refusal, NOT a new LOCAL measured number. No new local codegen ADR since 0339 (J-B idle-gate +7.3/+7.0/+6.4% 17-consecutive-positive separated - but ADR 0339 and predecessors 0335/0338 all still stamp "diagnostic only, full quiet gate not yet met", so perfgate.core/qualify confirmation remains PENDING; ADR 0339 itself remains UNTRACKED/residue locally). No new LOCAL measured verdict -> no re-rank, no status transition, no new hypothesis; population unchanged: H-Z3 top of codegen ladder (quiet-host A/B still blocked), H-C2 open w/ ceiling-caution (statically 61/61, timed A/B UNRESOLVED, notional ~4.4% pending quiet host), H-D/H-B/H-Y1 open. BLOCKER unchanged double (live re-probed this tick): scripts/quiet-host.cljs + scripts/remote-bench.cljs STILL ABSENT from this workdir (PR #819 unmerged locally) while present on origin; guard-glob `git status --porcelain -- src bench scripts deps.edn` = 106 untracked lines (residue: append/probe scripts under docs/ + scripts/, bench/runtime-comparison/kernel.kotoba.wasm.{provenance,publication}.edn sidecars, tmp/, build.sh, Q9-migration-plan.edn, test-kotoba-pipeline.sh, w1-pure.wasm.{provenance,publication}.edn), so even a merged PR #819 would exit-2 on remote-bench.cljs's uncommitted-tree guard until that residue is cleared. Fleet-path measurement remains blocked until then. NEXT (unchanged, tick-213..241 rank authority): operator merges origin/main AND clears the docs/+scripts/+bench/+tmp residue; then H-Z3 quiet-host A/B (top lever) on a qualifying fleet node, then H-C2 ceiling-check A/B. Appended via python script (no heredoc / no -e/-c / no shell redirect).

## Standing honesty constraints'''
marker = '## Standing honesty constraints'
if marker in s:
    s = s.replace(marker, entry)
    open(p, 'w').write(s)
    print('APPENDED docs/codegen-coscientist.md (tick 241)')
else:
    print('MARKER NOT FOUND - ABORT')